"use client";

const n=(v:any,d=1)=>v==null?"—":Number(v).toFixed(d);
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(1)} pp`;
const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:Math.abs(Number(v))>=1e6?`$${(Number(v)/1e6).toFixed(2)}M`:`$${Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}`;

function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="card stat-card"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}

export default function FundamentalContextV4({fund}:{fund:any}){
 const a=fund?.fundamental_assessment||{},inputs=a?.inputs||{},peer=fund?.fundamental_peer_context||{},history=fund?.fundamental_history||{},flags=a?.flags||[];
 const anomaly=String(a?.anomaly||"not assessed").replaceAll("_"," ");
 return <div className="v3-stack">
  <div className="command-stat-grid">
   <Metric label="Fundamental quality" value={n(a?.quality_score)} detail={`${a?.confidence||"low"} confidence · ${a?.coverage==null?"—":`${Math.round(Number(a.coverage)*100)}%`} component coverage`}/>
   <Metric label="Valuation quality" value={n(a?.valuation_score)} detail="Separate from business quality; not a return forecast."/>
   <Metric label="Valuation anomaly" value={anomaly} detail={a?.valuation_applicability?.pe_meaningful?"Trailing P/E is economically applicable.":"P/E is not used as a cheapness signal."}/>
   <Metric label="Peer context" value={peer?.available?`${n(peer?.valuation_quality_percentile,0)}th pct":"Insufficient"} detail={peer?.available?`${peer.peer_count} cached ${peer.basis} peers`:"Requires at least 3 contemporaneous cached peers."}/>
  </div>
  {flags.length>0&&<details className="card methodology-dropdown" open><summary><strong>Fundamental flags</strong><span>{flags.length}</span><b>▾</b></summary><div className="intel-scroll">{flags.map((x:any,i:number)=><div className="intel-catalyst-row" key={`${x.code}-${i}`}><span className={`data-badge ${x.severity==="warning"?"derived":"cached"}`}>{String(x.severity||"info").toUpperCase()}</span><div><strong>{String(x.code||"flag").replaceAll("_"," ")}</strong><small>{x.detail}</small></div></div>)}</div></details>}
  <details className="card methodology-dropdown" open><summary><strong>Quality drivers</strong><span>{a?.scores?Object.keys(a.scores).length:0}</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Growth</i><strong>{n(a?.scores?.growth)}</strong></span><span><i>Profitability</i><strong>{n(a?.scores?.profitability)}</strong></span><span><i>Balance sheet</i><strong>{n(a?.scores?.balance_sheet)}</strong></span><span><i>Cash flow</i><strong>{n(a?.scores?.cash_flow)}</strong></span><span><i>Revenue growth YoY</i><strong>{inputs?.revenue_growth_yoy_percent==null?"—":`${n(inputs.revenue_growth_yoy_percent,1)}%`}</strong></span><span><i>Earnings growth YoY</i><strong>{inputs?.earnings_growth_yoy_percent==null?"—":`${n(inputs.earnings_growth_yoy_percent,1)}%`}</strong></span><span><i>Net margin</i><strong>{inputs?.profit_margin_percent==null?"—":`${n(inputs.profit_margin_percent,1)}%`}</strong></span><span><i>Margin change YoY</i><strong>{pct(inputs?.profit_margin_change_yoy_points)}</strong></span><span><i>ROE</i><strong>{inputs?.return_on_equity_percent==null?"—":`${n(inputs.return_on_equity_percent,1)}%`}</strong></span><span><i>Debt / equity</i><strong>{n(inputs?.debt_to_equity)}</strong></span><span><i>Current ratio</i><strong>{n(inputs?.current_ratio)}</strong></span><span><i>Free cash flow</i><strong>{money(inputs?.free_cash_flow)}</strong></span></div></details>
  <details className="card methodology-dropdown" open><summary><strong>Peer valuation</strong><span>{peer?.available?`${peer.peer_count} peers`:"insufficient"}</span><b>▾</b></summary>{peer?.available?<div className="metric-tile-grid"><span><i>Quality percentile</i><strong>{n(peer.quality_percentile,0)}th</strong></span><span><i>Valuation-quality percentile</i><strong>{n(peer.valuation_quality_percentile,0)}th</strong></span><span><i>P/E percentile</i><strong>{n(peer.pe_percentile,0)}th</strong></span><span><i>P/S percentile</i><strong>{n(peer.price_to_sales_percentile,0)}th</strong></span><span><i>Peer median P/E</i><strong>{n(peer?.peer_medians?.pe_ratio)}</strong></span><span><i>Peer median P/S</i><strong>{n(peer?.peer_medians?.price_to_sales_ratio)}</strong></span></div>:<p className="muted">No reliable cached peer comparison is available yet. Missing peers are not imputed.</p>}<p className="muted small-note">{peer?.policy}</p></details>
  <details className="card methodology-dropdown"><summary><strong>Point-in-time fundamental history</strong><span>{history?.observations??0} observations</span><b>▾</b></summary>{history?.available?<div className="intel-scroll">{(history.history||[]).slice(-24).reverse().map((x:any)=><div className="intel-flow-row" key={x.date}><div><strong>{x.date}</strong><small>{String(x.anomaly||"neutral").replaceAll("_"," ")}</small></div><div><b>Q {n(x.quality_score,1)}</b><small>Val {n(x.valuation_score,1)}</small></div></div>)}</div>:<p className="muted">Historical assessment is intentionally unavailable until at least two genuine stored V4 observations exist.</p>}<p className="muted small-note">{history?.policy}</p></details>
 </div>
}