"use client";

import {useEffect,useMemo,useState} from "react";
import {AuthGate,type Account} from "../auth-shell";
import DeepLinksV4 from "./deep-links-v4";
import OpportunityTableV4 from "./opportunity-table-v4";
import MacroRotationTableV4 from "./macro-rotation-table-v4";
import ResearchMetricStripV4 from "./research-metric-strip-v4";
import "./v4.css";

const API="/backend";
const REQUEST_TIMEOUT_MS=12000;
type LayerKey="research"|"macro"|"opportunity"|"deployment";
type Overview={version:string;pipeline:string[];layers:Record<LayerKey,any>;sources?:any[]};
type Deployment={basket:string;capital:number;eligible:any[];unavailable:any[];methodology:string;model:string;fundamental_score_policy?:string};

async function requestJson(url:string,init?:RequestInit,timeoutMs=REQUEST_TIMEOUT_MS){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(url,{cache:"no-store",credentials:"include",...init,signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("This view took too long to respond. Retry without losing your current layer.");throw e}finally{clearTimeout(t)}}
const n=(v:any,d=1)=>v==null?"—":Number(v).toFixed(d);
const words=(v:any)=>String(v||"").replaceAll("_"," ");
const when=(v:any)=>{if(!v)return "—";const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString()};
const arr=(v:any):any[]=>Array.isArray(v)?v:[];
const normalizeRotation=(x:any)=>({...((x&&typeof x==="object")?x:{}),rows:arr(x?.rows),early_rotation:arr(x?.early_rotation),outflow_risk:arr(x?.outflow_risk)});
const normalizeFunnel=(x:any)=>({...((x&&typeof x==="object")?x:{}),candidates:arr(x?.candidates??x?.rows),rows:arr(x?.rows??x?.candidates),stages:arr(x?.stages)});
const normalizeDeployment=(x:any)=>({...((x&&typeof x==="object")?x:{}),eligible:arr(x?.eligible),unavailable:arr(x?.unavailable)});

export default function V4(){return <AuthGate>{account=><DecisionStack account={account}/>}</AuthGate>}

function DecisionStack({account}:{account:Account}){
 const[overview,setOverview]=useState<Overview|null>(null),[deployment,setDeployment]=useState<Deployment|null>(null),[rotation,setRotation]=useState<any>(null),[funnel,setFunnel]=useState<any>(null),[research,setResearch]=useState<any>(null);
 const[active,setActive]=useState<LayerKey>("research"),[capital,setCapital]=useState(1000),[basket,setBasket]=useState("ai-buildout"),[symbol,setSymbol]=useState("NBIS");
 const[loading,setLoading]=useState(true),[error,setError]=useState(""),[deployLoading,setDeployLoading]=useState(false),[researchLoading,setResearchLoading]=useState(false),[funnelLoading,setFunnelLoading]=useState(false),[rotationLoading,setRotationLoading]=useState(false),[enrichLoading,setEnrichLoading]=useState(false),[enrichMsg,setEnrichMsg]=useState("");
 async function load(){setLoading(true);setError("");try{setOverview(await requestJson(`${API}/api/v1/stack/overview`))}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}}
 async function loadDeployment(){setDeployLoading(true);setError("");try{setDeployment(normalizeDeployment(await requestJson(`${API}/api/v1/stack/deployment?basket=${encodeURIComponent(basket)}&capital=${capital}`)))}catch(e:any){setError(e?.message||String(e))}finally{setDeployLoading(false)}}
 async function loadRotation(){if(rotation)return;setRotationLoading(true);try{setRotation(normalizeRotation(await requestJson(`${API}/api/v1/stack/rotation`)))}catch(e:any){setError(e?.message||String(e))}finally{setRotationLoading(false)}}
 async function loadFunnel(force=false){if(funnel&&!force)return;setFunnelLoading(true);try{setFunnel(normalizeFunnel(await requestJson(`${API}/api/v1/stack/candidates?limit=60`)))}catch(e:any){setError(e?.message||String(e))}finally{setFunnelLoading(false)}}
 async function enrichFunnel(){setEnrichLoading(true);setEnrichMsg("");setError("");try{const r=await requestJson(`${API}/api/v1/stack/candidates/enrich?limit=60`,{method:"POST"});setEnrichMsg(`${r.jobs_added||0} enrichment job${r.jobs_added===1?"":"s"} queued`);await loadFunnel(true)}catch(e:any){setError(e?.message||String(e))}finally{setEnrichLoading(false)}}
 async function loadResearch(target?:string){const s=(target??symbol).trim().toUpperCase();if(!s)return;setResearchLoading(true);setError("");try{setResearch(await requestJson(`${API}/api/v1/stack/research/${encodeURIComponent(s)}`));setSymbol(s)}catch(e:any){setError(e?.message||String(e))}finally{setResearchLoading(false)}}
 function openResearch(target:string){const s=target.trim().toUpperCase();setSymbol(s);setActive("research");loadResearch(s)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(active==="macro")loadRotation();if(active==="opportunity")loadFunnel();if(active==="deployment"&&!deployment)loadDeployment();if(active==="research"&&!research)loadResearch()},[active]);
 const layer=overview?.layers?.[active];
 const pipeline=useMemo(()=>[["research","Research","What is happening?"],["macro","Macro","Where is capital moving?"],["opportunity","Opportunity","Where is the asymmetry?"],["deployment","Deployment","Where should the next dollar go?"]] as const,[]);
 if(loading)return <main className="v4-shell"><div className="v4-loading" role="status">Loading Daily Report decision stack…</div></main>;
 const rstate=research?.rotation_context?.state;
 const coverage=funnel?.coverage||{};
 const verification=funnel?.verification||{};
 const partialOpportunity=funnel&&coverage.market_wide_ready===false;
 return <main className="v4-shell">
  <header className="v4-header"><div><span className="v4-kicker">DAILY REPORT V4 · DEVELOPMENT BUILD</span><h1>Decision Stack</h1><p>Research → Macro → Opportunity → Deployment</p></div><div className="v4-user"><span>{account.name}</span><small>{overview?.version||"4.5-dev"}</small></div></header>
  {error&&<div className="v4-error" role="alert"><span>{error}</span><button onClick={()=>{setError("");if(active==="research")loadResearch();else if(active==="macro"){setRotation(null);loadRotation()}else if(active==="opportunity")loadFunnel(true);else loadDeployment()}}>Retry</button></div>}
  <section className="v4-pipeline" aria-label="Decision pipeline">{pipeline.map(([key,title,question],i)=><button key={key} aria-pressed={active===key} className={active===key?"active":""} onClick={()=>{setError("");setActive(key)}}><span>{i+1}</span><div><strong>{title}</strong><small>{question}</small></div></button>)}</section>

  {active==="research"&&<section className="v4-grid">
   <article className="v4-card hero"><span className="label">Research coverage</span><strong>{layer?.tracked_symbols??0}</strong><p>Watchlist + portfolio symbols feeding the decision stack.</p></article>
   <article className="v4-card"><span className="label">Stored market snapshots</span><strong>{layer?.stored_market_snapshots??0}</strong><p>Shared cached observations reused across layers.</p></article>
   <article className="v4-card"><span className="label">Feature snapshots</span><strong>{layer?.stored_feature_snapshots??0}</strong><p>Point-in-time score history and derived features.</p></article>
   <article className="v4-card wide research-search"><div><span className="label">Security workspace</span><h2>Unified ticker research</h2><p className="muted">Cache-first composition of market, fundamentals, theme/sector rotation, flow, theses and score history.</p></div><div className="control-row"><input aria-label="Ticker" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} onKeyDown={e=>{if(e.key==="Enter")loadResearch()}} placeholder="Ticker"/><button onClick={()=>loadResearch()} disabled={researchLoading}>{researchLoading?"Loading…":"Open"}</button></div></article>
   {research&&<>
    <article className="v4-card"><span className="label">{research.symbol}</span><strong>{research.market?.price==null?"—":`$${n(research.market.price,2)}`}</strong><p>{research.registry?.name||research.registry?.sector||"Stored security"}</p><ResearchMetricStripV4 research={research}/></article>
    <article className="v4-card"><span className="label">Opportunity score</span><strong>{n(research.latest_features?.buy_score,1)}</strong><p>{research.score_history?.buy_score_change==null?"No prior point":`${research.score_history.buy_score_change>=0?"+":""}${n(research.score_history.buy_score_change,1)} since prior snapshot`}</p><div className="mini-stats"><span>W%R <b>{n(research.latest_features?.williams_r,1)}</b></span><span>Model <b>{research.latest_features?.model_version||"legacy"}</b></span></div></article>
    <article className="v4-card"><span className="label">Rotation context · {research.rotation_context?.proxy||"unmapped"}</span><strong className="small-strong">{words(rstate?.state)||"Unmapped"}</strong><p>{rstate?`${n(rstate.rotation_pressure,2)} pressure · ${n(rstate.conviction,0)} conviction · ${research.rotation_context?.basis}`:"No applicable proxy mapping"}</p><div className="mini-stats"><span>History <b>{rstate?.observations??0}</b></span><span>Age <b>{rstate?.data_age_hours==null?"—":`${n(rstate.data_age_hours,0)}h`}</b></span><span>Flow events <b>{research.flow_72h?.events??0}</b></span></div></article>
    <article className="v4-card wide source-card"><div><span className="label">Transparency</span><h2>Data state & sources</h2></div><div className="source-state-grid"><span><i>Market</i><b>{research.data_state?.market?"available":"missing"}</b></span><span><i>Fundamentals</i><b>{research.data_state?.fundamentals?"available":"missing"}</b></span><span><i>Feature history</i><b>{research.data_state?.feature_history_points??0} points</b></span><span><i>Market timestamp</i><b>{when(research.market?.retrieved_at)}</b></span><span><i>Market provider</i><b>{research.market?.provider||research.market?.technical_source||"—"}</b></span><span><i>Verification</i><b>{words(research.market?.verification_status||"unknown")}</b></span></div>{research.market?.source_url&&<a className="source-link" href={research.market.source_url} target="_blank" rel="noreferrer">Open market source ↗</a>}</article>
    <article className="v4-card wide"><div className="section-head"><div><span className="label">Explainability</span><h2>Why the score moved</h2></div><strong>{research.score_history?.history?.length||0} points</strong></div>{research.score_history?.model_version_changed&&<div className="v4-warning">Score formula version changed between compared snapshots; direct point attribution is disabled.</div>}<div className="driver-grid"><div><h3>Positive score attribution</h3>{(research.score_history?.largest_positive_drivers||[]).map((x:any)=><div className="driver" key={x.component}><span>{x.component}</span><b>{x.buy_score_contribution_delta==null?"—":`+${n(x.buy_score_contribution_delta,2)}`}</b></div>)}{!(research.score_history?.largest_positive_drivers||[]).length&&<p className="muted">No positive component contribution.</p>}</div><div><h3>Negative score attribution</h3>{(research.score_history?.largest_negative_drivers||[]).map((x:any)=><div className="driver" key={x.component}><span>{x.component}</span><b>{n(x.buy_score_contribution_delta,2)}</b></div>)}{!(research.score_history?.largest_negative_drivers||[]).length&&<p className="muted">No negative component contribution.</p>}</div><div><h3>Underlying observations</h3>{(research.score_history?.raw_driver_changes||[]).slice(0,5).map((x:any)=><div className="driver" key={x.field}><span>{x.label}</span><b>{x.delta==null?"—":`${x.delta>=0?"+":""}${n(x.delta,2)}`}</b></div>)}</div></div></article>
    <article className="v4-card wide"><h2>Fundamental + thesis context</h2><div className="research-context"><div className="mini-stats vertical"><span>P/E <b>{n(research.fundamentals?.pe_ratio,1)}</b></span><span>P/S <b>{n(research.fundamentals?.price_to_sales_ratio,1)}</b></span><span>Revenue growth <b>{research.fundamentals?.quarterly_revenue_growth_yoy==null?"—":`${n(Number(research.fundamentals.quarterly_revenue_growth_yoy)*100,1)}%`}</b></span></div><div>{(research.theses||[]).map((t:any)=><div className="thesis" key={t.id}><strong>{t.title}</strong><p>{t.statement}</p></div>)}{!(research.theses||[]).length&&<p className="muted">No active thesis attached to this ticker.</p>}</div></div></article>
   </>}
  </section>}

  {active==="macro"&&<section className="v4-grid">
   {rotationLoading&&!rotation&&<article className="v4-card wide"><p className="muted" role="status">Loading rotation state…</p></article>}
   <article className="v4-card wide"><div className="section-head"><div><span className="label">Rotation model v4</span><h2>Leadership + transition state</h2></div><strong>{rotation?.rows?.length??0} groups</strong></div><MacroRotationTableV4 rotation={rotation} onOpen={openResearch}/></article>
   <article className="v4-card"><span className="label">Early rotation</span><h2>Improving laggards</h2>{arr(rotation?.early_rotation).map((x:any)=><button className="compact-row row-button" key={x.symbol} onClick={()=>openResearch(x.symbol)}><strong>{x.symbol}</strong><span>{x.name}</span><b>{n(x.conviction,0)}</b></button>)}</article>
   <article className="v4-card"><span className="label">Outflow risk</span><h2>Weakening leadership</h2>{arr(rotation?.outflow_risk).map((x:any)=><button className="compact-row row-button" key={x.symbol} onClick={()=>openResearch(x.symbol)}><strong>{x.symbol}</strong><span>{x.name}</span><b>{n(x.rotation_pressure,1)}</b></button>)}</article>
   <article className="v4-card"><span className="label">Persisted history</span><h2>{layer?.rotation_history_days??0} days</h2><p className="muted">Background-captured state observations accumulating for forward-outcome calibration.</p></article>
   <article className="v4-card wide"><p className="muted">{rotation?.methodology}</p></article>
  </section>}

  {active==="opportunity"&&<section className="v4-grid">
   {funnelLoading&&!funnel&&<article className="v4-card wide"><p className="muted" role="status">Loading measured opportunity coverage and candidate funnel…</p></article>}
   {funnel&&<article className={`v4-card wide coverage-card ${partialOpportunity?"partial":"ready"}`}><div className="section-head"><div><span className="label">Scanner coverage</span><h2>{partialOpportunity?"Partial cached-market scan":"Market-wide scanner ready"}</h2></div><strong>{n(coverage.cached_snapshot_coverage_percent,1)}%</strong></div><div className="source-state-grid"><span><i>Registry universe</i><b>{coverage.registry_scannable??0}</b></span><span><i>Cached scannable</i><b>{coverage.cached_scannable??0}</b></span><span><i>Technical complete</i><b>{coverage.technical_complete??0}</b></span><span><i>Technical coverage</i><b>{n(coverage.technical_coverage_percent,1)}%</b></span><span><i>Verified</i><b>{verification.verified??0}</b></span><span><i>Primary only</i><b>{verification.primary_only??0}</b></span><span><i>Last cache update</i><b>{when(funnel.last_cache_update)}</b></span></div>{partialOpportunity&&<div className="v4-warning">{coverage.limitation||"Results represent the cached subset only and are not complete market coverage."}</div>}</article>}
   <article className="v4-card wide"><div className="section-head"><div><span className="label">Candidate funnel</span><h2>{partialOpportunity?"Cached market → qualified setups":"Broad market → qualified setups"}</h2></div><div className="control-row"><strong>{funnel?.candidates?.length??0}</strong><button onClick={enrichFunnel} disabled={enrichLoading||!(funnel?.deep_enrichment_symbols||[]).length}>{enrichLoading?"Queueing…":"Enrich shortlist"}</button></div></div><div className="funnel-stages">{(funnel?.stages||[]).map((x:any,i:number)=><div key={x.name}><span>{i+1}</span><strong>{x.name}</strong><b>{x.input} → {x.output}</b><small>{x.rule}</small></div>)}</div>{enrichMsg&&<p className="muted">{enrichMsg}</p>}</article>
   <article className="v4-card wide"><h2>Highest-ranked market candidates</h2><OpportunityTableV4 rows={(funnel?.candidates||[]).slice(0,60)} onOpen={openResearch}/><p className="muted">{funnel?.methodology||layer?.methodology}</p></article>
  </section>}

  {active==="deployment"&&<section className="v4-grid">
   <article className="v4-card wide deployment-controls"><div><span className="label">New capital</span><h2>Williams Priority deployment</h2><p>Cross-sectional allocation only. Existing positions are not rebalanced.</p></div><div className="control-row"><select aria-label="Deployment basket" value={basket} onChange={e=>setBasket(e.target.value)}><option value="ai-buildout">AI Buildout Basket</option><option value="watchlist">Watchlist + Portfolio</option></select><label>$<input aria-label="New capital" type="number" min="0" step="500" value={capital} onChange={e=>setCapital(Number(e.target.value)||0)}/></label><button onClick={loadDeployment} disabled={deployLoading}>{deployLoading?"Calculating…":"Calculate"}</button></div></article>
   {deployment&&<article className="v4-card wide"><div className="section-head"><div><span className="label">{deployment.model}</span><h2>{deployment.basket}</h2></div><strong>${Number(deployment.capital).toLocaleString()}</strong></div><div className="allocation-list">{deployment.eligible.map((x:any)=><button className="allocation-row-button" key={x.symbol} onClick={()=>openResearch(x.symbol)}><div><strong>{x.priority_rank}. {x.symbol}</strong><small>14M W%R {n(x.williams_r,1)} · {x.signal_month}</small><small>Fundamental {x.fundamental_score?.score==null?"—":n(x.fundamental_score.score,1)} · {x.fundamental_score?.grade||"insufficient data"} · {Math.round(Number(x.fundamental_score?.coverage||0)*100)}% coverage</small></div><span>{(Number(x.priority_weight)*100).toFixed(1)}%</span><b>${Number(x.suggested_dollars).toLocaleString()}</b></button>)}</div><details className="deployment-fundamentals"><summary>Fundamental score details</summary>{deployment.eligible.map((x:any)=><div className="fundamental-detail" key={`fund-${x.symbol}`}><strong>{x.symbol} · {x.fundamental_score?.score==null?"—":n(x.fundamental_score.score,1)}</strong><span>{x.fundamental_score?.grade||"insufficient data"} · {Math.round(Number(x.fundamental_score?.coverage||0)*100)}% evidence coverage</span><small>{(x.fundamental_score?.components||[]).map((c:any)=>`${words(c.factor)} ${n(c.score,0)}`).join(" · ")||"No cached fundamental evidence yet."}</small><small>{x.fundamental_source?`${x.fundamental_source.provider} · ${when(x.fundamental_source.retrieved_at)}`:"Source pending cache population"}</small></div>)}</details><p className="muted">{deployment.fundamental_score_policy}</p>{deployment.unavailable?.length>0&&<div className="v4-warning">Unavailable: {deployment.unavailable.map((x:any)=>`${x.symbol} (${x.reason})`).join(", ")}</div>}<p className="muted">{deployment.methodology}</p></article>}
  </section>}
  <footer className="v4-footer">Four-layer decision stack · focus first, expandable detail, source transparency, measured coverage.</footer>
  <DeepLinksV4 layer={active}/>
 </main>
}
