"use client";
import {FormEvent,useState} from "react";

const API="/backend";
async function post(path:string,body:any,timeout=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${API}${path}`,{method:"POST",credentials:"include",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("Scenario calculation timed out. Retry when stored market data is available.");throw e}finally{clearTimeout(t)}}
const money=(v:any)=>v==null?"—":Number(v).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2});
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
const num=(v:any,d=2)=>v==null?"—":Number(v).toFixed(d);

export default function PortfolioScenarioV4({portfolioId}:{portfolioId:number|null}){
 const[symbol,setSymbol]=useState(""),[amount,setAmount]=useState("1000"),[funding,setFunding]=useState("cash"),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function run(e:FormEvent){e.preventDefault();if(!portfolioId||!symbol.trim())return;setLoading(true);setError("");try{setData(await post(`/api/v1/portfolios/${portfolioId}/scenario/buy`,{symbol:symbol.trim().toUpperCase(),amount:Number(amount),funding_source:funding}))}catch(e:any){setData(null);setError(e.message)}finally{setLoading(false)}}
 const b=data?.before||{},a=data?.after||{},c=data?.changes||{},risk=data?.candidate_risk||{},hedge=data?.hedge_reference||{};
 return <details className="card methodology-dropdown" open><summary><div><strong>What-if position scenario</strong><span className="muted">read-only · no holdings change</span></div><b>▾</b></summary>
  <form className="suite-form" onSubmit={run}><div className="metric-tile-grid"><label><i>Ticker</i><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker" required/></label><label><i>Buy amount</i><input className="search" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" type="number" min="1" required/></label><label><i>Funding</i><select className="search" value={funding} onChange={e=>setFunding(e.target.value)}><option value="cash">Existing cash</option><option value="external">External capital</option></select></label></div><button className="btn" disabled={loading}>{loading?"Calculating…":"Run scenario"}</button></form>
  {error&&<div className="suite-error" role="alert"><span>{error}</span></div>}
  {data&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>{data.symbol} exposure</span><strong>{num(a.symbol_exposure_percent)}%</strong><small>{num(b.symbol_exposure_percent)}% → {num(a.symbol_exposure_percent)}%</small></article><article className="card stat-card"><span>{a.sector||"Sector"} exposure</span><strong>{a.sector_exposure_percent==null?"—":`${num(a.sector_exposure_percent)}%`}</strong><small>{b.sector_exposure_percent==null?"unmapped":`${num(b.sector_exposure_percent)}% → ${num(a.sector_exposure_percent)}%`}</small></article><article className="card stat-card"><span>Cash weight</span><strong>{num(a.cash_percent)}%</strong><small>{num(b.cash_percent)}% → {num(a.cash_percent)}%</small></article><article className="card stat-card"><span>Historical volatility</span><strong>{a.annualized_volatility_percent==null?"—":`${num(a.annualized_volatility_percent)}%`}</strong><small>{c.annualized_volatility_points==null?"insufficient history":`${pct(c.annualized_volatility_points)} points`}</small></article><article className="card stat-card"><span>Historical max drawdown</span><strong className="negative">{a.historical_max_drawdown_percent==null?"—":`${num(a.historical_max_drawdown_percent)}%`}</strong><small>{c.historical_max_drawdown_points==null?"insufficient history":`${pct(c.historical_max_drawdown_points)} points`}</small></article><article className="card stat-card"><span>Portfolio correlation</span><strong>{num(risk.portfolio_correlation,3)}</strong><small>{risk.correlation_observations||0} overlapping sessions</small></article></div>
   <details className="card methodology-dropdown"><summary><strong>Incremental risk</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Scenario weight</i><strong>{num(risk.scenario_weight_percent)}%</strong></span><span><i>Standalone annualized vol</i><strong>{risk.standalone_annualized_volatility_percent==null?"—":`${num(risk.standalone_annualized_volatility_percent)}%`}</strong></span><span><i>Standalone max drawdown</i><strong>{risk.standalone_max_drawdown_percent==null?"—":`${num(risk.standalone_max_drawdown_percent)}%`}</strong></span><span><i>Approx. drawdown contribution</i><strong>{risk.approx_drawdown_contribution_points==null?"—":`${num(risk.approx_drawdown_contribution_points)} pts`}</strong></span><span><i>Estimated shares</i><strong>{num(data.estimated_shares,4)}</strong></span><span><i>Reference price</i><strong>{money(data.candidate_price)}</strong></span></div></details>
   {!!data.theme_changes?.length&&<details className="card methodology-dropdown"><summary><strong>Theme exposure changes</strong><span>{data.theme_changes.length}</span><b>▾</b></summary><div className="mini-grid">{data.theme_changes.map((x:any)=><span key={x.theme}><strong>{x.theme}</strong><b>{num(x.before_percent)}% → {num(x.after_percent)}%</b><small>{x.delta_points>=0?"+":""}{num(x.delta_points)} pts</small></span>)}</div></details>}
   <details className="card methodology-dropdown"><summary><strong>Hedge reference</strong><span>{hedge.available?hedge.reference?.symbol:"unavailable"}</span><b>▾</b></summary>{hedge.available?<div className="metric-tile-grid"><span><i>Best stored proxy</i><strong>{hedge.reference.symbol}</strong></span><span><i>Correlation</i><strong>{num(hedge.reference.correlation,3)}</strong></span><span><i>Historical beta</i><strong>{num(hedge.reference.beta,3)}</strong></span><span><i>Observations</i><strong>{hedge.reference.observations}</strong></span></div>:<p className="muted">{hedge.reason}</p>}<p className="muted small-note">{hedge.interpretation||hedge.policy}</p></details>
   <p className="muted small-note">{data.policy}</p></div>}
 </details>
}
