"use client";
import {useMemo,useState} from "react";

const API="/backend";
async function post(path:string,body:any,timeout=20000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${API}${path}`,{method:"POST",credentials:"include",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
const money=(v:any)=>v==null?"—":`$${Number(v).toLocaleString(undefined,{maximumFractionDigits:0})}`;
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;

export default function StrategyLabV4({symbol}:{symbol:string}){
 const[start,setStart]=useState("2020-01-01"),[end,setEnd]=useState(""),[threshold,setThreshold]=useState(-80),[contribution,setContribution]=useState(1000),[scoreThreshold,setScoreThreshold]=useState(70),[loading,setLoading]=useState(""),[error,setError]=useState(""),[williams,setWilliams]=useState<any>(null),[formula,setFormula]=useState<any>(null);
 const defaultFormula=useMemo(()=>({williams:60,ma100_proximity:30,ma100_slope:5,approach_velocity:5}),[]);
 async function runWilliams(){setLoading("williams");setError("");try{setWilliams(await post(`/api/v1/security/${symbol}/strategy-lab/williams`,{start,end:end||null,contribution,threshold,window:14}))}catch(e:any){setError(e.message)}finally{setLoading("")}}
 async function runFormula(){setLoading("formula");setError("");try{setFormula(await post(`/api/v1/security/${symbol}/strategy-lab/formula`,{criteria:defaultFormula,filters:[],score_threshold:scoreThreshold,start:start||null,end:end||null}))}catch(e:any){setError(e.message)}finally{setLoading("")}}
 const dca=williams?.strategy_1_monthly_dca||{},wr=williams?.strategy_2_williams_timeline||{};
 return <div className="v3-stack">
  <div className="card suite-hero"><div><span className="eyebrow">Stored-data research</span><h3>Strategy Lab · {symbol}</h3><p className="muted">Run deterministic historical tests against stored OHLCV. No provider calls occur during a test and future bars never enter historical signals.</p></div></div>
  {error&&<div className="suite-error" role="alert"><strong>Strategy test failed</strong><span>{error}</span></div>}
  <details className="card methodology-dropdown" open><summary><strong>Williams Timeline Test</strong><span>DCA vs threshold deployment</span><b>▾</b></summary><div className="metric-tile-grid"><label><i>Start</i><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><i>End</i><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label><i>Monthly contribution</i><input type="number" min="1" value={contribution} onChange={e=>setContribution(Number(e.target.value))}/></label><label><i>Williams threshold</i><input type="number" min="-100" max="0" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label></div><button className="btn" disabled={!!loading} onClick={runWilliams}>{loading==="williams"?"Running…":"Run Williams test"}</button>{williams&&<><div className="command-stat-grid"><article className="card stat-card"><span>Monthly DCA</span><strong>{money(dca.total_value)}</strong><small>{pct(dca.return_pct)} return</small></article><article className="card stat-card"><span>Williams deployment</span><strong>{money(wr.total_value)}</strong><small>{pct(wr.return_pct)} return</small></article><article className="card stat-card"><span>Williams triggers</span><strong>{wr.triggers?.length||0}</strong><small>{money(wr.total_invested)} deployed</small></article><article className="card stat-card"><span>Remaining cash</span><strong>{money(wr.remaining_cash)}</strong><small>{williams.parameters?.start} → {williams.parameters?.end}</small></article></div><details className="card methodology-dropdown"><summary><strong>Trigger ledger</strong><span>{wr.triggers?.length||0}</span><b>▾</b></summary><div className="intel-scroll">{(wr.triggers||[]).map((x:any)=><div className="intel-flow-row" key={x.date}><div><strong>{x.date}</strong><small>Williams {Number(x.williams_r).toFixed(1)}</small></div><div><b>{money(x.amount_invested)}</b><small>@ ${Number(x.close).toFixed(2)}</small></div></div>)}</div></details><p className="muted small-note">{williams.methodology}</p></>}</details>
  <details className="card methodology-dropdown" open><summary><strong>Default Opportunity formula history</strong><span>5 / 20 / 60 / 120D outcomes</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Formula</i><strong>60% Williams · 30% 100MA · 5% slope · 5% approach</strong></span><label><i>Signal threshold</i><input type="number" min="0" max="100" value={scoreThreshold} onChange={e=>setScoreThreshold(Number(e.target.value))}/></label></div><button className="btn" disabled={!!loading} onClick={runFormula}>{loading==="formula"?"Running…":"Run formula history"}</button>{formula&&<><div className="command-stat-grid">{[5,20,60,120].map(h=>{const x=formula.forward_returns?.[String(h)]||{};return <article className="card stat-card" key={h}><span>{h}D forward</span><strong>{pct(x.mean_return_pct)}</strong><small>{x.samples||0} samples · {x.positive_rate==null?"—":`${Math.round(Number(x.positive_rate)*100)}%`} positive</small></article>})}</div><p className="muted">Signals: <b>{formula.signal_count}</b>. Fundamental criteria are intentionally excluded from historical formula tests until genuine point-in-time fundamental history accumulates.</p><p className="muted small-note">{formula.methodology}</p></>}</details>
 </div>
}
