from __future__ import annotations

# Additive macro universe. These symbols are merged into services.rotation.SECTORS
# at application startup so the existing market refresh/cache path is reused.
EXPANDED_MACRO = {
    "IWM": "Russell 2000 / Small Caps",
    "RSP": "S&P 500 Equal Weight",
    "MTUM": "U.S. Momentum Factor",
    "QUAL": "U.S. Quality Factor",
    "SPLV": "U.S. Low Volatility",
    "EFA": "Developed Markets ex-U.S.",
    "EEM": "Emerging Markets",
    "EWJ": "Japan",
    "VGK": "Europe",
    "FXI": "China Large Caps",
    "ITB": "U.S. Home Construction",
    "XHB": "Homebuilders",
    "XRT": "Retail / Consumer Breadth",
    "SKYY": "Cloud Computing",
    "FDN": "Internet / Digital Economy",
    "GRID": "Grid Infrastructure",
    "REMX": "Rare Earths & Strategic Metals",
    "SLV": "Silver",
    "GDX": "Gold Miners",
    "ICLN": "Clean Energy",
    "TAN": "Solar",
    "LQD": "Investment Grade Credit",
    "JNK": "High Yield Credit",
    "IEF": "7-10Y Treasuries",
    "TLT": "Long Treasuries",
    "SHY": "Short Treasuries",
    "TIP": "Inflation-Protected Treasuries",
    "HYG": "High Yield Credit",
    "UUP": "U.S. Dollar",
    "USO": "Crude Oil",
    "IBIT": "Bitcoin",
    "CPER": "Copper",
}

MACRO_CATEGORIES = {
    "SPY": "U.S. Market", "QQQ": "U.S. Market", "IWM": "U.S. Market", "RSP": "U.S. Market",
    "MTUM": "Factors", "QUAL": "Factors", "SPLV": "Factors",
    "XLK": "Sectors", "XLF": "Sectors", "XLE": "Sectors", "XLV": "Sectors", "XLI": "Sectors",
    "XLY": "Sectors", "XLP": "Sectors", "XLB": "Sectors", "XLU": "Sectors", "XLRE": "Sectors", "XLC": "Sectors",
    "SMH": "Technology Themes", "EUV": "Technology Themes", "DRAM": "Technology Themes", "NCLD": "Technology Themes",
    "IGV": "Technology Themes", "CIBR": "Technology Themes", "SKYY": "Technology Themes", "FDN": "Technology Themes",
    "QTUM": "Technology Themes", "BOTZ": "Technology Themes",
    "ITA": "Industrial / Infrastructure", "ARKX": "Industrial / Infrastructure", "PAVE": "Industrial / Infrastructure",
    "GRID": "Industrial / Infrastructure", "IYT": "Industrial / Infrastructure",
    "NLR": "Energy / Materials", "URA": "Energy / Materials", "COPX": "Energy / Materials", "CPER": "Energy / Materials",
    "XME": "Energy / Materials", "GLD": "Energy / Materials", "SLV": "Energy / Materials", "GDX": "Energy / Materials",
    "REMX": "Energy / Materials", "USO": "Energy / Materials", "ICLN": "Energy / Materials", "TAN": "Energy / Materials",
    "KRE": "Credit / Financial Conditions", "LQD": "Credit / Financial Conditions", "HYG": "Credit / Financial Conditions",
    "JNK": "Credit / Financial Conditions",
    "SHY": "Rates / Dollar", "IEF": "Rates / Dollar", "TLT": "Rates / Dollar", "TIP": "Rates / Dollar", "UUP": "Rates / Dollar",
    "EFA": "Global Equity", "EEM": "Global Equity", "EWJ": "Global Equity", "VGK": "Global Equity", "FXI": "Global Equity",
    "ITB": "Consumer / Housing", "XHB": "Consumer / Housing", "XRT": "Consumer / Housing",
    "XBI": "Healthcare Themes", "IBIT": "Alternative Risk",
}

TRACKING_RATIONALE = {
    "U.S. Market": "Broad cap-weight, equal-weight and small-cap breadth to distinguish narrow mega-cap strength from broad risk appetite.",
    "Factors": "Momentum, quality and low-volatility leadership help identify the market style being rewarded.",
    "Sectors": "Primary U.S. sector rotation baseline.",
    "Technology Themes": "Separates semiconductors, memory, photonics, cloud, software, cybersecurity, quantum and robotics from broad technology.",
    "Industrial / Infrastructure": "Defense, reshoring, transport, grid and infrastructure capex exposure.",
    "Energy / Materials": "Oil, nuclear, uranium, metals, miners and clean-energy duration sensitivity.",
    "Credit / Financial Conditions": "Investment-grade, high-yield and regional-bank behavior as a financing/risk-stress check.",
    "Rates / Dollar": "Duration, inflation protection and dollar pressure proxies.",
    "Global Equity": "Regional leadership outside the U.S. and sensitivity to dollar/global growth shifts.",
    "Consumer / Housing": "Rate-sensitive housing and equal-weight retail breadth.",
    "Healthcare Themes": "High-beta biotech risk appetite inside healthcare.",
    "Alternative Risk": "Bitcoin as a high-beta liquidity/risk-appetite cross-check.",
}
