"use client";
import {FormEvent,ReactNode,useEffect,useState} from "react";

const API="/backend";
export type Account={id:string;email:string;name:string|null;name_required:boolean;role:string;status:string;enabled:boolean};
async function request(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}

export function AuthGate({children}:{children:(account:Account)=>ReactNode}){
 const[account,setAccount]=useState<Account|null>(null),[checking,setChecking]=useState(true),[mode,setMode]=useState<"login"|"register">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[name,setName]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[working,setWorking]=useState(false);
 const refresh=async()=>{setChecking(true);try{const d=await request("/api/v1/auth/session");setAccount(d.account)}catch{setAccount(null)}finally{setChecking(false)}};
 useEffect(()=>{localStorage.removeItem("dailyReportUserEmail");localStorage.removeItem("dailyReportUserToken");refresh();const h=()=>refresh();window.addEventListener("daily-report-session-changed",h);return()=>window.removeEventListener("daily-report-session-changed",h)},[]);
 async function submit(e:FormEvent){e.preventDefault();setWorking(true);setError("");setMessage("");try{if(mode==="login"){const d=await request("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})});setPassword("");setAccount(d.account)}else{const d=await request("/api/v1/auth/register",{method:"POST",body:JSON.stringify({email,password})});setPassword("");setMessage(d.message||"Account request submitted for approval.")}}catch(e:any){setError(e.message)}finally{setWorking(false)}}
 async function saveName(e:FormEvent){e.preventDefault();if(!name.trim())return;setWorking(true);setError("");try{const d=await request("/api/v1/auth/profile",{method:"PUT",body:JSON.stringify({name:name.trim()})});setAccount(d.account)}catch(e:any){setError(e.message)}finally{setWorking(false)}}
 if(checking)return <main className="container startup-screen auth-startup"><div className="brand-lockup"><div className="brand-mark">⌁</div><div><h1>Daily Report</h1><p className="muted">Checking secure session</p></div></div><div className="card auth-loading-card"><span className="eyebrow">Secure access</span><h2>Opening Daily Report</h2><p className="muted">Restoring your encrypted account session.</p><div className="loading-track"><i/></div></div></main>;
 if(!account)return <main className="container auth-screen"><div className="auth-layout"><section className="auth-brand"><div className="brand-lockup"><div className="brand-mark">⌁</div><div><h1>Daily Report</h1><p className="muted">Private market intelligence workspace</p></div></div><div><span className="eyebrow">Protected access</span><h2>{mode==="login"?"Sign in":"Request an account"}</h2><p className="muted">Credentials are sent only to the authenticated backend. Passwords are never stored or returned in readable form.</p></div></section><form className="card auth-card" onSubmit={submit}><div className="view-toggle auth-toggle"><button type="button" className={`toggle ${mode==="login"?"active":""}`} onClick={()=>{setMode("login");setError("");setMessage("")}}>Sign in</button><button type="button" className={`toggle ${mode==="register"?"active":""}`} onClick={()=>{setMode("register");setError("");setMessage("")}}>Create account</button></div><label>Email<input className="search" type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input className="search" type="password" autoComplete={mode==="login"?"current-password":"new-password"} required minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==="register"&&<p className="muted small-note">Use at least 12 characters with a letter and a number. New accounts remain locked until the administrator approves them.</p>}{error&&<div className="inline-error">{error}</div>}{message&&<div className="auth-message">{message}</div>}<button className="btn auth-primary" disabled={working}>{working?"Working…":mode==="login"?"Sign in":"Submit account request"}</button></form></div></main>;
 if(account.name_required)return <main className="container auth-screen"><form className="card auth-card onboarding-card" onSubmit={saveName}><span className="eyebrow">First login</span><h1>Welcome</h1><p className="muted">Enter the name you want Daily Report to use on your loading screen and account settings.</p><label>Name<input className="search" autoComplete="name" maxLength={100} required value={name} onChange={e=>setName(e.target.value)}/></label>{error&&<div className="inline-error">{error}</div>}<button className="btn auth-primary" disabled={working}>{working?"Saving…":"Continue"}</button></form></main>;
 return <>{children(account)}</>;
}

export function AccountSettings({account}:{account:Account}){
 const[name,setName]=useState(account.name||""),[email,setEmail]=useState(account.email),[currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState(""),[pending,setPending]=useState<any[]>([]),[mailConfigured,setMailConfigured]=useState<boolean|null>(null),[loadingPending,setLoadingPending]=useState(false);
 useEffect(()=>{setName(account.name||"");setEmail(account.email)},[account.name,account.email]);
 async function saveProfile(e:FormEvent){e.preventDefault();setError("");setStatus("");try{await request("/api/v1/auth/profile",{method:"PUT",body:JSON.stringify({name,email,current_password:email.trim().toLowerCase()!==account.email.trim().toLowerCase()?currentPassword:undefined})});setCurrentPassword("");setStatus("Account details updated.");window.dispatchEvent(new Event("daily-report-session-changed"))}catch(e:any){setError(e.message)}}
 async function changePassword(e:FormEvent){e.preventDefault();setError("");setStatus("");try{await request("/api/v1/auth/password",{method:"PUT",body:JSON.stringify({current_password:currentPassword,new_password:newPassword})});setCurrentPassword("");setNewPassword("");setStatus("Password updated and other sessions were signed out.")}catch(e:any){setError(e.message)}}
 async function logout(){await request("/api/v1/auth/logout",{method:"POST"}).catch(()=>null);window.dispatchEvent(new Event("daily-report-session-changed"))}
 async function loadPending(){if(account.role!=="owner")return;setLoadingPending(true);try{const d=await request("/api/v1/auth/admin/pending");setPending(d.accounts||[]);setMailConfigured(!!d.approval_email_notifications_configured)}catch(e:any){setError(e.message)}finally{setLoadingPending(false)}}
 useEffect(()=>{loadPending()},[account.role]);async function decide(id:string,decision:"approve"|"reject"){setError("");try{await request(`/api/v1/auth/admin/accounts/${encodeURIComponent(id)}/${decision}`,{method:"POST"});await loadPending()}catch(e:any){setError(e.message)}}
 return <section className="account-settings"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Private account</span><h2>Account & security</h2><p className="muted">Your email and name are encrypted at rest. Your password is represented only by a salted one-way hash.</p></div><span className="data-badge cached">{account.role}</span></div><div className="suite-two"><form className="card reveal-card suite-form" onSubmit={saveProfile}><h2>Profile</h2><label>Name<input className="search" value={name} onChange={e=>setName(e.target.value)} maxLength={100}/></label><label>Email<input className="search" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{email.trim().toLowerCase()!==account.email.trim().toLowerCase()&&<label>Current password<input className="search" type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} placeholder="Required to change email"/></label>}<button className="btn">Save profile</button></form><form className="card reveal-card suite-form" onSubmit={changePassword}><h2>Change password</h2><label>Current password<input className="search" type="password" autoComplete="current-password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>New password<input className="search" type="password" autoComplete="new-password" required minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><button className="btn">Update password</button><button className="btn danger" type="button" onClick={logout}>Sign out</button></form></div>{status&&<div className="auth-message">{status}</div>}{error&&<div className="inline-error">{error}</div>}{account.role==="owner"&&<div className="card reveal-card"><div className="section-head"><div><span className="eyebrow">Administrator</span><h2>Pending account approvals</h2><p className="muted">{mailConfigured===true?"Email notifications are enabled.":mailConfigured===false?"Approval requests are recorded here; email delivery is waiting for the private Gmail SMTP app-password secret.":"Checking approval notification status…"}</p></div><button className="btn" onClick={loadPending} disabled={loadingPending}>{loadingPending?"Refreshing…":"Refresh"}</button></div>{pending.length?<div className="approval-list">{pending.map(p=><div className="approval-row" key={p.id}><div><strong>{p.email}</strong><span className="muted">Requested {p.created_at?new Date(p.created_at).toLocaleString():"recently"}</span></div><div><button className="btn" onClick={()=>decide(p.id,"approve")}>Approve</button><button className="btn danger" onClick={()=>decide(p.id,"reject")}>Reject</button></div></div>)}</div>:<p className="muted">No account requests are waiting for approval.</p>}</div>}</section>;
}
