"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {navigateTo,type NavigationTarget} from "./navigation-context";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function headers(){const e=typeof window!=="undefined"?localStorage.getItem("dailyReportUserEmail")||"":"",t=typeof window!=="undefined"?localStorage.getItem("dailyReportUserToken")||"":"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
function Loading(){return <div className="suite-skeleton">{Array.from({length:7}).map((_,i)=><span key={i}/>)}</div>}

export default function EventsWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[data,setData]=useState<any>(null),[tracked,setTracked]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[trackedError,setTrackedError]=useState(""),[tab,setTab]=useState("Calendar"),[impact,setImpact]=useState("all"),[category,setCategory]=useState("all"),[sort,setSort]=useState("date"),[order,setOrder]=useState("asc");
 const[title,setTitle]=useState(""),[eventDate,setEventDate]=useState(""),[symbol,setSymbol]=useState(""),[customImpact,setCustomImpact]=useState("medium"),[description,setDescription]=useState("");
 async function load(){setLoading(true);setError("");setTrackedError("");const[a,b]=await Promise.allSettled([api("/api/v1/events?days=365&sort=date&order=asc&limit=1200"),api("/api/v1/events/tracked-companies?days=365&scope=all&refresh_missing=true&max_refresh=20")]);if(a.status==="fulfilled")setData(a.value);else setError(a.reason?.message||"Macro calendar failed to load");if(b.status==="fulfilled")setTracked(b.value);else setTrackedError(b.reason?.message||"Tracked-company calendar failed to load");setLoading(false)}
 async function loadTracked(){setTrackedError("");try{setTracked(await api("/api/v1/events/tracked-companies?days=365&scope=all&refresh_missing=true&max_refresh=20"))}catch(e:any){setTrackedError(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(navigation?.tab==="Events"&&navigation.subtab)setTab(navigation.subtab)},[navigation?.nonce]);
 const sourceRows=useMemo(()=>{if(["Tracked Companies","Markets","Portfolios"].includes(tab)){const rows=tracked?.events||[];if(tab==="Markets")return rows.filter((e:any)=>(e.tracked_via||[]).includes("Markets"));if(tab==="Portfolios")return rows.filter((e:any)=>(e.tracked_via||[]).includes("Portfolio"));return rows}let rows=[...(data?.events||[])];if(tab==="My Events")rows=rows.filter((x:any)=>x.source==="User event");return rows},[data,tracked,tab]);
 const filtered=useMemo(()=>{let rows=[...sourceRows];if(impact!=="all")rows=rows.filter((x:any)=>x.impact===impact);if(category!=="all")rows=rows.filter((x:any)=>x.category===category);const dir=order==="asc"?1:-1;rows.sort((a:any,b:any)=>{let av:any,bv:any;if(sort==="impact"){av=a.impact_score||0;bv=b.impact_score||0}else if(sort==="category"){av=a.category||"";bv=b.category||""}else{av=`${a.event_date||""} ${a.time||""}`;bv=`${b.event_date||""} ${b.time||""}`}return av>bv?dir:av<bv?-dir:0});return rows},[sourceRows,impact,category,sort,order]);
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const e of filtered){const d=e.event_date||"Unscheduled";m.set(d,[...(m.get(d)||[]),e])}return [...m.entries()]},[filtered]);
 const categories=useMemo(()=>Array.from(new Set([...(data?.categories||[]),...(tracked?.events||[]).map((x:any)=>x.category).filter(Boolean)])).sort(),[data,tracked]);
 async function add(e:FormEvent){e.preventDefault();await api("/api/v1/events/custom",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_date:eventDate,title,impact:customImpact,category:"Custom",symbol:symbol||null,description:description||null})});setTitle("");setEventDate("");setSymbol("");setDescription("");await load();setTab("My Events")}
 async function remove(id:number){await api(`/api/v1/events/custom/${id}`,{method:"DELETE"});await load()}
 const tabs=["Calendar","Tracked Companies","Markets","Portfolios","My Events","Sources"];
 const trackedView=["Tracked Companies","Markets","Portfolios"].includes(tab);
 return <section className="tab-panel v3-workspace events-v3"><div className="card suite-hero"><div><span className="eyebrow">Catalyst calendar</span><h2>Events</h2><p className="muted">Macro schedules and tracked-company catalysts load independently so a slow company-calendar source cannot blank the main calendar.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh all"}</button></div><div className="subtab-bar">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Macro events degraded</strong><span>{error}</span></div>}{trackedError&&trackedView&&<div className="suite-error"><strong>Tracked-company events degraded</strong><span>{trackedError}</span><button className="btn" onClick={loadTracked}>Retry company calendars</button></div>}{loading&&!data&&!tracked?<Loading/>:<>
 {tab!=="Sources"&&<><details className="card methodology-dropdown event-filters"><summary><strong>Filters & sorting</strong><span className="muted">{filtered.length} events shown</span><b>▾</b></summary><div className="v2-toolbar"><label>Impact<select className="search" value={impact} onChange={e=>setImpact(e.target.value)}><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Category<select className="search" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All</option>{categories.map((x:any)=><option key={x}>{x}</option>)}</select></label><label>Sort<select className="search" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date</option><option value="impact">Impact</option><option value="category">Category</option></select></label><label>Order<select className="search" value={order} onChange={e=>setOrder(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div></details>
 {groups.length?<div className="event-v2-list">{groups.map(([d,events])=><details className="card event-v2-day" key={d}><summary><div><span className="eyebrow">{d}</span><strong>{events.length} event{events.length===1?"":"s"}</strong></div><span className="reason-count">{events.filter((x:any)=>x.impact==="high").length} high</span><b>▾</b></summary><div>{events.map((e:any,i:number)=><details className={`event-v2-item impact-${e.impact}`} data-security-symbol={e.symbol||undefined} key={`${e.title}-${i}`}><summary><span className={`data-badge ${e.impact==="high"?"live":e.impact==="medium"?"derived":"cached"}`}>{String(e.impact||"low").toUpperCase()}</span><strong>{e.time?`${e.time} · `:""}{e.title}</strong><span>{e.category}{e.symbol?` · ${e.symbol}`:""}</span><b>▾</b></summary><div><p>{e.description||"Scheduled market event."}</p><div className="event-meta"><span>{e.source}</span>{e.tracked_via?.length>0&&<span>Tracked via {e.tracked_via.join(" + ")}</span>}{e.symbol&&<button className="text-btn" onClick={()=>navigateTo({tab:"Research",symbol:e.symbol,subtab:"Overview"})}>Research {e.symbol} →</button>}{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Source ↗</a>}{e.custom_event_id&&<button className="text-btn danger" onClick={()=>remove(e.custom_event_id)}>Delete</button>}</div></div></details>)}</div></details>)}</div>:<div className="card inline-state"><span>{trackedView?"No tracked-company dates are resolved in this window yet. Retry company calendars to hydrate another bounded batch.":"No events matched this view."}</span>{trackedView&&<button className="btn" onClick={loadTracked}>Refresh company calendars</button>}</div>}</>}
 {tab==="My Events"&&<form className="card suite-form custom-event-form" onSubmit={add}><span className="eyebrow">Private calendar</span><h3>Add custom catalyst</h3><div className="form-pair"><input className="search" type="date" required value={eventDate} onChange={e=>setEventDate(e.target.value)}/><select className="search" value={customImpact} onChange={e=>setCustomImpact(e.target.value)}><option value="low">Low impact</option><option value="medium">Medium impact</option><option value="high">High impact</option></select></div><input className="search" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Event title"/><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker (optional)"/><input className="search" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Why it matters / notes"/><button className="btn">Add event</button></form>}
 {tab==="Sources"&&<div className="v3-stack"><div className="provider-chip-grid">{(data?.providers||[]).map((p:any,i:number)=><span key={`${p.provider}-${i}`}><strong>{p.provider}</strong><b>{p.count}</b><small>{p.status}</small></span>)}</div><details className="card methodology-dropdown"><summary><strong>Tracked company hydration</strong><span>{tracked?.count||0} events</span><b>▾</b></summary><p>{tracked?.methodology}</p><p className="muted">Markets: {tracked?.markets_symbols?.length||0} symbols · Portfolios: {tracked?.portfolio_symbols?.length||0} symbols · refreshed this request: {tracked?.refreshed_symbols?.length||0} · deferred: {tracked?.deferred_symbols?.length||0}</p>{tracked?.unresolved_symbols?.length>0&&<p className="muted">No upcoming calendar date currently resolved for: {tracked.unresolved_symbols.join(", ")}</p>}{trackedError&&<p className="negative">{trackedError}</p>}</details>{data?.errors?.length>0&&<details className="card methodology-dropdown"><summary><strong>Degraded providers</strong><span>{data.errors.length}</span><b>▾</b></summary>{data.errors.map((x:string,i:number)=><p className="muted" key={i}>{x}</p>)}</details>}<details className="card methodology-dropdown"><summary><strong>Calendar methodology</strong><b>▾</b></summary><p>{data?.methodology}</p></details></div>}
 </>}</section>
}
