"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {navigateTo,type NavigationTarget} from "./navigation-context";

const API="/backend";
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
function Loading(){return <div className="suite-skeleton">{Array.from({length:7}).map((_,i)=><span key={i}/>)}</div>}
function EventItem({e,onRemove}:{e:any;onRemove?:(id:number)=>void}){return <details className={`event-v2-item impact-${e.impact}`} data-security-symbol={e.symbol||undefined}><summary><span className={`data-badge ${e.impact==="high"?"live":e.impact==="medium"?"derived":"cached"}`}>{String(e.impact||"low").toUpperCase()}</span><strong>{e.time?`${e.time} · `:""}{e.title}</strong><span>{e.category}{e.symbol?` · ${e.symbol}`:""}</span><b>▾</b></summary><div><p>{e.description||"Scheduled market event."}</p><div className="event-meta"><span>{e.source}</span>{e.tracked_via?.length>0&&<span>Tracked via {e.tracked_via.join(" + ")}</span>}{e.symbol&&<button className="text-btn" onClick={()=>navigateTo({tab:"Research",symbol:e.symbol,subtab:"Intelligence"})}>Research {e.symbol} →</button>}{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Source ↗</a>}{e.custom_event_id&&onRemove&&<button className="text-btn danger" onClick={()=>onRemove(e.custom_event_id)}>Delete</button>}</div></div></details>}
function severity(events:any[]){if(events.some(e=>e.impact==="high"&&e.symbol&&(e.tracked_via||[]).length))return "tracked-high";if(events.some(e=>e.impact==="high"))return "high";if(events.length)return "minor";return "none"}
function CalendarGrid({events,month,onSelect,selected}:{events:any[];month:Date;onSelect:(d:string)=>void;selected:string}){const year=month.getFullYear(),m=month.getMonth(),first=new Date(year,m,1),last=new Date(year,m+1,0),lead=first.getDay(),days=last.getDate();const byDate=new Map<string,any[]>();for(const e of events){const d=e.event_date;if(d)byDate.set(d,[...(byDate.get(d)||[]),e])}const cells=Array.from({length:lead+days},(_,i)=>i<lead?null:i-lead+1);return <div className="calendar-shell"><div className="calendar-weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{cells.map((day,i)=>{if(!day)return <span className="calendar-blank" key={`b-${i}`}/>;const iso=`${year}-${String(m+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,rows=byDate.get(iso)||[],sev=severity(rows);return <button className={`calendar-day severity-${sev} ${selected===iso?"selected":""}`} key={iso} onClick={()=>onSelect(iso)}><strong>{day}</strong><span>{rows.length?`${rows.length} event${rows.length===1?"":"s"}`:"No events"}</span>{sev==="tracked-high"&&<b>Tracked</b>}</button>})}</div><div className="calendar-legend"><span className="severity-none">No events</span><span className="severity-minor">Minor</span><span className="severity-high">Significant</span><span className="severity-tracked-high">Tracked-stock significant</span></div></div>}

export default function EventsWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[data,setData]=useState<any>(null),[tracked,setTracked]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[trackedError,setTrackedError]=useState(""),[tab,setTab]=useState("Calendar"),[view,setView]=useState("calendar"),[impact,setImpact]=useState("all"),[category,setCategory]=useState("all"),[sort,setSort]=useState("date"),[order,setOrder]=useState("asc"),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selectedDate,setSelectedDate]=useState("");
 const[title,setTitle]=useState(""),[eventDate,setEventDate]=useState(""),[symbol,setSymbol]=useState(""),[customImpact,setCustomImpact]=useState("medium"),[description,setDescription]=useState("");
 async function load(){setLoading(true);setError("");setTrackedError("");const[a,b]=await Promise.allSettled([api("/api/v1/events?days=365&sort=date&order=asc&limit=1200"),api("/api/v1/events/tracked-companies?days=365&scope=all&refresh_missing=true&max_refresh=20")]);if(a.status==="fulfilled")setData(a.value);else setError(a.reason?.message||"Macro calendar failed to load");if(b.status==="fulfilled")setTracked(b.value);else setTrackedError(b.reason?.message||"Tracked-company calendar failed to load");setLoading(false)}
 async function loadTracked(){setTrackedError("");try{setTracked(await api("/api/v1/events/tracked-companies?days=365&scope=all&refresh_missing=true&max_refresh=20"))}catch(e:any){setTrackedError(e.message)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(navigation?.tab==="Events"&&navigation.subtab)setTab(navigation.subtab)},[navigation?.nonce]);
 const mergedCalendarRows=useMemo(()=>{const all=[...(data?.events||[]),...(tracked?.events||[])],seen=new Set<string>();return all.filter((e:any)=>{const k=[e.event_date,e.time,e.title,e.symbol,e.source].join("|");if(seen.has(k))return false;seen.add(k);return true})},[data,tracked]);
 const sourceRows=useMemo(()=>{if(tab==="Calendar")return mergedCalendarRows;if(["Tracked Companies","Markets","Portfolios"].includes(tab)){const rows=tracked?.events||[];if(tab==="Markets")return rows.filter((e:any)=>(e.tracked_via||[]).includes("Markets"));if(tab==="Portfolios")return rows.filter((e:any)=>(e.tracked_via||[]).includes("Portfolio"));return rows}let rows=[...(data?.events||[])];if(tab==="My Events")rows=rows.filter((x:any)=>x.source==="User event");return rows},[data,tracked,tab,mergedCalendarRows]);
 const filtered=useMemo(()=>{let rows=[...sourceRows];if(impact!=="all")rows=rows.filter((x:any)=>x.impact===impact);if(category!=="all")rows=rows.filter((x:any)=>x.category===category);const dir=order==="asc"?1:-1;rows.sort((a:any,b:any)=>{let av:any,bv:any;if(sort==="impact"){av=a.impact_score||0;bv=b.impact_score||0}else if(sort==="category"){av=a.category||"";bv=b.category||""}else{av=`${a.event_date||""} ${a.time||""}`;bv=`${b.event_date||""} ${b.time||""}`}return av>bv?dir:av<bv?-dir:0});return rows},[sourceRows,impact,category,sort,order]);
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const e of filtered){const d=e.event_date||"Unscheduled";m.set(d,[...(m.get(d)||[]),e])}return [...m.entries()]},[filtered]);
 const categories=useMemo(()=>Array.from(new Set([...(data?.categories||[]),...(tracked?.events||[]).map((x:any)=>x.category).filter(Boolean)])).sort(),[data,tracked]);
 const selectedEvents=useMemo(()=>selectedDate?filtered.filter((e:any)=>e.event_date===selectedDate):[],[filtered,selectedDate]);
 async function add(e:FormEvent){e.preventDefault();await api("/api/v1/events/custom",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_date:eventDate,title,impact:customImpact,category:"Custom",symbol:symbol||null,description:description||null})});setTitle("");setEventDate("");setSymbol("");setDescription("");await load();setTab("My Events")}
 async function remove(id:number){await api(`/api/v1/events/custom/${id}`,{method:"DELETE"});await load()}
 function shiftMonth(delta:number){setMonth(x=>new Date(x.getFullYear(),x.getMonth()+delta,1));setSelectedDate("")}
 const tabs=["Calendar","Tracked Companies","Markets","Portfolios","My Events","Sources"],trackedView=["Tracked Companies","Markets","Portfolios"].includes(tab);
 return <section className="tab-panel v3-workspace events-v3"><div className="card suite-hero"><div><span className="eyebrow">Catalyst calendar</span><h2>Events</h2><p className="muted">Calendar severity combines macro events with tracked-company catalysts. Company calendar hydration remains bounded and cached so navigation does not trigger repeated provider pulls.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh all"}</button></div><div className="subtab-bar">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Macro events degraded</strong><span>{error}</span></div>}{trackedError&&trackedView&&<div className="suite-error"><strong>Tracked-company events degraded</strong><span>{trackedError}</span><button className="btn" onClick={loadTracked}>Retry company calendars</button></div>}{loading&&!data&&!tracked?<Loading/>:<>
 {tab!=="Sources"&&<><details className="card methodology-dropdown event-filters"><summary><strong>Filters & sorting</strong><span className="muted">{filtered.length} events shown</span><b>▾</b></summary><div className="v2-toolbar"><label>Impact<select className="search" value={impact} onChange={e=>setImpact(e.target.value)}><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Category<select className="search" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All</option>{categories.map((x:any)=><option key={x}>{x}</option>)}</select></label><label>Sort<select className="search" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date</option><option value="impact">Impact</option><option value="category">Category</option></select></label><label>Order<select className="search" value={order} onChange={e=>setOrder(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div></details>
 {tab==="Calendar"&&<div className="v3-stack"><div className="card calendar-controls"><button className="btn" onClick={()=>shiftMonth(-1)}>← Previous</button><strong>{month.toLocaleString(undefined,{month:"long",year:"numeric"})}</strong><button className="btn" onClick={()=>shiftMonth(1)}>Next →</button><div className="view-toggle"><button className={`toggle ${view==="calendar"?"active":""}`} onClick={()=>setView("calendar")}>Calendar</button><button className={`toggle ${view==="agenda"?"active":""}`} onClick={()=>setView("agenda")}>Agenda</button></div></div>{view==="calendar"?<><CalendarGrid events={filtered} month={month} selected={selectedDate} onSelect={setSelectedDate}/>{selectedDate&&<div className="card selected-day-card"><div className="section-head"><div><span className="eyebrow">Selected day</span><h3>{selectedDate}</h3></div><span className="reason-count">{selectedEvents.length} events</span></div><div className="card-scroll-region">{selectedEvents.length?selectedEvents.map((e:any,i:number)=><EventItem key={`${e.title}-${i}`} e={e} onRemove={remove}/>):<p className="muted">No events on this day.</p>}</div></div>}</>:<div className="event-v2-list">{groups.map(([d,events])=><details className="card event-v2-day" key={d}><summary><div><span className="eyebrow">{d}</span><strong>{events.length} event{events.length===1?"":"s"}</strong></div><span className="reason-count">{events.filter((x:any)=>x.impact==="high").length} high</span><b>▾</b></summary><div className="card-scroll-region">{events.map((e:any,i:number)=><EventItem key={`${e.title}-${i}`} e={e} onRemove={remove}/>)}</div></details>)}</div>}</div>}
 {tab!=="Calendar"&&groups.length?<div className="event-v2-list">{groups.map(([d,events])=><details className="card event-v2-day" key={d}><summary><div><span className="eyebrow">{d}</span><strong>{events.length} event{events.length===1?"":"s"}</strong></div><span className="reason-count">{events.filter((x:any)=>x.impact==="high").length} high</span><b>▾</b></summary><div className="card-scroll-region">{events.map((e:any,i:number)=><EventItem key={`${e.title}-${i}`} e={e} onRemove={remove}/>)}</div></details>)}</div>:tab!=="Calendar"&&tab!=="Sources"&&<div className="card inline-state"><span>{trackedView?"No tracked-company dates are resolved in this window yet.":"No events matched this view."}</span>{trackedView&&<button className="btn" onClick={loadTracked}>Refresh company calendars</button>}</div>}</>}
 {tab==="My Events"&&<form className="card suite-form custom-event-form" onSubmit={add}><span className="eyebrow">Private calendar</span><h3>Add custom catalyst</h3><div className="form-pair"><input className="search" type="date" required value={eventDate} onChange={e=>setEventDate(e.target.value)}/><select className="search" value={customImpact} onChange={e=>setCustomImpact(e.target.value)}><option value="low">Low impact</option><option value="medium">Medium impact</option><option value="high">High impact</option></select></div><input className="search" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Event title"/><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker (optional)"/><input className="search" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Why it matters / notes"/><button className="btn">Add event</button></form>}
 {tab==="Sources"&&<div className="v3-stack"><div className="provider-chip-grid">{(data?.providers||[]).map((p:any,i:number)=><span key={`${p.provider}-${i}`}><strong>{p.provider}</strong><b>{p.count}</b><small>{p.status}</small></span>)}</div><details className="card methodology-dropdown"><summary><strong>Tracked company hydration</strong><span>{tracked?.count||0} events</span><b>▾</b></summary><p>{tracked?.methodology}</p><p className="muted">Markets: {tracked?.markets_symbols?.length||0} · Portfolios: {tracked?.portfolio_symbols?.length||0} · refreshed this request: {tracked?.refreshed_symbols?.length||0} · deferred: {tracked?.deferred_symbols?.length||0}</p></details><details className="card methodology-dropdown"><summary><strong>Calendar methodology</strong><b>▾</b></summary><p>{data?.methodology}</p></details></div>}
 </>}</section>
}
