"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
function Loading(){return <div className="suite-skeleton">{Array.from({length:7}).map((_,i)=><span key={i}/>)}</div>}

export default function EventsWorkspaceV3(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Calendar"),[impact,setImpact]=useState("all"),[category,setCategory]=useState("all"),[sort,setSort]=useState("date"),[order,setOrder]=useState("asc");
 const[title,setTitle]=useState(""),[eventDate,setEventDate]=useState(""),[symbol,setSymbol]=useState(""),[customImpact,setCustomImpact]=useState("medium"),[description,setDescription]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await api("/api/v1/events?days=365&sort=date&order=asc&limit=1200"))}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{let rows=[...(data?.events||[])];if(tab==="Company")rows=rows.filter((x:any)=>x.symbol);if(tab==="My Events")rows=rows.filter((x:any)=>x.source==="User event");if(impact!=="all")rows=rows.filter((x:any)=>x.impact===impact);if(category!=="all")rows=rows.filter((x:any)=>x.category===category);const dir=order==="asc"?1:-1;rows.sort((a:any,b:any)=>{let av:any,bv:any;if(sort==="impact"){av=a.impact_score||0;bv=b.impact_score||0}else if(sort==="category"){av=a.category||"";bv=b.category||""}else{av=`${a.event_date||""} ${a.time||""}`;bv=`${b.event_date||""} ${b.time||""}`}return av>bv?dir:av<bv?-dir:0});return rows},[data,tab,impact,category,sort,order]);
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const e of filtered){const d=e.event_date||"Unscheduled";m.set(d,[...(m.get(d)||[]),e])}return [...m.entries()]},[filtered]);
 async function add(e:FormEvent){e.preventDefault();await api("/api/v1/events/custom",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({event_date:eventDate,title,impact:customImpact,category:"Custom",symbol:symbol||null,description:description||null})});setTitle("");setEventDate("");setSymbol("");setDescription("");await load();setTab("My Events")}
 async function remove(id:number){await api(`/api/v1/events/custom/${id}`,{method:"DELETE"});await load()}
 return <section className="tab-panel v3-workspace events-v3"><div className="card suite-hero"><div><span className="eyebrow">Catalyst calendar</span><h2>Events</h2><p className="muted">Official economic schedules, Treasury auctions, market-structure dates, cached company dates and private user events—split into focused views.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div>
 <div className="subtab-bar">{["Calendar","Company","My Events","Sources"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Events unavailable</strong><span>{error}</span></div>}{loading&&!data?<Loading/>:data&&<>
 {tab!=="Sources"&&<><details className="card methodology-dropdown event-filters"><summary><strong>Filters & sorting</strong><span className="muted">{filtered.length} events shown</span><b>▾</b></summary><div className="v2-toolbar"><label>Impact<select className="search" value={impact} onChange={e=>setImpact(e.target.value)}><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Category<select className="search" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All</option>{(data.categories||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><label>Sort<select className="search" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date</option><option value="impact">Impact</option><option value="category">Category</option></select></label><label>Order<select className="search" value={order} onChange={e=>setOrder(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label></div></details>
 <div className="event-v2-list">{groups.map(([d,events])=><details className="card event-v2-day" key={d}><summary><div><span className="eyebrow">{d}</span><strong>{events.length} event{events.length===1?"":"s"}</strong></div><span className="reason-count">{events.filter((x:any)=>x.impact==="high").length} high</span><b>▾</b></summary><div>{events.map((e:any,i:number)=><details className={`event-v2-item impact-${e.impact}`} key={`${e.title}-${i}`}><summary><span className={`data-badge ${e.impact==="high"?"live":e.impact==="medium"?"derived":"cached"}`}>{String(e.impact||"low").toUpperCase()}</span><strong>{e.time?`${e.time} · `:""}{e.title}</strong><span>{e.category}{e.symbol?` · ${e.symbol}`:""}</span><b>▾</b></summary><div><p>{e.description||"Scheduled market event."}</p><div className="event-meta"><span>{e.source}</span>{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Source ↗</a>}{e.custom_event_id&&<button className="text-btn danger" onClick={()=>remove(e.custom_event_id)}>Delete my event</button>}</div></div></details>)}</div></details>)}</div></>}
 {tab==="My Events"&&<form className="card suite-form custom-event-form" onSubmit={add}><span className="eyebrow">Private calendar</span><h3>Add custom catalyst</h3><div className="form-pair"><input className="search" type="date" required value={eventDate} onChange={e=>setEventDate(e.target.value)}/><select className="search" value={customImpact} onChange={e=>setCustomImpact(e.target.value)}><option value="low">Low impact</option><option value="medium">Medium impact</option><option value="high">High impact</option></select></div><input className="search" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Event title"/><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker (optional)"/><input className="search" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Why it matters / notes"/><button className="btn">Add event</button></form>}
 {tab==="Sources"&&<div className="v3-stack"><div className="provider-chip-grid">{(data.providers||[]).map((p:any,i:number)=><span key={`${p.provider}-${i}`}><strong>{p.provider}</strong><b>{p.count}</b><small>{p.status}</small></span>)}</div>{data.errors?.length>0&&<details className="card methodology-dropdown"><summary><strong>Unavailable/degraded sources</strong><span>{data.errors.length}</span><b>▾</b></summary>{data.errors.map((x:string,i:number)=><p className="muted" key={i}>{x}</p>)}</details>}<details className="card methodology-dropdown" open><summary><strong>Calendar methodology</strong><b>▾</b></summary><p>{data.methodology}</p><p className="muted">Rule-based options/index markers are clearly labeled planning markers, not company announcements. Company dates can change and should be reconfirmed near the event.</p></details></div>}
 </>}</section>
}
