"use client";

import {useEffect,useMemo,useState} from "react";

const API="/backend";
const KIND_BY_ID:Record<string,string>={ma100_proximity:"ma100_proximity",ma200_proximity:"ma200_proximity",relative_volume:"relative_volume",earnings_catalyst:"catalyst_days",persistent_flow:"persistent_flow",portfolio_concentration:"portfolio_position_weight",regime_change:"regime_transition"};
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}

export default function FutureAlertTemplates(){
 const[data,setData]=useState<any>(null),[symbol,setSymbol]=useState(""),[portfolios,setPortfolios]=useState<any[]>([]),[portfolioId,setPortfolioId]=useState<number|null>(null),[thresholds,setThresholds]=useState<Record<string,string>>({}),[creating,setCreating]=useState<string|null>(null),[previewing,setPreviewing]=useState<string|null>(null),[previews,setPreviews]=useState<Record<string,any>>({}),[notice,setNotice]=useState("");
 useEffect(()=>{Promise.all([api("/api/v1/future/alert-templates"),api("/api/v1/portfolios")]).then(([t,p])=>{setData(t);const rows=p.portfolios||[];setPortfolios(rows);setPortfolioId(rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null);const init:Record<string,string>={};for(const x of t.templates||[])if(x.threshold!=null)init[x.id]=String(x.threshold);setThresholds(init)}).catch(e=>setNotice(e.message))},[]);
 const templates=useMemo(()=>data?.templates||[],[data]);
 function payload(t:any){const kind=KIND_BY_ID[t.id]||t.kind;const threshold=kind==="regime_transition"?null:Number(thresholds[t.id]??t.threshold);return {kind,symbol:t.scope==="ticker"?symbol.trim().toUpperCase()||null:null,portfolio_id:t.scope==="portfolio"?portfolioId:null,operator:kind==="regime_transition"?"changed":t.operator,threshold,label:t.name,channels:{in_app:true,push:false},cooldown_minutes:360}}
 async function preview(t:any){const body=payload(t);if(t.scope==="ticker"&&!body.symbol){setNotice("Enter a ticker before previewing this template.");return}if(t.scope==="portfolio"&&!body.portfolio_id){setNotice("Select a portfolio before previewing this template.");return}setPreviewing(t.id);setNotice("");try{const d=await api("/api/v1/alerts/v3/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setPreviews(x=>({...x,[t.id]:d}))}catch(e:any){setNotice(`Preview failed: ${e.message}`)}finally{setPreviewing(null)}}
 async function createTemplate(t:any){const body=payload(t);if(t.scope==="ticker"&&!body.symbol){setNotice("Enter a ticker before creating this template.");return}if(t.scope==="portfolio"&&!body.portfolio_id){setNotice("Select a portfolio before creating this template.");return}setCreating(t.id);setNotice("");try{await api("/api/v1/alerts/v3",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice(`${t.name} alert created.`);window.dispatchEvent(new Event("daily-report-alerts-changed"));await preview(t)}catch(e:any){setNotice(`Could not create template: ${e.message}`)}finally{setCreating(null)}}
 function currentText(p:any){if(!p)return"Not previewed";if(p.kind==="regime_transition")return p.current_meta?.transition?`${p.current_meta.transition.from} → ${p.current_meta.transition.to}`:"No stored transition";if(p.current_value==null)return"No current value";return String(Number(p.current_value).toFixed(2))}
 return <div className="card reveal-card future-alert-templates"><div className="section-head"><div><span className="eyebrow">Typed reusable rules</span><h2>Alert templates</h2><p className="muted">Every template now maps to a real evaluator. Preview uses the same backend calculation the scheduler will use after saving.</p></div><div className="future-alert-targets"><label>Ticker<input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="AAOI"/></label><label>Portfolio<select className="search" value={portfolioId??""} onChange={e=>setPortfolioId(Number(e.target.value)||null)}><option value="">No portfolio</option>{portfolios.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div></div><div className="future-template-grid">{templates.map((t:any)=>{const p=previews[t.id],state=p?.would_trigger?"TRIGGERED":"READY";return <article key={t.id}><div className="section-head"><strong>{t.name}</strong><span className={`data-badge ${p?.would_trigger?"live":"derived"}`}>{state}</span></div><span>{KIND_BY_ID[t.id]||t.kind} · {t.scope}</span><p>{t.description}</p>{t.threshold!=null&&<label>Threshold<input className="search" inputMode="decimal" value={thresholds[t.id]??String(t.threshold)} onChange={e=>setThresholds(x=>({...x,[t.id]:e.target.value}))}/><small>{t.unit}</small></label>}<div className="metric-tile-grid"><span><i>Current preview</i><strong>{currentText(p)}</strong></span>{p&&<span><i>Would trigger now</i><strong>{p.would_trigger?"Yes":"No"}</strong></span>}</div><div className="metric-links"><button className="text-btn" disabled={previewing===t.id} onClick={()=>preview(t)}>{previewing===t.id?"Previewing…":"Preview"}</button><button className="btn" disabled={creating===t.id} onClick={()=>createTemplate(t)}>{creating===t.id?"Creating…":"Create alert"}</button></div></article>})}</div>{notice&&<p role="status" className={notice.startsWith("Could not")||notice.startsWith("Preview failed")?"negative":""}>{notice}</p>}<p className="muted">MA proximity uses absolute distance; persistent-flow clusters never claim participant identity; regime transitions fire once per stored transition.</p></div>
}
