"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API="/backend";
async function api(path:string,options:RequestInit={},timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.headers||{})},signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("Request timed out. Retry this section.");throw e}finally{clearTimeout(t)}}
const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:Math.abs(Number(v))>=1e6?`$${(Number(v)/1e6).toFixed(2)}M`:Number(v).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2});
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
function Loading({text="Loading…"}:{text?:string}){return <span className="spinner-line"><i/>{text}</span>}
function ErrorBox({text,onRetry}:{text:string;onRetry:()=>void}){return <div className="suite-error" role="alert"><span>{text}</span><button className="btn" onClick={onRetry}>Retry</button></div>}

export function PortfolioIntelligencePanel({portfolioId}:{portfolioId:number|null}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){if(!portfolioId)return;setLoading(true);setError("");try{setData(await api(`/api/v1/future/portfolio/${portfolioId}/intelligence`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setData(null);if(portfolioId)load()},[portfolioId]);if(!portfolioId)return <div className="card inline-state"><strong>Portfolio intelligence needs a portfolio</strong><span>Create or select a portfolio first.</span></div>;
 return <div className="v3-stack future-panel">{loading&&!data?<Loading text="Building portfolio intelligence…"/>:error&&!data?<ErrorBox text={error} onRetry={load}/>:data&&<><div className="command-stat-grid"><article className="card stat-card"><span>Top position</span><strong>{pct(data.concentration?.top1_weight)}</strong></article><article className="card stat-card"><span>Top 3</span><strong>{pct(data.concentration?.top3_weight)}</strong></article><article className="card stat-card"><span>Effective positions</span><strong>{data.concentration?.effective_positions??"—"}</strong></article><article className="card stat-card"><span>vs SPY</span><strong className={(data.benchmark?.relative_return||0)>=0?"positive":"negative"}>{pct(data.benchmark?.relative_return)}</strong><small>{data.benchmark?.start&&data.benchmark?.end?`${data.benchmark.start} → ${data.benchmark.end}`:"history still accumulating"}</small></article></div>
 <div className="future-exposure-grid">{Object.entries(data.exposures||{}).map(([kind,rows]:any)=><details className="card methodology-dropdown" key={kind} open={kind==="sector"||kind==="theme"}><summary><strong>{kind[0].toUpperCase()+kind.slice(1)} exposure</strong><span>{rows.length}</span><b>▾</b></summary><div className="future-bar-list">{rows.map((x:any)=><div key={x.name}><span>{x.name}</span><b>{pct(x.weight)}</b><i style={{width:`${Math.min(100,Math.max(0,x.weight))}%`}}/></div>)}</div></details>)}</div>
 <details className="card methodology-dropdown" open><summary><strong>Mechanical scenario analysis</strong><span>{data.scenarios?.length||0}</span><b>▾</b></summary><div className="mini-grid">{(data.scenarios||[]).map((x:any)=><span key={x.id}><strong>{x.label}</strong><b className="negative">{money(x.estimated_change)} · {pct(x.estimated_portfolio_percent)}</b><small>{x.assumption}</small></span>)}</div><p className="muted">Scenarios are deterministic shocks, not forecasts or probability estimates.</p></details>
 <details className="card methodology-dropdown"><summary><strong>Methodology & limitations</strong><b>▾</b></summary><p>{data.methodology}</p></details></>}</div>
}

export function OpportunityChangePanel({symbol}:{symbol:string}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await api(`/api/v1/future/opportunities/${encodeURIComponent(symbol)}/why-changed`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setData(null);load()},[symbol]);
 if(loading&&!data)return <Loading text="Explaining score change…"/>;if(error&&!data)return <ErrorBox text={error} onRetry={load}/>;if(!data)return null;
 return <details className="methodology-dropdown future-change-panel"><summary><div><strong>Why did this score change?</strong><span className={(data.score_delta||0)>=0?"positive":"negative"}>{data.score_delta==null?"first snapshot":`${data.score_delta>=0?"+":""}${data.score_delta} buy-score pts`}</span></div><b>▾</b></summary><div className="component-grid-v3">{(data.component_deltas||[]).map((x:any)=><span className="metric-explainer" key={x.component}><i>{x.component}</i><strong>{x.current??"—"}</strong><small>{x.delta==null?"no prior value":`${x.delta>=0?"+":""}${x.delta} vs ${x.previous}`}</small></span>)}</div>{(data.new_flags?.length||data.removed_flags?.length)?<div className="suite-two"><div><strong>New flags</strong><div className="chip-row">{(data.new_flags||[]).map((x:string)=><span key={x}>{x}</span>)}</div></div><div><strong>Removed flags</strong><div className="chip-row">{(data.removed_flags||[]).map((x:string)=><span key={x}>{x}</span>)}</div></div></div>:<p className="muted">No threshold flags changed between the two latest stored snapshots.</p>}<p className="muted">Current market-source age: {data.source_age?.market_minutes==null?"—":`${data.source_age.market_minutes} min`}. {data.note}</p></details>
}

export function FlowClustersPanel(){
 const[data,setData]=useState<any>(null),[days,setDays]=useState(7),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{setData(await api(`/api/v1/future/flow/clusters?days=${days}&limit=100`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[days]);
 const clusters=data?.clusters||[];return <section className="future-panel"><div className="card section-head"><div><span className="eyebrow">Repeated activity signatures</span><h3>Flow clusters</h3><p className="muted">Clusters group repeated contract signatures. They do not identify traders or prove opening/closing intent.</p></div><label>Window<select className="search" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>1 day</option><option value={3}>3 days</option><option value={7}>7 days</option><option value={14}>14 days</option><option value={30}>30 days</option></select></label></div>{loading&&!data?<Loading text="Clustering flow…"/>:error&&!data?<ErrorBox text={error} onRetry={load}/>:<div className="future-cluster-grid">{clusters.length?clusters.map((x:any,i:number)=><details className="card methodology-dropdown" key={`${x.symbol}-${x.side}-${x.expiration}-${x.strike}-${i}`}><summary><div><strong>{x.symbol} · {String(x.side).toUpperCase()} {x.strike!=null?`$${x.strike}`:""}</strong><span>{x.observations} observations · {money(x.premium)}</span></div><b>▾</b></summary><div className="metric-tile-grid"><span><i>Expiration</i><strong>{x.expiration}</strong></span><span><i>Direction label</i><strong>{x.direction}</strong></span><span><i>Contracts/volume</i><strong>{x.contracts}</strong></span><span><i>Confidence</i><strong>{x.confidence}%</strong></span><span><i>First seen</i><strong>{new Date(x.first_seen).toLocaleString()}</strong></span><span><i>Last seen</i><strong>{new Date(x.last_seen).toLocaleString()}</strong></span></div><p className="muted">{x.inference}</p></details>):<div className="card inline-state"><strong>No repeated clusters in this window</strong><span>Stored flow observations did not repeat enough to form a cluster.</span></div>}</div>}</section>
}

export function ImpactMapPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{setData(await api("/api/v1/future/impact-map"))}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 return <section className="future-panel"><div className="card section-head"><div><span className="eyebrow">Exposure-aware intelligence</span><h3>News & catalyst impact map</h3></div><button className="btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh map"}</button></div>{error&&!data?<ErrorBox text={error} onRetry={load}/>:loading&&!data?<Loading text="Mapping exposure…"/>:<div className="future-impact-list">{(data?.items||[]).length?(data.items||[]).map((x:any,i:number)=><details className="card methodology-dropdown" key={`${x.kind}-${x.title}-${i}`}><summary><div><span className={`data-badge ${x.causal_confidence==="explicit_mapping"?"live":"derived"}`}>{String(x.kind).toUpperCase()}</span><strong>{x.title}</strong></div><span>{pct(x.estimated_portfolio_exposure_percent)} portfolio exposure</span><b>▾</b></summary><div className="chip-row">{(x.symbols||[]).map((s:string)=><button key={s} className="chip" onClick={()=>window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:{tab:"Research",symbol:s}}))}>{s}</button>)}</div>{(x.rationale||[]).map((r:any)=><p key={r.symbol}><strong>{r.symbol}</strong> · {r.matches.join(" · ")} · {pct(r.portfolio_exposure_percent)} exposure</p>)}<p className="muted">Mapping confidence: {x.causal_confidence==="explicit_mapping"?"explicit ticker mapping":"association only; text match is not proof of causality"}.</p>{x.url&&<a className="source-link" href={x.url} target="_blank" rel="noreferrer">Open source ↗</a>}</details>):<div className="card inline-state"><strong>No mapped impact items</strong><span>No recent report news/custom catalysts matched the current watchlist or portfolio.</span></div>}</div>}{data&&<p className="muted small-note">{data.methodology}</p>}</section>
}

export function RegimeConfidencePanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{setData(await api("/api/v1/future/regime/confidence"))}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 return <section className="future-panel">{loading&&!data?<Loading text="Calculating regime confidence…"/>:error&&!data?<ErrorBox text={error} onRetry={load}/>:data&&<><div className="command-stat-grid"><article className="card stat-card"><span>Regime</span><strong>{data.regime}</strong></article><article className="card stat-card"><span>Regime score</span><strong>{data.score} pts</strong></article><article className="card stat-card"><span>Confidence</span><strong>{data.confidence}%</strong></article><article className="card stat-card"><span>Evidence coverage</span><strong>{data.evidence_completeness}%</strong></article></div><details className="card methodology-dropdown" open><summary><strong>Component evidence</strong><span>{data.evidence?.length||0}</span><b>▾</b></summary><div className="mini-grid">{(data.evidence||[]).map((x:any)=><span key={x.symbol}><strong>{x.symbol} · {x.label}</strong><b className={(x.return||0)>=0?"positive":"negative"}>{pct(x.return)}</b><small>{x.as_of||"stored"}</small></span>)}</div></details><details className="card methodology-dropdown"><summary><strong>Regime transition history</strong><span>{data.transition_history?.length||0}</span><b>▾</b></summary><div className="history-row-list">{(data.transition_history||[]).map((x:any)=><span key={`${x.as_of}-${x.regime}`}><time>{x.as_of}</time><b>{x.regime}</b><small>{x.score} pts · {x.confidence}% confidence</small></span>)}</div></details><p className="muted">{data.methodology}</p></>}</section>
}

const DEFAULT_CARDS=["market_dashboard","sentiment","themes"];
export function DashboardLayoutsPanel(){
 const[data,setData]=useState<any>(null),[name,setName]=useState("Default"),[cards,setCards]=useState<string[]>(DEFAULT_CARDS),[hidden,setHidden]=useState<string[]>([]),[columns,setColumns]=useState(2),[density,setDensity]=useState("comfortable"),[saving,setSaving]=useState(false),[error,setError]=useState("");async function load(){try{const d=await api("/api/v1/future/dashboard-layouts");setData(d);const active=(d.layouts||[]).find((x:any)=>x.name===d.active)||d.layouts?.[0];if(active){setName(active.name);setCards(active.cards?.filter((x:string)=>DEFAULT_CARDS.includes(x))||DEFAULT_CARDS);setHidden(active.hidden||[]);setColumns(active.columns||2);setDensity(active.density||"comfortable")}}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);
 function move(card:string,dir:number){setCards(x=>{const a=[...x],i=a.indexOf(card),j=i+dir;if(i<0||j<0||j>=a.length)return a;[a[i],a[j]]=[a[j],a[i]];return a})}
 async function save(){setSaving(true);setError("");try{await api("/api/v1/future/dashboard-layouts",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,cards,hidden,density,columns,make_active:true})});await load();window.dispatchEvent(new Event("daily-report-dashboard-layout-changed"))}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function activate(layout:string){await api("/api/v1/future/dashboard-layouts/active",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:layout})});await load();window.dispatchEvent(new Event("daily-report-dashboard-layout-changed"))}
 return <div className="card reveal-card future-layout-editor"><div className="section-head"><div><span className="eyebrow">Saved dashboard profiles</span><h2>Dashboard layouts</h2><p className="muted">This first release controls the top Report dashboard cards. The same profile model is ready to expand to every card without changing the stored format.</p></div></div>{data?.layouts?.length>0&&<div className="chip-row">{data.layouts.map((x:any)=><button className={`chip ${data.active===x.name?"active":""}`} key={x.name} onClick={()=>activate(x.name)}>{x.name}{data.active===x.name?" · active":""}</button>)}</div>}<div className="future-layout-form"><label>Layout name<input className="search" value={name} onChange={e=>setName(e.target.value)}/></label><label>Columns<select className="search" value={columns} onChange={e=>setColumns(Number(e.target.value))}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option></select></label><label>Density<select className="search" value={density} onChange={e=>setDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label></div><div className="future-layout-card-list">{cards.map((c,i)=><div key={c}><label><input type="checkbox" checked={!hidden.includes(c)} onChange={e=>setHidden(x=>e.target.checked?x.filter(v=>v!==c):[...x,c])}/><strong>{c.replaceAll("_"," ")}</strong></label><div><button type="button" className="text-btn" disabled={i===0} onClick={()=>move(c,-1)}>↑</button><button type="button" className="text-btn" disabled={i===cards.length-1} onClick={()=>move(c,1)}>↓</button></div></div>)}</div><button className="btn" onClick={save} disabled={saving||!name.trim()}>{saving?"Saving…":"Save & apply layout"}</button>{error&&<p className="negative">{error}</p>}</div>
}

export function DashboardLayoutRuntime(){
 useEffect(()=>{let live=true;async function apply(){try{const d=await api("/api/v1/future/dashboard-layouts");if(!live)return;const layout=(d.layouts||[]).find((x:any)=>x.name===d.active)||d.layouts?.[0];if(!layout)return;const zone=document.querySelector<HTMLElement>(".dashboard-layout-zone");if(!zone)return;zone.style.setProperty("--dashboard-columns",String(layout.columns||2));zone.dataset.density=layout.density||"comfortable";const order=new Map((layout.cards||[]).map((x:string,i:number)=>[x,i]));const hidden=new Set(layout.hidden||[]);zone.querySelectorAll<HTMLElement>("[data-dashboard-card]").forEach((el)=>{const key=el.dataset.dashboardCard||"";el.style.order=String(order.has(key)?order.get(key):999);el.style.display=hidden.has(key)?"none":""})}catch{}}
 apply();const h=()=>apply();window.addEventListener("daily-report-dashboard-layout-changed",h);return()=>{live=false;window.removeEventListener("daily-report-dashboard-layout-changed",h)}},[]);return null
}

export function ReportComparePanel(){
 const[history,setHistory]=useState<any[]>([]),[left,setLeft]=useState<number|null>(null),[right,setRight]=useState<number|null>(null),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function loadHistory(){try{const d=await api("/api/v1/future/reports/history?limit=50");const r=d.reports||[];setHistory(r);if(r.length>=2){setRight(r[0].id);setLeft(r[1].id)}}catch(e:any){setError(e.message)}}useEffect(()=>{loadHistory()},[]);async function compare(){if(!left||!right)return;setLoading(true);setError("");try{setData(await api(`/api/v1/future/reports/compare?left_id=${left}&right_id=${right}`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <details className="card methodology-dropdown future-report-compare"><summary><div><span className="eyebrow">Stored snapshot history</span><strong>Compare & export reports</strong></div><span>{history.length} snapshots</span><b>▾</b></summary>{history.length<2?<p className="muted">Save at least two Daily Report snapshots to compare them.</p>:<><div className="future-compare-controls"><label>Earlier<select className="search" value={left??""} onChange={e=>setLeft(Number(e.target.value))}>{history.map(x=><option key={x.id} value={x.id}>#{x.id} · {x.report_date} · {new Date(x.created_at).toLocaleString()}</option>)}</select></label><label>Later<select className="search" value={right??""} onChange={e=>setRight(Number(e.target.value))}>{history.map(x=><option key={x.id} value={x.id}>#{x.id} · {x.report_date} · {new Date(x.created_at).toLocaleString()}</option>)}</select></label><button className="btn" onClick={compare} disabled={loading}>{loading?"Comparing…":"Compare"}</button></div>{error&&<ErrorBox text={error} onRetry={compare}/>} {data&&<><div className="metric-tile-grid"><span><i>Left verified</i><strong>{data.verification?.left_verified??"—"}</strong></span><span><i>Right verified</i><strong>{data.verification?.right_verified??"—"}</strong></span><span><i>News added</i><strong>{data.news_added?.length||0}</strong></span><span><i>News removed</i><strong>{data.news_removed?.length||0}</strong></span></div><div className="future-compare-table"><div><strong>Ticker</strong><strong>Earlier</strong><strong>Later</strong><strong>Change</strong></div>{(data.symbol_changes||[]).map((x:any)=><div key={x.symbol}><strong>{x.symbol}</strong><span>{money(x.left_price)}</span><span>{money(x.right_price)}</span><span className={(x.price_change_percent||0)>=0?"positive":"negative"}>{pct(x.price_change_percent)}</span></div>)}</div><p className="muted">{data.methodology}</p></>}</>}
 {right&&<div className="metric-links"><a className="text-btn" href={`${API}/api/v1/future/reports/${right}/export.csv`}>Export CSV</a><a className="text-btn" href={`${API}/api/v1/future/reports/${right}/export.json`} target="_blank" rel="noreferrer">Export JSON</a><button className="text-btn" onClick={()=>window.print()}>Print / Save PDF</button></div>}</details>
}

export function AlertTemplatesPanel(){
 const[data,setData]=useState<any>(null),[symbol,setSymbol]=useState(""),[creating,setCreating]=useState<string|null>(null),[notice,setNotice]=useState("");useEffect(()=>{api("/api/v1/future/alert-templates").then(setData).catch(()=>{})},[]);
 async function createTemplate(t:any){if(t.scope==="ticker"&&!symbol.trim()){setNotice("Enter a ticker before creating this ticker-scoped template.");return}setCreating(t.id);setNotice("");try{const symbols=t.scope==="ticker"?[symbol.trim().toUpperCase()]:["SPY"];await api("/api/v1/alerts/v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols,kind:t.kind,operator:t.operator,threshold:t.threshold,label:t.name,channels:{in_app:true,push:false},cooldown_minutes:360})});setNotice(`${t.name} alert created${t.scope==="ticker"?` for ${symbols[0]}`:""}.`);window.dispatchEvent(new Event("daily-report-alerts-changed"))}catch(e:any){setNotice(`Could not create template: ${e.message}`)}finally{setCreating(null)}}
 return <div className="card reveal-card future-alert-templates"><div className="section-head"><div><span className="eyebrow">Reusable rules</span><h2>Alert templates</h2></div><label>Ticker<input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="AAOI"/></label></div><div className="future-template-grid">{(data?.templates||[]).map((t:any)=><article key={t.id}><strong>{t.name}</strong><span>{t.kind} {t.operator} {t.threshold??"state change"} {t.unit}</span><p>{t.description}</p><button className="btn" disabled={creating===t.id} onClick={()=>createTemplate(t)}>{creating===t.id?"Creating…":"Create from template"}</button></article>)}</div>{notice&&<p role="status" className={notice.startsWith("Could not")?"negative":"positive"}>{notice}</p>}<p className="muted">{data?.methodology}</p></div>
}
