"use client";

import {useEffect,useMemo,useState} from "react";

const API="/backend";
const KIND_BY_ID:Record<string,string>={ma100_proximity:"ma100_proximity",ma200_proximity:"ma200_proximity",relative_volume:"relative_volume",earnings_catalyst:"catalyst_days",persistent_flow:"persistent_flow",portfolio_concentration:"portfolio_position_weight",regime_change:"regime_transition",williams_entry:"williams_oversold_entry",williams_recovery:"williams_oversold_recovery",ma100_approach:"ma100_approach_from_above",williams_ma100:"williams_ma100_trigger",opportunity_invalidated:"opportunity_invalidated",opportunity_triggered:"opportunity_convergence",candidate_context_changed:"candidate_context_changed",candidate_flow_changed:"candidate_flow_changed",portfolio_concentration_breach:"portfolio_concentration_breach"};
const SEMANTIC_KINDS=new Set(["candidate_context_changed","candidate_flow_changed","portfolio_concentration_breach"]);
const TRANSITION_KINDS=new Set(["regime_transition","williams_oversold_entry","williams_oversold_recovery","ma100_approach_from_above","williams_ma100_trigger","opportunity_invalidated","opportunity_convergence",...SEMANTIC_KINDS]);
const V4_TEMPLATES=[
 {id:"williams_entry",name:"Williams enters oversold",kind:"williams_oversold_entry",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert once when Williams %R crosses into <= -80 after prior state is established."},
 {id:"williams_recovery",name:"Williams recovers from oversold",kind:"williams_oversold_recovery",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert once when Williams %R moves back above -80 after being oversold."},
 {id:"ma100_approach",name:"100MA approach from above",kind:"ma100_approach_from_above",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert when price moves from more than 5% above the 100MA into the 0-5% approach zone. A move up from below does not count."},
 {id:"williams_ma100",name:"Williams + 100MA trigger",kind:"williams_ma100_trigger",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert once when Williams <= -80 and price is simultaneously 0-5% above the 100MA."},
 {id:"opportunity_triggered",name:"Opportunity convergence triggered",kind:"opportunity_convergence",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert when the convergence model enters Triggered with its data-readiness requirements satisfied."},
 {id:"opportunity_invalidated",name:"Opportunity invalidated",kind:"opportunity_invalidated",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert when the convergence model newly enters Invalidated."},
];
const V4_SEMANTIC_TEMPLATES=[
 {id:"candidate_context_changed",name:"Candidate context changed",kind:"candidate_context_changed",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert when fresh company news, catalyst or filing context changes to a materially different semantic state. Stale/missing-only transitions are ignored."},
 {id:"candidate_flow_changed",name:"Flow confirmation changed",kind:"candidate_flow_changed",operator:"changed",threshold:null,unit:"state",scope:"ticker",description:"Alert when cached candidate flow changes between confirmation, contradiction and mixed states after baseline state is established."},
 {id:"portfolio_concentration_breach",name:"Portfolio concentration breach",kind:"portfolio_concentration_breach",operator:"changed",threshold:20,unit:"% portfolio",scope:"portfolio",description:"Alert once when the largest position crosses from below to at or above the selected portfolio-weight threshold."},
];
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}

export default function FutureAlertTemplates(){
 const[data,setData]=useState<any>(null),[symbol,setSymbol]=useState(""),[portfolios,setPortfolios]=useState<any[]>([]),[portfolioId,setPortfolioId]=useState<number|null>(null),[thresholds,setThresholds]=useState<Record<string,string>>({}),[creating,setCreating]=useState<string|null>(null),[previewing,setPreviewing]=useState<string|null>(null),[previews,setPreviews]=useState<Record<string,any>>({}),[notice,setNotice]=useState("");
 const[formulas,setFormulas]=useState<any[]>([]),[formulaAlerts,setFormulaAlerts]=useState<any[]>([]),[formulaId,setFormulaId]=useState<number|null>(null),[formulaMode,setFormulaMode]=useState<"score"|"rank">("score"),[formulaThreshold,setFormulaThreshold]=useState("80"),[formulaBusy,setFormulaBusy]=useState(false);
 async function loadFormulaAlerts(){try{const d=await api("/api/v1/alerts/v4/formulas");setFormulaAlerts(d.alerts||[])}catch(e:any){setNotice(`Could not load formula alerts: ${e.message}`)}}
 useEffect(()=>{Promise.all([api("/api/v1/future/alert-templates"),api("/api/v1/portfolios"),api("/api/v1/opportunities/formulas"),api("/api/v1/alerts/v4/formulas")]).then(([t,p,f,a])=>{setData(t);const rows=p.portfolios||[];setPortfolios(rows);setPortfolioId(rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null);const saved=f.saved||[];setFormulas(saved);setFormulaId(saved[0]?.id||null);setFormulaAlerts(a.alerts||[]);const init:Record<string,string>={};for(const x of [...(t.templates||[]),...V4_TEMPLATES,...V4_SEMANTIC_TEMPLATES])if(x.threshold!=null)init[x.id]=String(x.threshold);setThresholds(init)}).catch(e=>setNotice(e.message))},[]);
 const templates=useMemo(()=>[...(data?.templates||[]),...V4_TEMPLATES,...V4_SEMANTIC_TEMPLATES],[data]);
 function payload(t:any){const kind=KIND_BY_ID[t.id]||t.kind;const transition=TRANSITION_KINDS.has(kind);const threshold=kind==="portfolio_concentration_breach"?Number(thresholds[t.id]??t.threshold):transition?null:Number(thresholds[t.id]??t.threshold);return {kind,symbol:t.scope==="ticker"?symbol.trim().toUpperCase()||null:null,portfolio_id:t.scope==="portfolio"?portfolioId:null,operator:transition?"changed":t.operator,threshold,label:t.name,channels:{in_app:true,push:false},cooldown_minutes:360}}
 async function preview(t:any){const body=payload(t);if(t.scope==="ticker"&&!body.symbol){setNotice("Enter a ticker before previewing this template.");return}if(t.scope==="portfolio"&&!body.portfolio_id){setNotice("Select a portfolio before previewing this template.");return}setPreviewing(t.id);setNotice("");try{const path=SEMANTIC_KINDS.has(body.kind)?"/api/v1/alerts/v4/preview":"/api/v1/alerts/v3/preview";const d=await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setPreviews(x=>({...x,[t.id]:d}))}catch(e:any){setNotice(`Preview failed: ${e.message}`)}finally{setPreviewing(null)}}
 async function createTemplate(t:any){const body=payload(t);if(t.scope==="ticker"&&!body.symbol){setNotice("Enter a ticker before creating this template.");return}if(t.scope==="portfolio"&&!body.portfolio_id){setNotice("Select a portfolio before creating this template.");return}setCreating(t.id);setNotice("");try{const path=SEMANTIC_KINDS.has(body.kind)?"/api/v1/alerts/v4":"/api/v1/alerts/v3";await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setNotice(`${t.name} alert created.`);window.dispatchEvent(new Event("daily-report-alerts-changed"));await preview(t)}catch(e:any){setNotice(`Could not create template: ${e.message}`)}finally{setCreating(null)}}
 function currentText(p:any){if(!p)return"Not previewed";if(p.transition_native){const s=p.current_meta?.state;return s?String(s).replaceAll("_"," "):"State unavailable"}if(p.kind==="regime_transition")return p.current_meta?.transition?`${p.current_meta.transition.from} → ${p.current_meta.transition.to}`:"No stored transition";if(p.current_value==null)return"No current value";return String(Number(p.current_value).toFixed(2))}
 async function createFormulaAlert(){const ticker=symbol.trim().toUpperCase();if(!formulaId){setNotice("Save an Opportunity formula before creating a formula alert.");return}if(!ticker){setNotice("Enter a ticker before creating a formula alert.");return}const threshold=Number(formulaThreshold);if(!Number.isFinite(threshold)||threshold<=0){setNotice("Enter a valid formula alert threshold.");return}const f=formulas.find(x=>x.id===formulaId);setFormulaBusy(true);setNotice("");try{await api("/api/v1/alerts/v4/formulas",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({formula_id:formulaId,symbol:ticker,mode:formulaMode,threshold,label:formulaMode==="score"?`${ticker} ${f?.name||"formula"} score threshold`:`${ticker} ${f?.name||"formula"} top-${Math.round(threshold)} entry`,channels:{in_app:true,push:false},cooldown_minutes:360})});setNotice("Saved-formula alert created. Its first scheduler evaluation establishes baseline state.");await loadFormulaAlerts();window.dispatchEvent(new Event("daily-report-alerts-changed"))}catch(e:any){setNotice(`Could not create formula alert: ${e.message}`)}finally{setFormulaBusy(false)}}
 async function removeFormulaAlert(id:number){setFormulaBusy(true);setNotice("");try{await api(`/api/v1/alerts/v4/formulas/${id}`,{method:"DELETE"});await loadFormulaAlerts();setNotice("Saved-formula alert removed.");window.dispatchEvent(new Event("daily-report-alerts-changed"))}catch(e:any){setNotice(`Could not remove formula alert: ${e.message}`)}finally{setFormulaBusy(false)}}
 return <div className="card reveal-card future-alert-templates"><div className="section-head"><div><span className="eyebrow">Typed reusable rules</span><h2>Alert templates</h2><p className="muted">Templates map to the same cache-only evaluator used by the scheduler. Transition alerts fire on state entry, not continuously while a condition remains true.</p></div><div className="future-alert-targets"><label>Ticker<input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="AAOI"/></label><label>Portfolio<select className="search" value={portfolioId??""} onChange={e=>setPortfolioId(Number(e.target.value)||null)}><option value="">No portfolio</option>{portfolios.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label></div></div><div className="future-template-grid">{templates.map((t:any)=>{const p=previews[t.id],transition=TRANSITION_KINDS.has(KIND_BY_ID[t.id]||t.kind),state=p?.would_trigger?"TRIGGERED":transition?"STATEFUL":"READY";return <article key={t.id}><div className="section-head"><strong>{t.name}</strong><span className={`data-badge ${p?.would_trigger?"live":"derived"}`}>{state}</span></div><span>{KIND_BY_ID[t.id]||t.kind} · {t.scope}</span><p>{t.description}</p>{t.threshold!=null&&(!transition||(KIND_BY_ID[t.id]||t.kind)==="portfolio_concentration_breach")&&<label>Threshold<input className="search" inputMode="decimal" value={thresholds[t.id]??String(t.threshold)} onChange={e=>setThresholds(x=>({...x,[t.id]:e.target.value}))}/><small>{t.unit}</small></label>}<div className="metric-tile-grid"><span><i>Current preview</i><strong>{currentText(p)}</strong></span>{p&&!transition&&<span><i>Would trigger now</i><strong>{p.would_trigger?"Yes":"No"}</strong></span>}{p&&transition&&<span><i>Delivery rule</i><strong>Next qualifying transition</strong></span>}</div><div className="metric-links"><button className="text-btn" disabled={previewing===t.id} onClick={()=>preview(t)}>{previewing===t.id?"Previewing…":"Preview state"}</button><button className="btn" disabled={creating===t.id} onClick={()=>createTemplate(t)}>{creating===t.id?"Creating…":"Create alert"}</button></div></article>})}</div>
 <div className="section-head"><div><span className="eyebrow">Saved Opportunity formulas</span><h2>Formula alerts</h2><p className="muted">Each active saved formula is scanned once per 15-minute evaluator cycle regardless of how many tickers use it. Asset scores and ranks come from the full cached eligible universe.</p></div></div>
 {formulas.length?<><div className="future-alert-targets"><label>Formula<select className="search" value={formulaId??""} onChange={e=>setFormulaId(Number(e.target.value)||null)}>{formulas.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Trigger<select className="search" value={formulaMode} onChange={e=>{const mode=e.target.value as "score"|"rank";setFormulaMode(mode);setFormulaThreshold(mode==="score"?"80":"20")}}><option value="score">Score crosses above</option><option value="rank">Rank enters top N</option></select></label><label>{formulaMode==="score"?"Score threshold":"Top N"}<input className="search" inputMode="decimal" value={formulaThreshold} onChange={e=>setFormulaThreshold(e.target.value)}/></label><button className="btn" disabled={formulaBusy} onClick={createFormulaAlert}>{formulaBusy?"Saving…":"Create formula alert"}</button></div><div className="future-template-grid">{formulaAlerts.map((a:any)=><article key={a.id}><div className="section-head"><strong>{a.symbol} · {a.formula_name||`Formula ${a.formula_id}`}</strong><span className="data-badge derived">{String(a.current_state||"unavailable").replaceAll("_"," ")}</span></div><p>{a.mode==="score"?`Alert when score crosses above ${a.threshold}.`:`Alert when rank enters top ${Math.round(a.threshold)}.`}</p><div className="metric-tile-grid"><span><i>Current score</i><strong>{a.current_score==null?"—":Number(a.current_score).toFixed(1)}</strong></span><span><i>Current rank</i><strong>{a.current_rank==null?"—":`#${a.current_rank}`}</strong></span></div><div className="metric-links"><button className="text-btn" disabled={formulaBusy} onClick={()=>removeFormulaAlert(a.id)}>Remove</button></div></article>)}</div></>:<p className="muted">No saved custom Opportunity formulas yet. Save a formula in Opportunities first; the protected default formula remains available through the standard technical/convergence templates.</p>}
 {notice&&<p role="status" className={notice.startsWith("Could not")||notice.startsWith("Preview failed")?"negative":""}>{notice}</p>}<p className="muted">MA proximity uses absolute distance; approach-from-above requires prior extended-above state; context and flow changes ignore stale/missing-only states; first observations initialize transition state without notifying.</p></div>
}