"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

const API="/backend";
type Market=Record<string,{symbol?:string;price?:number|null;change_percent?:number|null;seven_day_percent?:number|null;thirty_day_percent?:number|null;relative_volume?:number|null;as_of?:string|null}>;
type Rotation={leaders?:any[];laggards?:any[];sectors?:any[]}|null;

async function api(path:string,options:RequestInit={}){
 const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",...options,headers:{...(options.headers||{})}});
 const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d;
}
const money=(v:number|null|undefined)=>v==null?"—":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:Math.abs(v)>=1e6?`$${(v/1e6).toFixed(2)}M`:Math.abs(v)>=1e3?`$${(v/1e3).toFixed(1)}K`:`$${v.toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const scoreClass=(v:number)=>v>=60?"positive":v<=40?"negative":"";
function Spinner({label="Loading"}:{label?:string}){return <span className="suite-spinner" role="status"><i/>{label}</span>}
function Skeleton({rows=4}:{rows?:number}){return <div className="suite-skeleton" aria-label="Loading">{Array.from({length:rows}).map((_,i)=><span key={i}/>)}</div>}
function Empty({children}:{children:React.ReactNode}){return <div className="suite-empty">{children}</div>}
function ErrorBox({error,onRetry}:{error:string;onRetry?:()=>void}){return <div className="suite-error"><strong>Unable to load</strong><span>{error}</span>{onRetry&&<button className="btn" onClick={onRetry}>Retry</button>}</div>}

export function ContextBar({market,rotation}:{market:Market;rotation:Rotation}){
 const items=["SPY","QQQ","VIX"].map(s=>market[s]).filter(Boolean),leader=rotation?.leaders?.[0];
 return <div className="context-bar" aria-label="Market context">{items.map((m:any)=><span key={m.symbol}><b>{m.symbol}</b> {m.symbol==="VIX"?(m.price?.toFixed?.(2)||"—"):money(m.price)} <i className={(m.change_percent||0)>=0?"positive":"negative"}>{pct(m.change_percent)}</i></span>)}{leader&&<span><b>Leader</b> {leader.symbol} <i className={(leader.rotation_score||0)>=0?"positive":"negative"}>{leader.rotation_score>=0?"+":""}{leader.rotation_score?.toFixed?.(2)}</i></span>}<span className="context-updated">Shared cached data</span></div>
}

export function PortfolioPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[symbol,setSymbol]=useState(""),[shares,setShares]=useState(""),[cost,setCost]=useState("");
 const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/portfolio"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 async function save(e:FormEvent){e.preventDefault();try{await api("/api/v1/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol,shares:Number(shares||0),average_cost:Number(cost||0)})});setSymbol("");setShares("");setCost("");load()}catch(e:any){setError(e.message)}}
 async function remove(s:string){try{await api(`/api/v1/portfolio/${encodeURIComponent(s)}`,{method:"DELETE"});load()}catch(e:any){setError(e.message)}}
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Position-aware intelligence</span><h2>Portfolio</h2><p className="muted">Holdings are private to this account; market data is shared by symbol.</p></div>{loading&&<Spinner label="Updating"/>}</div>{error&&<ErrorBox error={error} onRetry={load}/>} {loading&&!data?<Skeleton rows={6}/>:data&&<><div className="suite-stat-grid"><article className="card stat-card"><span>Market value</span><strong>{money(data.market_value)}</strong></article><article className="card stat-card"><span>Cost basis</span><strong>{money(data.cost_basis)}</strong></article><article className="card stat-card"><span>Unrealized P/L</span><strong className={(data.unrealized_pl||0)>=0?"positive":"negative"}>{money(data.unrealized_pl)}</strong></article><article className="card stat-card"><span>Concentration</span><strong>{data.concentration_risk}</strong></article></div><div className="card reveal-card suite-grid-card"><h2>Positions</h2><div className="suite-table"><div className="suite-row suite-head"><span>Ticker</span><span>Value</span><span>P/L</span><span>Sector</span><span>Buy</span><span>Sell</span><span/></div>{data.holdings?.map((h:any)=><div className="suite-row" key={h.symbol}><strong>{h.symbol}<small>{h.shares} sh · {money(h.average_cost)} cost</small></strong><span>{money(h.market_value)}</span><span className={(h.unrealized_pl||0)>=0?"positive":"negative"}>{money(h.unrealized_pl)}<small>{pct(h.unrealized_percent)}</small></span><span>{h.sector}</span><strong className={scoreClass(h.buy_score||50)}>{h.buy_score??"—"}</strong><strong>{h.sell_score??"—"}</strong><button className="text-btn" onClick={()=>remove(h.symbol)}>Remove</button></div>)}</div></div><div className="suite-two"><div className="card reveal-card"><h2>Sector exposure</h2>{data.sector_exposure?.length?data.sector_exposure.map((x:any)=><div className="exposure-row" key={x.sector}><span>{x.sector}</span><div><i style={{width:`${Math.min(100,x.weight)}%`}}/></div><strong>{x.weight.toFixed(1)}%</strong></div>):<Empty>Add holdings to calculate exposure.</Empty>}</div><form className="card reveal-card suite-form" onSubmit={save}><h2>Add / update holding</h2><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} placeholder="Ticker" required/><input className="search" inputMode="decimal" value={shares} onChange={e=>setShares(e.target.value)} placeholder="Shares"/><input className="search" inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)} placeholder="Average cost"/><button className="btn">Save holding</button></form></div></>}</section>
}

export function OpportunitiesPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[mode,setMode]=useState<"buy"|"sell">("buy");
 const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/opportunities?limit=100"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>[...(data?.opportunities||[])].sort((a:any,b:any)=>mode==="buy"?b.buy_score-a.buy_score:b.sell_score-a.sell_score),[data,mode]);
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Auditable screener</span><h2>Opportunities</h2><p className="muted">Visible technical, valuation, sector, flow, momentum and risk components.</p></div><div className="view-toggle"><button className={`toggle ${mode==="buy"?"active":""}`} onClick={()=>setMode("buy")}>Buy setup</button><button className={`toggle ${mode==="sell"?"active":""}`} onClick={()=>setMode("sell")}>Sell / trim</button><button className="btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div></div>{error&&<ErrorBox error={error} onRetry={load}/>} {loading&&!data?<Skeleton rows={8}/>:<div className="opportunity-grid">{rows.map((r:any)=><details className="card reveal-card opportunity-card" key={r.symbol}><summary><div><strong>{r.symbol}</strong><span>{mode==="buy"?"Buy":"Sell"} setup</span></div><strong className={scoreClass(mode==="buy"?r.buy_score:100-r.sell_score)}>{mode==="buy"?r.buy_score:r.sell_score}</strong></summary><div className="component-grid">{Object.entries(r.components||{}).map(([k,v]:any)=><div key={k}><span>{k}</span><div><i style={{width:`${v}%`}}/></div><strong>{v}</strong></div>)}</div></details>)}</div>}</section>
}

export function EventsPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/events?days=90"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const grouped=useMemo(()=>{const m=new Map<string,any[]>();for(const e of data?.events||[]){const d=String(e.event_date||e.date||"Unscheduled").slice(0,10);m.set(d,[...(m.get(d)||[]),e])}return [...m.entries()]},[data]);
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Forward catalyst map</span><h2>Events</h2></div><button className="btn" disabled={loading} onClick={load}>{loading?"Loading…":"Refresh"}</button></div>{error&&<ErrorBox error={error} onRetry={load}/>} {loading&&!data?<Skeleton rows={7}/>:<div className="event-timeline">{grouped.length?grouped.map(([d,events])=><div className="card reveal-card event-day" key={d}><strong>{d}</strong><div>{events.map((e:any,i:number)=><details key={`${d}-${i}`}><summary><span className={`data-badge ${e.kind==="earnings"?"live":"cached"}`}>{e.kind||"macro"}</span><b>{e.title||e.event||e.name||"Scheduled event"}</b>{e.symbol&&<span>{e.symbol}</span>}</summary><p className="muted">{e.description||e.country||e.category||"Potential market catalyst."}</p></details>)}</div></div>):<Empty>No scheduled events returned.</Empty>}</div>}</section>
}

export function RegimePanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/regime"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Cross-asset context</span><h2>Market Regime</h2></div><button className="btn" onClick={load} disabled={loading}>{loading?"Updating…":"Refresh"}</button></div>{error&&<ErrorBox error={error} onRetry={load}/>} {loading&&!data?<Skeleton rows={6}/>:data&&<><div className="regime-grid">{data.factors?.map((f:any)=><article className="card reveal-card regime-card" key={f.factor}><span>{f.factor}</span><strong className={f.score>=0?"positive":"negative"}>{f.state}</strong><small>{f.score>=0?"+":""}{f.score.toFixed(2)}</small></article>)}</div><div className="card reveal-card suite-grid-card"><h2>Cross-asset tape</h2><div className="suite-table"><div className="suite-row cross suite-head"><span>Proxy</span><span>Role</span><span>1D</span><span>7D</span><span>30D</span></div>{data.cross_asset?.map((x:any)=><div className="suite-row cross" key={x.symbol}><strong>{x.symbol}</strong><span>{x.label}</span><span className={(x.day||0)>=0?"positive":"negative"}>{pct(x.day)}</span><span>{pct(x.seven_day)}</span><span>{pct(x.thirty_day)}</span></div>)}</div></div></>}</section>
}

export function ResearchPanel({initialSymbol="AAOI"}:{initialSymbol?:string}){
 const[symbol,setSymbol]=useState(initialSymbol),[query,setQuery]=useState(initialSymbol),[workspace,setWorkspace]=useState<any>(null),[analogs,setAnalogs]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async(s=symbol)=>{const sym=s.trim().toUpperCase();if(!sym)return;setLoading(true);setError("");try{const[w,a]=await Promise.all([api(`/api/v1/security/${encodeURIComponent(sym)}/workspace`),api(`/api/v1/security/${encodeURIComponent(sym)}/analogs?limit=6`)]);setSymbol(sym);setQuery(sym);setWorkspace(w);setAnalogs(a)}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load(initialSymbol)},[]);const m=workspace?.market||{},o=workspace?.opportunity||{};
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Unified security workspace</span><h2>Research</h2></div><form className="research-search" onSubmit={e=>{e.preventDefault();load(query)}}><input className="search" value={query} onChange={e=>setQuery(e.target.value.toUpperCase())}/><button className="btn">Open</button></form></div>{loading&&<Skeleton rows={8}/>} {error&&<ErrorBox error={error} onRetry={()=>load(symbol)}/>} {!loading&&workspace&&<><div className="security-title card reveal-card"><div><span className="eyebrow">{workspace.registry?.sector||m.sector||"Security"}</span><h2>{symbol} · {money(m.price)}</h2><span className="muted">{workspace.registry?.name||m.name||""}</span></div><strong className={(m.change_percent||0)>=0?"positive":"negative"}>{pct(m.change_percent)} today</strong></div><div className="suite-stat-grid"><article className="card stat-card"><span>Buy score</span><strong className={scoreClass(o.buy_score||50)}>{o.buy_score??"—"}</strong></article><article className="card stat-card"><span>Williams %R</span><strong>{m.williams_r_14?.toFixed?.(1)??"—"}</strong></article><article className="card stat-card"><span>Rel volume</span><strong>{m.relative_volume?.toFixed?.(2)??"—"}x</strong></article><article className="card stat-card"><span>P/E</span><strong>{m.pe_ratio?.toFixed?.(2)??"—"}</strong></article></div><div className="card reveal-card"><h2>Closest historical analogs</h2><div className="analog-grid">{analogs?.analogs?.length?analogs.analogs.map((a:any)=><article key={a.date}><strong>{a.date}</strong><span>1D {pct(a.return_1d)}</span><span>5D {pct(a.return_5d)}</span><b className={(a.following_5d||0)>=0?"positive":"negative"}>Next 5D {pct(a.following_5d)}</b></article>):<Empty>Not enough stored history yet.</Empty>}</div></div></>}</section>
}

export function AlertsPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[symbol,setSymbol]=useState("AAOI"),[kind,setKind]=useState("williams"),[operator,setOperator]=useState("<="),[threshold,setThreshold]=useState("-80"),[label,setLabel]=useState("Oversold technical alert");
 const load=async()=>{setLoading(true);try{setData(await api("/api/v1/alerts"));setError("")}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();try{await api("/api/v1/alerts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol,kind,operator,threshold:Number(threshold),label})});load()}catch(e:any){setError(e.message)}} async function remove(id:number){try{await api(`/api/v1/alerts/${id}`,{method:"DELETE"});load()}catch(e:any){setError(e.message)}}
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Condition monitoring</span><h2>Alerts</h2></div>{loading&&<Spinner/>}</div>{error&&<ErrorBox error={error} onRetry={load}/>}<div className="suite-two"><div className="card reveal-card"><h2>Rules</h2>{data?.alerts?.length?data.alerts.map((a:any)=><div className={`alert-row ${a.triggered?"triggered":""}`} key={a.id}><div><strong>{a.symbol||"Global"} · {a.label}</strong><span>{a.kind} {a.operator} {a.threshold}</span></div><button className="text-btn" onClick={()=>remove(a.id)}>Remove</button></div>):<Empty>No alert rules yet.</Empty>}</div><form className="card reveal-card suite-form" onSubmit={create}><h2>New alert</h2><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/><select className="search" value={kind} onChange={e=>setKind(e.target.value)}><option value="price">Price</option><option value="williams">Williams %R</option><option value="buy_score">Buy score</option></select><div className="form-pair"><select className="search" value={operator} onChange={e=>setOperator(e.target.value)}><option>&gt;=</option><option>&lt;=</option><option>&gt;</option><option>&lt;</option></select><input className="search" value={threshold} onChange={e=>setThreshold(e.target.value)}/></div><input className="search" value={label} onChange={e=>setLabel(e.target.value)}/><button className="btn">Create alert</button></form></div></section>
}

export function ThesisPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[title,setTitle]=useState("AI infrastructure buildout"),[statement,setStatement]=useState("AI infrastructure spending remains elevated, supporting photonics, memory, semiconductors and compute infrastructure."),[symbols,setSymbols]=useState("AAOI,AXTI,SNDK,MU,NBIS,SMH");
 const load=async()=>{setLoading(true);try{setData(await api("/api/v1/theses"));setError("")}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);async function create(e:FormEvent){e.preventDefault();try{await api("/api/v1/theses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,statement,symbols:symbols.split(",").map(s=>s.trim()).filter(Boolean)})});load()}catch(e:any){setError(e.message)}}async function remove(id:number){try{await api(`/api/v1/theses/${id}`,{method:"DELETE"});load()}catch(e:any){setError(e.message)}}
 return <section className="tab-panel suite-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Evidence tracking</span><h2>Thesis Engine</h2></div>{loading&&<Spinner/>}</div>{error&&<ErrorBox error={error} onRetry={load}/>}<div className="thesis-grid">{data?.theses?.map((t:any)=><article className="card reveal-card thesis-card" key={t.id}><h2>{t.title}</h2><p>{t.statement}</p><strong className={t.health==="strengthening"?"positive":t.health==="weakening"?"negative":""}>{t.health} · {t.score}</strong><button className="text-btn" onClick={()=>remove(t.id)}>Remove thesis</button></article>)}</div><form className="card reveal-card suite-form thesis-form" onSubmit={create}><input className="search" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="search" value={statement} onChange={e=>setStatement(e.target.value)}/><input className="search" value={symbols} onChange={e=>setSymbols(e.target.value.toUpperCase())}/><button className="btn">Create thesis</button></form></section>
}

export function DataHealthPanel(){
 const[data,setData]=useState<any>(null),[queue,setQueue]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=async()=>{setLoading(true);try{const[d,q]=await Promise.all([api("/api/v1/system/data-health"),api("/api/v1/refresh-queue")]);setData(d);setQueue(q);setError("")}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);async function process(){setLoading(true);try{await api("/api/v1/refresh-queue/process?limit=5",{method:"POST"});await api("/api/v1/features/refresh",{method:"POST"});load()}catch(e:any){setError(e.message);setLoading(false)}}
 return <div className="suite-health">{error&&<ErrorBox error={error} onRetry={load}/>}<div className="card reveal-card suite-hero"><div><span className="eyebrow">Backend observability</span><h2>Data Health</h2></div><button className="btn" disabled={loading} onClick={process}>{loading?"Working…":"Process queue + features"}</button></div>{loading&&!data?<Skeleton rows={5}/>:data&&<><div className="suite-stat-grid"><article className="card stat-card"><span>Symbols</span><strong>{data.symbols}</strong></article><article className="card stat-card"><span>Fresh markets</span><strong>{data.market_fresh}</strong></article><article className="card stat-card"><span>Fresh fundamentals</span><strong>{data.fundamentals_fresh}</strong></article><article className="card stat-card"><span>History fresh</span><strong>{data.history_fresh??"—"}</strong></article></div><div className="card reveal-card"><h2>Refresh queue</h2>{queue?.items?.slice(0,12).map((x:any)=><div className="health-row" key={x.id}><strong>{x.symbol}</strong><span>{x.data_class}</span><span className={`data-badge ${x.status==="failed"?"stale":"cached"}`}>{x.status}</span></div>)}</div></>}</div>
}

export function DensityControl(){const[density,setDensity]=useState("comfortable");useEffect(()=>{const d=localStorage.getItem("dailyReportDensity")||"comfortable";setDensity(d);document.documentElement.dataset.density=d},[]);function set(d:string){setDensity(d);localStorage.setItem("dailyReportDensity",d);document.documentElement.dataset.density=d}return <div className="card reveal-card"><span className="eyebrow">Interface density</span><h2>Data density</h2><div className="view-toggle"><button className={`toggle ${density==="comfortable"?"active":""}`} onClick={()=>set("comfortable")}>Comfortable</button><button className={`toggle ${density==="compact"?"active":""}`} onClick={()=>set("compact")}>Compact</button></div></div>}
