"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const email=localStorage.getItem("dailyReportUserEmail")||"",token=localStorage.getItem("dailyReportUserToken")||"";return {...(email?{"X-User-Email":email}:{}),...(token?{"X-User-Token":token}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const money=(v:number|null|undefined)=>v==null?"—":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:Math.abs(v)>=1e6?`$${(v/1e6).toFixed(2)}M`:Math.abs(v)>=1e3?`$${(v/1e3).toFixed(1)}K`:`$${v.toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${Number(v).toFixed(2)}%`;
const num=(v:number|null|undefined,d=2)=>v==null?"—":Number(v).toFixed(d);
function goTab(name:string){const btn=Array.from(document.querySelectorAll<HTMLButtonElement>(".nav button")).find(x=>(x.textContent||"").trim()===name);btn?.click();}
function Loading(){return <div className="suite-skeleton">{Array.from({length:7}).map((_,i)=><span key={i}/>)}</div>}
function ErrorBox({text,onRetry}:{text:string;onRetry:()=>void}){return <div className="suite-error"><strong>Unable to load</strong><span>{text}</span><button className="btn" onClick={onRetry}>Retry</button></div>}

function MiniGauge({value,min=0,max=100}:{value:number|null|undefined;min?:number;max?:number}){const n=value==null?0:Math.max(0,Math.min(100,(Number(value)-min)/(max-min)*100));return <div className="metric-gauge" aria-hidden="true"><i style={{width:`${n}%`}}/></div>}
function MetricDisclosure({title,value,source,detail,tab,sourceUrl,visualValue,min=0,max=100}:{title:string;value:string;source:string;detail:string;tab?:string;sourceUrl?:string;visualValue?:number|null;min?:number;max?:number}){return <details className="metric-disclosure"><summary><span>{title}<small>{source}</small></span><strong>{value}</strong><b>▾</b></summary><div className="metric-disclosure-body">{visualValue!=null&&<MiniGauge value={visualValue} min={min} max={max}/>}<p>{detail}</p><div className="metric-links">{tab&&<button className="text-btn" onClick={()=>goTab(tab)}>Open {tab} →</button>}{sourceUrl&&<a className="source-link" href={sourceUrl} target="_blank" rel="noreferrer">Source ↗</a>}</div></div></details>}

export function AdvancedEvents(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sort,setSort]=useState("date"),[order,setOrder]=useState("asc"),[impact,setImpact]=useState("all"),[category,setCategory]=useState("all");
 const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/events?days=180&sort=date&order=asc&limit=700"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>{let r=[...(data?.events||[])];if(impact!=="all")r=r.filter((x:any)=>x.impact===impact);if(category!=="all")r=r.filter((x:any)=>x.category===category);const dir=order==="asc"?1:-1;r.sort((a:any,b:any)=>{let av:any,bv:any;if(sort==="impact"){av=a.impact_score||0;bv=b.impact_score||0}else if(sort==="category"){av=a.category||"";bv=b.category||""}else if(sort==="source"){av=a.source||"";bv=b.source||""}else{av=`${a.event_date||""} ${a.time||""}`;bv=`${b.event_date||""} ${b.time||""}`}return av>bv?dir:av<bv?-dir:0});return r},[data,sort,order,impact,category]);
 const groups=useMemo(()=>{const m=new Map<string,any[]>();for(const e of rows){const d=e.event_date||"Unscheduled";m.set(d,[...(m.get(d)||[]),e])}return [...m.entries()]},[rows]);
 return <section className="tab-panel v2-panel events-v2-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Multi-source catalyst calendar</span><h2>Events</h2><p className="muted">Official BLS, BEA and Federal Reserve schedules, MacroRadar fallback, and cached earnings dates in one sortable calendar.</p></div><button className="btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>
  <div className="card reveal-card v2-toolbar"><label>Sort<select className="search" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Date / time</option><option value="impact">Impact</option><option value="category">Category</option><option value="source">Source</option></select></label><label>Order<select className="search" value={order} onChange={e=>setOrder(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label><label>Impact<select className="search" value={impact} onChange={e=>setImpact(e.target.value)}><option value="all">All</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Category<select className="search" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All</option>{(data?.categories||[]).map((x:string)=><option key={x}>{x}</option>)}</select></label><strong>{rows.length} events</strong></div>
  {error&&<ErrorBox text={error} onRetry={load}/>} {loading&&!data?<Loading/>:<div className="event-v2-list">{groups.map(([d,events])=><details className="card reveal-card event-v2-day" key={d} open={groups.length<8}><summary><div><span className="eyebrow">{d}</span><h3>{events.length} scheduled event{events.length===1?"":"s"}</h3></div><span className="reason-count">{events.filter((x:any)=>x.impact==="high").length} high impact</span><b>▾</b></summary><div>{events.map((e:any,i:number)=><details className={`event-v2-item impact-${e.impact}`} key={`${e.title}-${i}`}><summary><span className={`data-badge ${e.impact==="high"?"live":e.impact==="medium"?"derived":"cached"}`}>{e.impact?.toUpperCase()}</span><strong>{e.time?`${e.time} · `:""}{e.title}</strong><span>{e.category}</span><b>▾</b></summary><div><p>{e.description||"Scheduled market event. Timing does not imply direction."}</p><div className="event-meta"><span>{e.source}</span>{e.symbol&&<button className="text-btn" onClick={()=>goTab("Research")}>{e.symbol} research →</button>}{e.category!=="Earnings"&&<button className="text-btn" onClick={()=>goTab("Macro")}>Macro context →</button>}{e.source_url&&<a className="source-link" href={e.source_url} target="_blank" rel="noreferrer">Official/source calendar ↗</a>}</div></div></details>)}</div></details>)}</div>}
  {data&&<details className="card reveal-card methodology-dropdown"><summary><strong>Calendar methodology & provider health</strong><b>▾</b></summary><p>{data.methodology}</p><div className="provider-chip-grid">{(data.providers||[]).map((p:any)=><span key={p.provider}>{p.provider}<b>{p.count}</b><small>{p.status}</small></span>)}</div>{data.errors?.length>0&&<p className="muted">Unavailable sources: {data.errors.join(" · ")}</p>}</details>}
 </section>
}

const COMPONENT_DETAILS:Record<string,{label:string;source:string;detail:string;tab:string}>={
 technical:{label:"Technicals",source:"Markets / shared daily history",tab:"Research",detail:"Starts at 50. Williams %R adds up to ±20 using (-50 − Williams) × 0.5. Being within 10% of the 100MA adds 8 and within 10% of the 200MA adds 10. A bounded 7D/30D momentum term adds up to ±12."},
 valuation:{label:"Valuation",source:"Yahoo Finance → SEC EDGAR → quota-aware Alpha fallback",tab:"Markets",detail:"Starts at 50. P/E contributes up to ±20 around a 30x reference, P/S up to ±15 around 6x, and PEG up to ±15 around 2x. Missing metrics remain neutral rather than being invented."},
 sector:{label:"Sector strength",source:"Macro sector proxy",tab:"Macro",detail:"The related sector score is 25% 1D + 45% 7D + 30% 30D sector-proxy performance. The component starts at 50 and moves by up to ±25."},
 flow:{label:"Options flow",source:"Large Flow / SquawkFlow",tab:"Large Flow",detail:"Net bullish minus bearish unusual-options premium is scaled by market capitalization. The component starts at 50 and is bounded to ±30 around neutral."},
 momentum:{label:"Relative strength",source:"Markets price history",tab:"Markets",detail:"This is the app's price-momentum/relative-strength proxy: 50 + bounded (2 × 7D return + 0.5 × 30D return), capped at ±30. It is not RSI and is not compared with an external benchmark."},
 risk:{label:"Risk context",source:"Markets technical state",tab:"Research",detail:"Starts at 50. Being within 5% of the stored all-time high subtracts 10; relative volume above 1.5× adds 8. It is intentionally simple and visible rather than a black-box risk model."},
};

export function AdvancedOpportunities(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[mode,setMode]=useState<"buy"|"sell">("buy");const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/opportunities?limit=150"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>[...(data?.opportunities||[])].sort((a:any,b:any)=>mode==="buy"?b.buy_score-a.buy_score:b.sell_score-a.sell_score),[data,mode]);
 return <section className="tab-panel v2-panel opportunities-v2-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Auditable opportunity engine</span><h2>Opportunities</h2><p className="muted">The headline score stays compact. Expand a ticker, then expand any component to see exactly where it came from and jump to the deeper source tab.</p></div><div className="view-toggle"><button className={`toggle ${mode==="buy"?"active":""}`} onClick={()=>setMode("buy")}>Buy setup</button><button className={`toggle ${mode==="sell"?"active":""}`} onClick={()=>setMode("sell")}>Sell / trim</button><button className="btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div></div>{error&&<ErrorBox text={error} onRetry={load}/>} {loading&&!data?<Loading/>:<div className="opportunity-v2-grid">{rows.map((r:any)=><details className="card reveal-card opportunity-v2-card" key={r.symbol}><summary><div><strong>{r.symbol}</strong><small>{mode==="buy"?"Buy setup":"Sell / trim setup"}</small></div><strong className={(mode==="buy"?r.buy_score:r.sell_score)>=60?"positive":(mode==="buy"?r.buy_score:r.sell_score)<=40?"negative":""}>{mode==="buy"?r.buy_score:r.sell_score}</strong><b>▾</b></summary><div className="component-disclosures">{Object.entries(r.components||{}).map(([k,v]:any)=>{const meta=COMPONENT_DETAILS[k]||{label:k,source:"Derived",detail:"Derived app component.",tab:"Research"};return <details className="component-disclosure" key={k}><summary><span>{meta.label}<small>{meta.source}</small></span><strong>{Number(v).toFixed(1)}</strong><b>▾</b></summary><div><MiniGauge value={v}/><p>{meta.detail}</p>{k==="sector"&&<p className="muted">Current related sector score: {r.sector_score??"—"}</p>}{k==="flow"&&<p className="muted">Bullish premium {money(r.flow?.bullish_premium)} · Bearish premium {money(r.flow?.bearish_premium)}</p>}<button className="text-btn" onClick={()=>goTab(meta.tab)}>Open {meta.tab} →</button></div></details>})}</div></details>)}</div>}{data&&<details className="card reveal-card methodology-dropdown"><summary><strong>Composite weighting</strong><b>▾</b></summary><p>{data.methodology}</p><p className="muted">Current weights: Technical 25% · Valuation 20% · Sector 15% · Flow 15% · Relative strength 15% · Risk 10%.</p></details>}</section>
}

export function AdvancedResearch(){
 const[symbol,setSymbol]=useState("AAOI"),[query,setQuery]=useState("AAOI"),[workspace,setWorkspace]=useState<any>(null),[analogs,setAnalogs]=useState<any>(null),[fund,setFund]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const load=async(s=query)=>{const sym=s.trim().toUpperCase();if(!sym)return;setLoading(true);setError("");try{const[w,a,f]=await Promise.all([api(`/api/v1/security/${encodeURIComponent(sym)}/workspace`),api(`/api/v1/security/${encodeURIComponent(sym)}/analogs?limit=8`),api(`/api/v1/markets/${encodeURIComponent(sym)}/fundamentals`)]);setSymbol(sym);setQuery(sym);setWorkspace(w);setAnalogs(a);setFund(f)}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load("AAOI")},[]);const m={...(workspace?.market||{}),...(fund||{})},o=workspace?.opportunity||{};
 return <section className="tab-panel v2-panel research-v2-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Explainable security workspace</span><h2>Research</h2><p className="muted">Every major metric is collapsible, visualized, source-labeled, and linked to the tab that owns the deeper context.</p></div><form className="research-search" onSubmit={e=>{e.preventDefault();load()}}><input className="search" value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Ticker"/><button className="btn">Open</button></form></div>{loading&&<Loading/>}{error&&<ErrorBox text={error} onRetry={()=>load(symbol)}/>} {!loading&&workspace&&<><div className="card reveal-card research-security-head"><div><span className="eyebrow">{workspace.registry?.sector||m.sector||"Security"}</span><h2>{symbol} · {money(m.price)}</h2><span className="muted">{workspace.registry?.name||m.name||""}</span></div><div><strong className={(m.change_percent||0)>=0?"positive":"negative"}>{pct(m.change_percent)} today</strong><small>{m.provider||"market provider"} · {m.as_of||"stored"}</small></div></div>
  <div className="research-v2-grid"><div className="card reveal-card disclosure-stack"><h3>Technical & price structure</h3><MetricDisclosure title="Williams %R" value={num(m.williams_r_14,1)} source="Shared daily history" visualValue={m.williams_r_14==null?null:100+Number(m.williams_r_14)} detail="14-period Williams %R. Values near -100 indicate the close is near the bottom of the recent high-low range; values near 0 indicate the top. The app calculates it from the same stored history used for moving averages." tab="Markets" sourceUrl={m.source_url}/><MetricDisclosure title="100MA distance" value={pct(m.price_vs_ma100_percent)} source="Markets" visualValue={m.price_vs_ma100_percent==null?null:50+Number(m.price_vs_ma100_percent)} min={0} max={100} detail={`100-day moving average ${money(m.ma100)}. Distance is (price / 100MA − 1) × 100.`} tab="Markets" sourceUrl={m.source_url}/><MetricDisclosure title="200MA distance" value={pct(m.price_vs_ma200_percent)} source="Markets" visualValue={m.price_vs_ma200_percent==null?null:50+Number(m.price_vs_ma200_percent)} detail={`200-day moving average ${money(m.ma200)}. It uses completed daily observations from the shared history cache.`} tab="Markets" sourceUrl={m.source_url}/><MetricDisclosure title="Relative volume" value={m.relative_volume==null?"—":`${num(m.relative_volume)}x`} source="Markets" visualValue={m.relative_volume==null?null:Number(m.relative_volume)} min={0} max={3} detail="Current completed daily volume divided by the 20-day average volume. It is a participation measure, not direction." tab="Markets" sourceUrl={m.source_url}/></div>
  <div className="card reveal-card disclosure-stack"><h3>Valuation</h3><MetricDisclosure title="P/E" value={num(m.pe_ratio)} source={fund?.field_sources?.pe_ratio||fund?.valuation_source||"Fundamentals cache"} visualValue={m.pe_ratio} min={0} max={60} detail={m.pe_ratio==null&&m.eps!=null&&m.eps<=0?"P/E is intentionally unavailable because trailing EPS is non-positive.":"Trailing P/E is provider-supplied when possible; otherwise it is derived from the shared price divided by available trailing/annual EPS."} tab="Markets" sourceUrl={fund?.source_url||m.source_url}/><MetricDisclosure title="P/S" value={num(m.price_to_sales_ratio)} source={fund?.field_sources?.price_to_sales_ratio||fund?.valuation_source||"Fundamentals cache"} visualValue={m.price_to_sales_ratio} min={0} max={20} detail="Price-to-sales uses provider P/S when available; otherwise market capitalization divided by revenue. SEC EDGAR standardized revenue is used as a fallback when richer trailing data is missing." tab="Markets" sourceUrl={fund?.source_url||m.source_url}/><MetricDisclosure title="PEG" value={num(m.peg_ratio)} source={fund?.field_sources?.peg_ratio||fund?.valuation_source||"Fundamentals cache"} visualValue={m.peg_ratio} min={0} max={4} detail="PEG is provider-supplied when possible. The fallback divides P/E by a positive earnings-growth estimate. If earnings or growth is non-positive, PEG is left unavailable rather than fabricated." tab="Markets" sourceUrl={fund?.source_url||m.source_url}/><details className="metric-disclosure"><summary><span>Provider coverage<small>Valuation data lineage</small></span><strong>{Object.values(fund?.coverage||{}).filter(Boolean).length}/3</strong><b>▾</b></summary><div className="metric-disclosure-body"><p>{fund?.valuation_note||fund?.valuation_source||"Fundamental fields are cached globally by symbol."}</p><p className="muted">Sources attempted: {(fund?.valuation_sources||[]).join(" → ")||fund?.provider||"—"}</p></div></details></div>
  <div className="card reveal-card disclosure-stack"><h3>Cross-tab intelligence</h3><MetricDisclosure title="Buy score" value={num(o.buy_score,1)} source="Opportunities" visualValue={o.buy_score} detail="Weighted composite of technical 25%, valuation 20%, sector 15%, flow 15%, relative strength 15%, and risk 10%." tab="Opportunities"/><MetricDisclosure title="Sector score" value={num(o.sector_score,2)} source="Macro → Opportunities" visualValue={o.sector_score==null?null:50+Number(o.sector_score)*4} detail="Related sector proxy score = 25% 1D + 45% 7D + 30% 30D performance. Open Macro for the full leadership/weakness view." tab="Macro"/><MetricDisclosure title="Bullish unusual flow" value={money(workspace.flow?.bullish_premium)} source="Large Flow" visualValue={workspace.flow?.bullish_premium} min={0} max={1000000} detail="Recent premium classified as bullish by contract type and execution direction. It is an observation of options activity, not a trade recommendation." tab="Large Flow"/><MetricDisclosure title="Bearish unusual flow" value={money(workspace.flow?.bearish_premium)} source="Large Flow" visualValue={workspace.flow?.bearish_premium} min={0} max={1000000} detail="Recent premium classified as bearish by contract type and execution direction." tab="Large Flow"/></div>
  </div>
  <details className="card reveal-card methodology-dropdown"><summary><div><span className="eyebrow">Historical visualization</span><h3>Closest analogs</h3></div><b>▾</b></summary><div className="analog-v2-grid">{analogs?.analogs?.length?analogs.analogs.map((a:any)=><article key={a.date}><strong>{a.date}</strong><MiniGauge value={Math.max(0,100-a.distance*20)}/><span>1D {pct(a.return_1d)}</span><span>5D {pct(a.return_5d)}</span><span>21D {pct(a.return_21d)}</span><span>RV {a.relative_volume}x</span><b className={(a.following_5d||0)>=0?"positive":"negative"}>Following 5D {pct(a.following_5d)}</b></article>):<p className="muted">Not enough stored history yet.</p>}</div><p className="muted">{analogs?.methodology}</p></details>
 </>}</section>
}

function urlBase64ToUint8Array(base64String:string){const padding="=".repeat((4-base64String.length%4)%4),base64=(base64String+padding).replace(/-/g,"+").replace(/_/g,"/");const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
export function AdvancedAlerts(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[symbols,setSymbols]=useState("AAOI"),[kind,setKind]=useState("williams"),[operator,setOperator]=useState("<="),[threshold,setThreshold]=useState("-80"),[label,setLabel]=useState("Oversold technical alert"),[cooldown,setCooldown]=useState("360"),[push,setPush]=useState(true),[inApp,setInApp]=useState(true),[pushStatus,setPushStatus]=useState("");
 const load=async()=>{setLoading(true);setError("");try{setData(await api("/api/v1/alerts/v2"))}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();try{const list=symbols.split(/[\s,]+/).map(x=>x.trim().toUpperCase()).filter(Boolean);await api("/api/v1/alerts/v2",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:list,kind,operator,threshold:Number(threshold),label,channels:{in_app:inApp,push},cooldown_minutes:Number(cooldown)})});await load()}catch(e:any){setError(e.message)}}
 async function remove(id:number){await api(`/api/v1/alerts/v2/${id}`,{method:"DELETE"});load()}
 async function enablePush(){setPushStatus("Preparing push…");try{const cfg=await api("/api/v1/push/config");if(!cfg.configured||!cfg.public_key){setPushStatus("Server Web Push keys are not configured yet.");return}if(!("serviceWorker" in navigator)||!("PushManager" in window)){setPushStatus("This browser does not support Web Push.");return}const permission=await Notification.requestPermission();if(permission!=="granted"){setPushStatus("Notification permission was not granted.");return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(cfg.public_key)});await api("/api/v1/push/subscriptions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription:sub.toJSON(),platform:navigator.userAgent.includes("iPhone")?"iOS PWA":"web"})});setPushStatus("Push notifications enabled on this device.");await load()}catch(e:any){setPushStatus(e.message||"Push setup failed")}}
 const vars=data?.variables||{};
 return <section className="tab-panel v2-panel alerts-v2-panel"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Custom condition monitoring</span><h2>Alerts</h2><p className="muted">Create one rule across multiple tickers, choose from market, valuation, technical, Macro, Opportunities and Large Flow variables, and deliver in-app or Web Push notifications.</p></div><button className="btn" onClick={enablePush}>Enable push on this device</button></div>{pushStatus&&<div className="card reveal-card alert-push-status"><span className={`data-badge ${pushStatus.includes("enabled")?"live":"cached"}`}>PUSH</span><p>{pushStatus}</p></div>}{error&&<ErrorBox text={error} onRetry={load}/>}<div className="alerts-v2-layout"><form className="card reveal-card suite-form" onSubmit={create}><h3>New alert</h3><label>Tickers<input className="search" value={symbols} onChange={e=>setSymbols(e.target.value.toUpperCase())} placeholder="AAOI, NBIS, IONQ"/><small>Comma or space separated; one rule is created for each ticker.</small></label><label>Variable<select className="search" value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(vars).map(([k,v]:any)=><option value={k} key={k}>{v.label} · {v.source}</option>)}</select></label><div className="form-pair"><select className="search" value={operator} onChange={e=>setOperator(e.target.value)}><option>&gt;=</option><option>&lt;=</option><option>&gt;</option><option>&lt;</option><option>==</option></select><input className="search" inputMode="decimal" value={threshold} onChange={e=>setThreshold(e.target.value)}/></div><input className="search" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Notification label"/><label>Cooldown<select className="search" value={cooldown} onChange={e=>setCooldown(e.target.value)}><option value="15">15 minutes</option><option value="60">1 hour</option><option value="360">6 hours</option><option value="1440">1 day</option><option value="10080">1 week</option></select></label><div className="alert-channel-row"><label><input type="checkbox" checked={inApp} onChange={e=>setInApp(e.target.checked)}/> In-app</label><label><input type="checkbox" checked={push} onChange={e=>setPush(e.target.checked)}/> Push</label></div><button className="btn">Create alerts</button>{vars[kind]&&<details className="inline-method"><summary>What does this variable mean?</summary><p>{vars[kind].description}</p><button type="button" className="text-btn" onClick={()=>goTab(vars[kind].source.split(" /")[0].split(" →")[0])}>Open source tab →</button></details>}</form>
 <div className="card reveal-card alert-rules-v2"><div className="section-head"><div><span className="eyebrow">Active rules</span><h3>{data?.alerts?.length||0} alerts</h3></div>{loading&&<span className="suite-spinner"><i/>Refreshing</span>}</div>{(data?.alerts||[]).map((a:any)=><details className={`alert-v2-row ${a.triggered?"triggered":""}`} key={a.id}><summary><div><strong>{a.symbol} · {a.label}</strong><small>{vars[a.kind]?.label||a.kind} {a.operator} {a.threshold}</small></div><span className={`data-badge ${a.triggered?"live":"cached"}`}>{a.triggered?"TRIGGERED":"WATCHING"}</span><b>▾</b></summary><div><p>Current value: <strong>{a.current_value??"—"}</strong></p><p className="muted">{vars[a.kind]?.description}</p><p className="muted">Delivery: {Object.entries(a.delivery?.channels||{}).filter(([,v])=>v).map(([k])=>k).join(" + ")||"in-app"} · cooldown {a.delivery?.cooldown_minutes||360} min</p><div className="metric-links"><button className="text-btn" onClick={()=>goTab((vars[a.kind]?.source||"Markets").split(" /")[0].split(" →")[0])}>Open source tab →</button><button className="text-btn danger" onClick={()=>remove(a.id)}>Remove</button></div></div></details>)}</div></div>
 <details className="card reveal-card methodology-dropdown"><summary><strong>Notification behavior</strong><b>▾</b></summary><p>Rules evaluate against the shared cache in the backend scheduler, so adding users does not multiply provider pulls. In-app events are persistent. Web Push can notify compatible desktop browsers and installed iPhone/iPad PWAs even when the app is not open, once VAPID keys are configured and the user grants permission.</p><p className="muted">Current server push configuration: {data?.push?.configured?"ready":"not configured"} · registered devices {data?.push?.subscriptions||0}.</p></details></section>
}

const GUIDES:Record<string,{metric:string;source:string;tab?:string;detail:string}[]>={
 Report:[{metric:"Sentiment",source:"App composite + external public sources",detail:"Composite breadth/market context plus external sentiment cards; normalized values remain labeled."},{metric:"Outliers",source:"Markets",tab:"Markets",detail:"Largest absolute 1D/7D/30D moves from stored watchlist snapshots."}],
 Markets:[{metric:"Williams %R / MAs",source:"Shared daily history",tab:"Research",detail:"Derived locally from the same daily-history pull to avoid extra provider calls."},{metric:"P/E · P/S · PEG",source:"Yahoo → SEC EDGAR → Alpha fallback",tab:"Research",detail:"Provider data is merged globally by symbol; missing non-applicable ratios remain blank."}],
 Portfolio:[{metric:"Live account value",source:"Markets shared cache",tab:"Markets",detail:"Current price × current shares + cash; account weights and P/L recalculate from the latest stored market snapshot."},{metric:"Baseline",source:"User-entered/imported portfolio state",detail:"Initial shares, average cost and starting values are preserved separately from live values."}],
 "World News":[{metric:"Relevance",source:"GDELT / Google News RSS",detail:"News discovery and classification score; links open the original publisher."}],
 "Large Flow":[{metric:"Relative flow size",source:"SquawkFlow + cached market cap",tab:"Markets",detail:"Observed premium divided by market capitalization when market cap is available."}],
 Macro:[{metric:"Rotation score",source:"Sector ETF history",detail:"Weighted 1D/7D/30D performance and participation context; expand a leader/laggard for catalysts and technicals."}],
 Regime:[{metric:"Regime factors",source:"Cross-asset ETF history",tab:"Macro",detail:"Risk appetite, growth, rates, dollar and breadth are derived from stored cross-asset proxies."}],
 Theses:[{metric:"Thesis health",source:"Opportunities + Markets + Flow",tab:"Opportunities",detail:"Evidence is assembled from shared symbol scores and is descriptive, not a forecast."}],
 Settings:[{metric:"Data health",source:"Backend cache/queue",detail:"Shows freshness, queue state and provider policy without triggering additional market pulls."}],
};
export function TabDisclosureGuide({active}:{active:string}){const rows=GUIDES[active];if(!rows?.length)return null;return <details className="card reveal-card methodology-dropdown tab-guide"><summary><strong>{active} · data & calculation guide</strong><span className="muted">collapsed by default</span><b>▾</b></summary><div className="guide-grid">{rows.map(x=><article key={x.metric}><strong>{x.metric}</strong><span>{x.source}</span><p>{x.detail}</p>{x.tab&&<button className="text-btn" onClick={()=>goTab(x.tab!)}>Open {x.tab} →</button>}</article>)}</div></details>}

export function MacroExpansionSuggestions(){const items=[
 ["International leadership","EFA · EEM · EWJ · VGK · FXI","See whether leadership is broadening outside the U.S. and whether dollar moves are translating into regional equity leadership."],
 ["Factor rotation","RSP · MTUM · QUAL · SPLV","Separate cap-weighted index strength from equal-weight breadth, momentum, quality and low-volatility leadership."],
 ["Housing & rates","ITB · XHB","Adds a highly rate-sensitive real-economy group that can react differently from long-duration technology."],
 ["Retail / consumer breadth","XRT","Useful cross-check against XLY because equal-weight retail can expose weaker consumer breadth hidden by mega-cap names."],
 ["Cloud / internet","SKYY or CLOU · FDN","Splits software/internet demand from broad XLK and semiconductor leadership."],
 ["Grid / electrification","GRID","Complements PAVE, NLR and utilities for AI-power buildout, transmission and electrical-equipment demand."],
 ["Critical materials","REMX · SLV · GDX","Adds rare earths, silver and miners alongside copper/metals to capture supply-chain and monetary commodity regimes."],
 ["Clean energy / solar","ICLN · TAN","High-duration policy-sensitive energy exposure that can diverge sharply from oil, uranium and utilities."],
 ["Credit stress","LQD · JNK/HYG","HYG is already in Regime; adding investment-grade credit makes spread/risk appetite comparisons more informative."],
];return <details className="card reveal-card methodology-dropdown macro-expansion"><summary><div><span className="eyebrow">Suggested expansion</span><strong>Additional Macro groups worth tracking</strong></div><b>▾</b></summary><div className="macro-suggestion-grid">{items.map(([name,tickers,why])=><article key={name}><strong>{name}</strong><span>{tickers}</span><p>{why}</p></article>)}</div></details>}
