"use client";
import {useEffect,useMemo,useState} from "react";

const API="/backend";
async function api(path:string,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("Large Flow request timed out. Retry when ready.");throw e}finally{clearTimeout(t)}}
const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:Math.abs(Number(v))>=1e6?`$${(Number(v)/1e6).toFixed(2)}M`:Math.abs(Number(v))>=1e3?`$${(Number(v)/1e3).toFixed(0)}K`:`$${Number(v).toFixed(0)}`;
function execution(v:any){const s=String(v||"").toLowerCase();if(/buy|ask|lift/.test(s))return"buy";if(/sell|bid|hit/.test(s))return"sell";return"unknown"}function side(d:any){return String(d?.side||d?.option_type||d?.put_call||"option").toLowerCase()}function bias(d:any){const s=side(d),x=execution(d?.aggression||d?.execution||d?.direction);if((s==="call"&&x==="buy")||(s==="put"&&x==="sell"))return"positive";if((s==="call"&&x==="sell")||(s==="put"&&x==="buy"))return"negative";return"neutral"}function signal(d:any){const x=execution(d?.aggression||d?.execution||d?.direction),s=side(d);return `${x==="unknown"?"—":x.toUpperCase()} ${s.toUpperCase()}`}function key(e:any){const d=e.data||{};return [e.symbol,side(d),d.strike??"?",d.expiration||"?"].join("|")}function dedupe(rows:any[]){const m=new Map<string,any>();for(const e of rows){const k=key(e),old=m.get(k);if(!old||(e.data?.premium||0)>=(old.data?.premium||0))m.set(k,e)}return [...m.values()]}
function expired(e:any){const raw=e.data?.expiration;if(!raw)return false;const t=Date.parse(`${String(raw).slice(0,10)}T23:59:59Z`);return Number.isFinite(t)&&t<Date.now()}function recent(e:any,hours:number){const t=Date.parse(e.occurred_at||"");return Number.isFinite(t)&&Date.now()-t<=hours*3600000}function age(v:any){const t=Date.parse(v||"");if(!Number.isFinite(t))return"age unavailable";const h=(Date.now()-t)/3600000;return h<1?`${Math.max(0,Math.round(h*60))}m old`:h<24?`${h.toFixed(1)}h old`:`${(h/24).toFixed(1)}d old`}function Loading(){return <div className="suite-skeleton" role="status">{Array.from({length:8}).map((_,i)=><span key={i}/>)}</div>}

export default function LargeFlowWorkspaceV3(){const[feed,setFeed]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Feed"),[filter,setFilter]=useState(""),[status,setStatus]=useState<"active"|"expired"|"all">("active"),[windowHours,setWindowHours]=useState(72);
 async function load(){setLoading(true);setError("");try{const[f,a]=await Promise.all([api("/api/v1/flow/recent?limit=100"),api("/api/v1/flow/analytics?hours=72")]);setFeed(f);setAnalytics(a)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const events=useMemo(()=>dedupe(feed?.events||[]).filter((e:any)=>!filter||e.symbol===filter.trim().toUpperCase()).filter((e:any)=>status==="all"||status==="expired"?status==="all"||expired(e):!expired(e)).filter((e:any)=>windowHours===0||recent(e,windowHours)),[feed,filter,status,windowHours]);const relative=[...(analytics?.rows||[])].sort((a:any,b:any)=>(b.flow_to_market_cap||0)-(a.flow_to_market_cap||0));
 return <section className="tab-panel v3-workspace flow-v3"><div className="card suite-hero"><div><span className="eyebrow">Shared unusual-options intelligence</span><h2>Large Flow</h2><p className="muted">Default feed: active contracts observed within 72 hours. Expired contracts are historical context and require an explicit filter.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div><div className="subtab-bar" role="tablist">{["Feed","Relative Flow","Persistence","Methodology"].map(x=><button key={x} role="tab" aria-selected={tab===x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error" role="alert"><strong>Large Flow unavailable</strong><span>{error}</span><button className="btn" onClick={load}>Retry</button></div>}{loading&&!feed?<Loading/>:<>
 {tab==="Feed"&&<div className="v3-stack"><div className="card flow-filter-v3"><div><strong>{feed?.provider||"SquawkFlow"}</strong><span className="muted">{events.length} visible unique contracts</span></div><label>Ticker<input className="search" value={filter} onChange={e=>setFilter(e.target.value.toUpperCase())} placeholder="All tickers"/></label></div><div className="card v2-toolbar"><div className="view-toggle" role="group" aria-label="Contract status">{(["active","expired","all"] as const).map(x=><button key={x} aria-pressed={status===x} className={status===x?"active":""} onClick={()=>setStatus(x)}>{x==="active"?"Active only":x==="expired"?"Expired":"All contracts"}</button>)}</div><div className="view-toggle" role="group" aria-label="Observation window">{[[24,"24h"],[72,"72h"],[168,"7d"],[0,"All history"]].map(([h,label]:any)=><button key={label} aria-pressed={windowHours===h} className={windowHours===h?"active":""} onClick={()=>setWindowHours(h)}>{label}</button>)}</div></div><div className="card flow-grid-wrap"><table className="flow-grid-table"><thead><tr><th>Ticker</th><th>Flow</th><th>Premium</th><th>Strike</th><th>Expiration</th><th>Flow / cap</th><th>Contracts</th><th>Vol/OI</th><th>Observed</th><th>Age</th><th>Source</th></tr></thead><tbody>{events.map((e:any)=>{const d=e.data||{},cap=d.market_cap||0,p=d.premium||0;return <tr key={key(e)} className={expired(e)?"stale-row":""}><td><strong>{e.symbol}</strong></td><td><span className={`flow-signal ${bias(d)}`}>{signal(d)}</span></td><td><strong>{money(p)}</strong></td><td>{d.strike==null?"—":`$${Number(d.strike).toFixed(2)}`}</td><td>{d.expiration||"—"}{expired(e)&&<small className="data-badge stale">EXPIRED</small>}</td><td>{p&&cap?`${(p/cap*10000).toFixed(2)} bps`:"—"}</td><td>{d.contracts?.toLocaleString?.()||"—"}</td><td>{d.volume_oi_ratio==null?"—":`${Number(d.volume_oi_ratio).toFixed(2)}x`}</td><td>{e.occurred_at?new Date(e.occurred_at).toLocaleString():"—"}</td><td>{age(e.occurred_at)}</td><td>{e.source_url?<a href={e.source_url} target="_blank" rel="noreferrer">Open ↗</a>:"—"}</td></tr>})}</tbody></table></div>{!events.length&&<div className="card inline-state"><span>No observations match the selected status/time/ticker filters.</span></div>}</div>}
 {tab==="Relative Flow"&&<details className="card methodology-dropdown" open><summary><div><span className="eyebrow">Small-cap sensitivity</span><strong>Premium relative to market capitalization</strong></div><b>▾</b></summary><div className="relative-flow-grid">{relative.map((r:any)=><article key={r.symbol}><div><strong>{r.symbol}</strong><span>{r.unique_contracts} contracts · {r.events} observations</span></div><b>{r.flow_to_market_cap==null?"—":`${(r.flow_to_market_cap*10000).toFixed(2)} bps`}</b><span>{money(r.total_premium)} total</span><small>{r.flow_to_daily_dollar_volume==null?"ADV ratio —":`${(r.flow_to_daily_dollar_volume*100).toFixed(2)}% of daily $ volume proxy`}</small></article>)}</div></details>}
 {tab==="Persistence"&&<div className="card"><h3>1h / 24h / 72h premium persistence</h3><div className="persistence-grid">{relative.map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>1H <b>{money(r.premium_1h)}</b></span><span>24H <b>{money(r.premium_24h)}</b></span><span>72H <b>{money(r.premium_72h)}</b></span><small>{r.unique_contracts} unique contracts</small></div>)}</div></div>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Interpretation & freshness</strong><b>▾</b></summary><p>Green = call buys or put sells. Red = call sells or put buys. The current feed excludes expired contracts by default and displays observation age so historical activity cannot be mistaken for current flow.</p></details><details className="card methodology-dropdown"><summary><strong>Data reuse</strong><b>▾</b></summary><p>All requests use the authenticated same-origin backend proxy. No legacy localStorage identity headers are sent.</p></details></div>}
 </>}</section>}
