"use client";

import {useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:Math.abs(Number(v))>=1e6?`$${(Number(v)/1e6).toFixed(2)}M`:Math.abs(Number(v))>=1e3?`$${(Number(v)/1e3).toFixed(0)}K`:`$${Number(v).toFixed(0)}`;
function execution(v:any){const s=String(v||"").toLowerCase();if(/buy|ask|lift/.test(s))return"buy";if(/sell|bid|hit/.test(s))return"sell";return"unknown"}
function side(d:any){return String(d?.side||d?.option_type||d?.put_call||"option").toLowerCase()}
function bias(d:any){const s=side(d),x=execution(d?.aggression||d?.execution||d?.direction);if((s==="call"&&x==="buy")||(s==="put"&&x==="sell"))return"positive";if((s==="call"&&x==="sell")||(s==="put"&&x==="buy"))return"negative";return"neutral"}
function signal(d:any){const x=execution(d?.aggression||d?.execution||d?.direction),s=side(d);return `${x==="unknown"?"—":x.toUpperCase()} ${s.toUpperCase()}`}
function key(e:any){const d=e.data||{};return [e.symbol,side(d),d.strike??"?",d.expiration||"?"].join("|")}
function dedupe(rows:any[]){const m=new Map<string,any>();for(const e of rows){const k=key(e),old=m.get(k);if(!old||(e.data?.premium||0)>=(old.data?.premium||0))m.set(k,e)}return [...m.values()]}
function Loading(){return <div className="suite-skeleton">{Array.from({length:8}).map((_,i)=><span key={i}/>)}</div>}

export default function LargeFlowWorkspaceV3(){
 const[feed,setFeed]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Feed"),[filter,setFilter]=useState("");
 async function load(){setLoading(true);setError("");try{const[f,a]=await Promise.all([api("/api/v1/flow/recent?limit=100"),api("/api/v1/flow/analytics?hours=72")]);setFeed(f);setAnalytics(a)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const events=useMemo(()=>dedupe(feed?.events||[]).filter((e:any)=>!filter||e.symbol===filter.trim().toUpperCase()),[feed,filter]);
 const relative=[...(analytics?.rows||[])].sort((a:any,b:any)=>(b.flow_to_market_cap||0)-(a.flow_to_market_cap||0));
 return <section className="tab-panel v3-workspace flow-v3"><div className="card suite-hero"><div><span className="eyebrow">Shared unusual-options intelligence</span><h2>Large Flow</h2><p className="muted">Contract feed, relative-size rankings and persistence are separated into subviews so the page stays readable.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Refreshing…":"Refresh"}</button></div><div className="subtab-bar">{["Feed","Relative Flow","Persistence","Methodology"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
 {error&&<div className="suite-error"><strong>Large Flow unavailable</strong><span>{error}</span></div>}{loading&&!feed?<Loading/>:<>
 {tab==="Feed"&&<div className="v3-stack"><div className="card flow-filter-v3"><div><strong>{feed?.provider||"SquawkFlow"}</strong><span className="muted">{events.length} unique aggregated contracts</span></div><input className="search" value={filter} onChange={e=>setFilter(e.target.value.toUpperCase())} placeholder="Filter ticker"/></div><div className="card flow-grid-wrap"><table className="flow-grid-table"><thead><tr><th>Ticker</th><th>Flow</th><th>Premium</th><th>Strike</th><th>Expiration</th><th>Flow / cap</th><th>Contracts</th><th>Vol/OI</th><th>Observed</th><th>Source</th></tr></thead><tbody>{events.map((e:any)=>{const d=e.data||{},cap=d.market_cap||0,p=d.premium||0;return <tr key={key(e)}><td><strong>{e.symbol}</strong></td><td><span className={`flow-signal ${bias(d)}`}>{signal(d)}</span></td><td><strong>{money(p)}</strong></td><td>{d.strike==null?"—":`$${Number(d.strike).toFixed(2)}`}</td><td>{d.expiration||"—"}</td><td>{p&&cap?`${(p/cap*10000).toFixed(2)} bps`:"—"}</td><td>{d.contracts?.toLocaleString?.()||"—"}</td><td>{d.volume_oi_ratio==null?"—":`${Number(d.volume_oi_ratio).toFixed(2)}x`}</td><td>{e.occurred_at?new Date(e.occurred_at).toLocaleString():"—"}</td><td>{e.source_url?<a href={e.source_url} target="_blank" rel="noreferrer">Open ↗</a>:"—"}</td></tr>})}</tbody></table></div></div>}
 {tab==="Relative Flow"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><div><span className="eyebrow">Small-cap sensitivity</span><strong>Premium relative to market capitalization</strong></div><b>▾</b></summary><div className="relative-flow-grid">{relative.map((r:any)=><article key={r.symbol}><div><strong>{r.symbol}</strong><span>{r.unique_contracts} contracts · {r.events} observations</span></div><b>{r.flow_to_market_cap==null?"—":`${(r.flow_to_market_cap*10000).toFixed(2)} bps`}</b><span>{money(r.total_premium)} total</span><small className={(r.net_premium||0)>=0?"positive":"negative"}>Net {money(r.net_premium)}</small><small>{r.flow_to_daily_dollar_volume==null?"ADV ratio —":`${(r.flow_to_daily_dollar_volume*100).toFixed(2)}% of daily $ volume proxy`}</small></article>)}</div></details></div>}
 {tab==="Persistence"&&<div className="v3-stack"><div className="card"><div className="section-head"><div><span className="eyebrow">Repeat activity</span><h3>1h / 24h / 72h premium persistence</h3></div></div><div className="persistence-grid">{relative.map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>1H <b>{money(r.premium_1h)}</b></span><span>24H <b>{money(r.premium_24h)}</b></span><span>72H <b>{money(r.premium_72h)}</b></span><small>{r.unique_contracts} unique contracts</small></div>)}</div></div></div>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Interpretation & deduplication</strong><b>▾</b></summary><p>Green = call buys or put sells. Red = call sells or put buys. Public unusual-flow rows may represent aggregated contract activity, so the app collapses repeated observations by ticker + option type + strike + expiration and keeps the more complete aggregate.</p></details><details className="card methodology-dropdown" open><summary><strong>Relative-size methodology</strong><b>▾</b></summary><p>{analytics?.methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Data reuse</strong><b>▾</b></summary><p>Market cap and underlying price are filled from the shared Markets/fundamentals cache when the flow provider omits them. This avoids duplicate provider requests.</p></details></div>}
 </>}</section>
}
