"use client";
import {useMemo,useState} from "react";

type EventData={side?:string|null;strike?:number|null;expiration?:string|null;premium?:number|null;contracts?:number|null;volume?:number|null;open_interest?:number|null;volume_oi_ratio?:number|null;aggression?:string|null;market_cap?:number|null;underlying_price?:number|null};
type Event={id?:number;event_id?:string|number|null;symbol:string;provider?:string;outlier_score?:number|null;significance_score?:number|null;direction?:string;direction_confidence?:number|null;analysis_reasons?:string[];source_url?:string;occurred_at?:string|null;data?:EventData};
type Market={market_cap?:number|null;price?:number|null};
type SortKey="significance"|"size"|"ticker"|"purchase_date"|"expiration_date"|"relative_size";
type WindowKey="today"|"24h"|"72h"|"7d"|"all";
const money=(v:number|null|undefined)=>v==null?"—":v>=1e9?`$${(v/1e9).toFixed(2)}B`:v>=1e6?`$${(v/1e6).toFixed(2)}M`:v>=1e3?`$${(v/1e3).toFixed(0)}K`:`$${v.toFixed(0)}`;
const num=(v:number|null|undefined)=>v==null?"—":Math.round(v).toLocaleString();
const dateValue=(v:string|null|undefined)=>{const t=v?Date.parse(v):NaN;return Number.isFinite(t)?t:0};
function contractKey(e:Event){const d=e.data||{};return [e.symbol,d.side||"?",d.strike??"?",d.expiration||"?"].join("|")}
function dedupeEvents(rows:Event[]){const m=new Map<string,Event>();for(const e of rows){const k=contractKey(e),old=m.get(k),os=old?.significance_score||old?.outlier_score||0,ns=e.significance_score||e.outlier_score||0;if(!old||ns>=os||dateValue(e.occurred_at)>dateValue(old.occurred_at))m.set(k,e)}return [...m.values()]}
function execution(v:string|null|undefined){const s=(v||"").toLowerCase();if(s.includes("buy")||s.includes("ask")||s.includes("lift"))return"buy";if(s.includes("sell")||s.includes("bid")||s.includes("hit"))return"sell";return s||"unknown"}
function fallbackSignalClass(e:Event){const side=(e.data?.side||"").toLowerCase(),ex=execution(e.data?.aggression);if((side==="call"&&ex==="buy")||(side==="put"&&ex==="sell"))return"positive";if((side==="call"&&ex==="sell")||(side==="put"&&ex==="buy"))return"negative";return"neutral"}
function signalClass(e:Event){if(e.direction==="bullish")return"positive";if(e.direction==="bearish")return"negative";return fallbackSignalClass(e)}
function signalText(e:Event){if(e.direction&&e.direction!=="ambiguous")return e.direction.toUpperCase();const side=(e.data?.side||"option").toLowerCase(),ex=execution(e.data?.aggression);return `${ex==="unknown"?"—":ex.toUpperCase()} ${side.toUpperCase()}`}
function expiryDate(v?:string|null){if(!v)return null;const d=new Date(`${String(v).slice(0,10)}T23:59:59Z`);return Number.isNaN(d.getTime())?null:d}
function isExpired(e:Event){const d=expiryDate(e.data?.expiration);return !!d&&d.getTime()<Date.now()}
function inWindow(e:Event,w:WindowKey){if(w==="all")return true;const t=dateValue(e.occurred_at);if(!t)return false;const now=Date.now();if(w==="today"){const d=new Date(t),n=new Date(now);return d.getUTCFullYear()===n.getUTCFullYear()&&d.getUTCMonth()===n.getUTCMonth()&&d.getUTCDate()===n.getUTCDate()}const hours=w==="24h"?24:w==="72h"?72:168;return now-t<=hours*3600000}
function ageLabel(v?:string|null){const t=dateValue(v);if(!t)return"age unavailable";const h=Math.max(0,(Date.now()-t)/3600000);return h<1?`${Math.round(h*60)}m old`:h<24?`${h.toFixed(1)}h old`:`${(h/24).toFixed(1)}d old`}

export default function LargeFlow({data,loading,error,onRefresh,market}:{data:any;loading:boolean;error:string;onRefresh:()=>void;market:Record<string,Market>}){const[symbol,setSymbol]=useState(""),[view,setView]=useState<"cards"|"grid">("grid"),[sortKey,setSortKey]=useState<SortKey>("significance"),[sortDir,setSortDir]=useState<"asc"|"desc">("desc"),[contractView,setContractView]=useState<"active"|"expired"|"all">("active"),[windowKey,setWindowKey]=useState<WindowKey>("72h");const provider=data?.provider||"SquawkFlow",usage=data?.usage||{},note=data?.live_error||data?.note||"",analysis=data?.analysis||{};
 const events=useMemo<Event[]>(()=>{const raw=dedupeEvents((data?.events||[]) as Event[]);return raw.filter(e=>!symbol.trim()||e.symbol===symbol.trim().toUpperCase()).filter(e=>contractView==="all"||contractView==="expired"?contractView==="all"||isExpired(e):!isExpired(e)).filter(e=>inWindow(e,windowKey)).map(e=>({...e,data:{...(e.data||{}),market_cap:e.data?.market_cap||market[e.symbol]?.market_cap||null,underlying_price:e.data?.underlying_price||market[e.symbol]?.price||null}}))},[data,market,symbol,contractView,windowKey]);
 const relativeSize=(e:Event)=>{const p=e.data?.premium||0,cap=e.data?.market_cap||0;return p>0&&cap>0?p/cap:0};const relativeLabel=(e:Event)=>{const r=relativeSize(e);if(!r)return"—";const bps=r*10000;return bps>=1?`${bps.toFixed(2)} bps`:`${(r*100).toFixed(4)}%`};
 const sortedEvents=useMemo(()=>[...events].sort((a,b)=>{let av:any,bv:any;if(sortKey==="significance"){av=a.significance_score||a.outlier_score||0;bv=b.significance_score||b.outlier_score||0}else if(sortKey==="size"){av=a.data?.premium||0;bv=b.data?.premium||0}else if(sortKey==="ticker"){av=a.symbol;bv=b.symbol}else if(sortKey==="purchase_date"){av=dateValue(a.occurred_at);bv=dateValue(b.occurred_at)}else if(sortKey==="expiration_date"){av=dateValue(a.data?.expiration);bv=dateValue(b.data?.expiration)}else{av=relativeSize(a);bv=relativeSize(b)}const cmp=typeof av==="string"?av.localeCompare(bv):av-bv;return sortDir==="asc"?cmp:-cmp}),[events,sortKey,sortDir]);
 function changeSort(next:SortKey){if(next===sortKey)setSortDir(d=>d==="asc"?"desc":"asc");else{setSortKey(next);setSortDir(next==="ticker"?"asc":"desc")}}const arrow=(key:SortKey)=>sortKey===key?(sortDir==="asc"?" ↑":" ↓"):"";const stats=useMemo(()=>({calls:events.filter(e=>e.data?.side==="call").length,puts:events.filter(e=>e.data?.side==="put").length,total:events.reduce((a,e)=>a+(e.data?.premium||0),0),high:events.filter(e=>(e.significance_score||0)>=65).length}),[events]);
 return <section className="tab-panel flow-panel"><div className="card reveal-card section-head"><div><span className="eyebrow">Unusual options intelligence</span><h2>Large Flow</h2><p className="muted">Default view shows active contracts observed in the last 72 hours. Expired flow remains available only when intentionally selected.</p></div><button className="btn" disabled={loading} onClick={onRefresh}>{loading?"Refreshing…":"Refresh"}</button></div><div className="flow-summary-grid"><article className="card stat-card"><span>Visible contracts</span><strong>{events.length}</strong></article><article className="card stat-card"><span>High significance</span><strong>{stats.high}</strong></article><article className="card stat-card"><span>Calls / puts</span><strong>{stats.calls} / {stats.puts}</strong></article><article className="card stat-card"><span>Observed premium</span><strong>{money(stats.total)}</strong></article></div>
 <div className="card reveal-card flow-toolbar"><div><strong>{provider}</strong><p className="muted">{usage.requests_remaining!=null?`${usage.requests_remaining} anonymous requests remaining this hour`:"Backend caching minimizes repeated provider requests."} {analysis.method?`Analysis: ${analysis.method}.`:""}</p></div><div className="flow-filter"><label>Ticker<input className="search" value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="All tickers"/></label><button className="btn" onClick={()=>setSymbol("")}>Clear</button></div></div>
 <div className="card reveal-card flow-view-controls"><div className="view-toggle" role="group" aria-label="Contract status">{(["active","expired","all"] as const).map(x=><button key={x} aria-pressed={contractView===x} className={`toggle ${contractView===x?"active":""}`} onClick={()=>setContractView(x)}>{x==="active"?"Active only":x==="expired"?"Expired":"All contracts"}</button>)}</div><div className="view-toggle" role="group" aria-label="Observation window">{(["today","24h","72h","7d","all"] as WindowKey[]).map(x=><button key={x} aria-pressed={windowKey===x} className={`toggle ${windowKey===x?"active":""}`} onClick={()=>setWindowKey(x)}>{x==="all"?"All history":x}</button>)}</div><div className="view-toggle"><button className={`toggle ${view==="grid"?"active":""}`} onClick={()=>setView("grid")}>Grid</button><button className={`toggle ${view==="cards"?"active":""}`} onClick={()=>setView("cards")}>Cards</button></div></div>
 {error&&<div className="error-state" role="alert"><div><strong>Large Flow unavailable</strong><p>{error}</p></div><button className="btn" onClick={onRefresh}>Retry</button></div>}{note&&<div className="card flow-note"><strong>Feed note</strong><p className="muted">{note}</p></div>}{!loading&&!error&&!events.length&&<div className="card"><p className="muted">No flow observations matched the current contract status, time window, and ticker filters.</p></div>}
 <div className="card flow-sort-controls"><span className="muted">Sort</span>{([["significance","Significance"],["size","Size"],["relative_size","Flow / Mkt Cap"],["ticker","Ticker"],["purchase_date","Observed"],["expiration_date","Expiration"]] as [SortKey,string][]).map(([k,label])=><button key={k} className={`toggle ${sortKey===k?"active":""}`} onClick={()=>changeSort(k)}>{label}{arrow(k)}</button>)}</div>
 {view==="grid"?<div className="card flow-grid-wrap"><table className="flow-grid-table"><thead><tr><th>Ticker</th><th>Direction</th><th>Significance</th><th>Size</th><th>Strike</th><th>Expiration</th><th>Flow / cap</th><th>Vol/OI</th><th>Observed</th><th>Age</th><th>Source</th></tr></thead><tbody>{sortedEvents.map(e=>{const d=e.data||{};return <tr key={contractKey(e)} className={isExpired(e)?"stale-row":""}><td><strong>{e.symbol}</strong></td><td><span className={`flow-signal ${signalClass(e)}`}>{signalText(e)}</span></td><td>{e.significance_score==null?"—":e.significance_score.toFixed(1)}</td><td>{money(d.premium)}</td><td>{d.strike==null?"—":`$${d.strike.toFixed(2)}`}</td><td>{d.expiration||"—"}{isExpired(e)&&<small className="data-badge stale">EXPIRED</small>}</td><td>{relativeLabel(e)}</td><td>{d.volume_oi_ratio==null?"—":`${d.volume_oi_ratio.toFixed(2)}x`}</td><td>{e.occurred_at?new Date(e.occurred_at).toLocaleString():"—"}</td><td>{ageLabel(e.occurred_at)}</td><td>{e.source_url?<a href={e.source_url} target="_blank" rel="noreferrer">Open ↗</a>:"—"}</td></tr>})}</tbody></table></div>:<div className="flow-event-grid">{sortedEvents.map(e=>{const d=e.data||{};return <article className="card flow-event" key={contractKey(e)}><div className="flow-event-head"><div><span className={`flow-signal ${signalClass(e)}`}>{signalText(e)}</span><strong>{e.symbol}</strong>{isExpired(e)&&<span className="data-badge stale">EXPIRED</span>}</div><span>Significance {e.significance_score==null?"—":e.significance_score.toFixed(1)}</span></div><div className="flow-metrics"><span>Strike <strong>{d.strike==null?"—":`$${d.strike.toFixed(2)}`}</strong></span><span>Expiry <strong>{d.expiration||"—"}</strong></span><span>Premium <strong>{money(d.premium)}</strong></span><span>Flow / cap <strong>{relativeLabel(e)}</strong></span><span>Contracts <strong>{num(d.contracts)}</strong></span><span>Vol/OI <strong>{d.volume_oi_ratio==null?"—":`${d.volume_oi_ratio.toFixed(2)}x`}</strong></span></div><div className="flow-event-foot"><span>{ageLabel(e.occurred_at)}</span>{e.source_url&&<a href={e.source_url} target="_blank" rel="noreferrer">Source ↗</a>}</div></article>})}</div>}
 <div className="card flow-disclaimer"><strong>Interpretation rule</strong><p className="muted">Significance and direction are separate. Expired contracts are historical context and are never presented as current unusual activity in the default view.</p></div></section>}
