"use client";
import {useMemo,useState} from "react";

type EventData={side?:string|null;strike?:number|null;expiration?:string|null;premium?:number|null;contracts?:number|null;volume?:number|null;open_interest?:number|null;volume_oi_ratio?:number|null;aggression?:string|null;direction?:string|null;market_cap?:number|null;underlying_price?:number|null};
type Event={id?:number;event_id?:string|number|null;event_type?:string;symbol:string;provider?:string;outlier_score?:number|null;source_url?:string;occurred_at?:string|null;data?:EventData};
type Market={market_cap?:number|null;price?:number|null};
type SortKey="size"|"ticker"|"purchase_date"|"expiration_date"|"relative_size";
const money=(v:number|null|undefined)=>v==null?"—":v>=1_000_000_000?`$${(v/1_000_000_000).toFixed(2)}B`:v>=1_000_000?`$${(v/1_000_000).toFixed(2)}M`:v>=1_000?`$${(v/1_000).toFixed(0)}K`:`$${v.toFixed(0)}`;
const num=(v:number|null|undefined)=>v==null?"—":Math.round(v).toLocaleString();
const dateValue=(v:string|null|undefined)=>{const t=v?Date.parse(v):NaN;return Number.isFinite(t)?t:0};
function contractKey(e:Event){const d=e.data||{};return [e.symbol,d.side||"?",d.strike??"?",d.expiration||"?"].join("|")}
function dedupeEvents(rows:Event[]){const m=new Map<string,Event>();for(const e of rows){const k=contractKey(e),old=m.get(k),op=old?.data?.premium||0,np=e.data?.premium||0;if(!old||np>=op||dateValue(e.occurred_at)>dateValue(old.occurred_at))m.set(k,e)}return [...m.values()]}
function execution(v:string|null|undefined){const s=(v||"").toLowerCase();if(s.includes("buy")||s.includes("ask")||s.includes("lift"))return"buy";if(s.includes("sell")||s.includes("bid")||s.includes("hit"))return"sell";return s||"unknown"}
function signalClass(e:Event){const side=(e.data?.side||"").toLowerCase(),ex=execution(e.data?.aggression);if((side==="call"&&ex==="buy")||(side==="put"&&ex==="sell"))return"positive";if((side==="call"&&ex==="sell")||(side==="put"&&ex==="buy"))return"negative";return"neutral"}
function signalText(e:Event){const side=(e.data?.side||"option").toLowerCase(),ex=execution(e.data?.aggression);return `${ex==="unknown"?"—":ex.toUpperCase()} ${side.toUpperCase()}`}

export default function LargeFlow({data,loading,error,onRefresh,market}:{data:any;loading:boolean;error:string;onRefresh:()=>void;market:Record<string,Market>}){
 const[symbol,setSymbol]=useState(""),[view,setView]=useState<"cards"|"grid">("grid"),[sortKey,setSortKey]=useState<SortKey>("size"),[sortDir,setSortDir]=useState<"asc"|"desc">("desc");
 const provider=data?.provider||"SquawkFlow",usage=data?.usage||{},note=data?.live_error||data?.note||"";
 const events=useMemo<Event[]>(()=>{const raw=(data?.events||[]) as Event[];const filtered=dedupeEvents(raw).filter(e=>!symbol.trim()||e.symbol===symbol.trim().toUpperCase());return filtered.map((e:Event):Event=>({...e,data:{...(e.data||{}),market_cap:e.data?.market_cap||market[e.symbol]?.market_cap||null,underlying_price:e.data?.underlying_price||market[e.symbol]?.price||null}}))},[data,market,symbol]);
 const relativeSize=(e:Event)=>{const p=e.data?.premium||0,cap=e.data?.market_cap||0;return p>0&&cap>0?p/cap:0};
 const relativeLabel=(e:Event)=>{const r=relativeSize(e);if(!r)return"—";const bps=r*10000;return bps>=1?`${bps.toFixed(2)} bps`:`${(r*100).toFixed(4)}%`};
 const stats=useMemo(()=>{const calls=events.filter(e=>e.data?.side==="call").length,puts=events.filter(e=>e.data?.side==="put").length,total=events.reduce((a,e)=>a+(e.data?.premium||0),0);return {calls,puts,total}},[events]);
 const sortedEvents=useMemo<Event[]>(()=>[...events].sort((a,b)=>{let av:any,bv:any;if(sortKey==="size"){av=a.data?.premium||0;bv=b.data?.premium||0}else if(sortKey==="ticker"){av=a.symbol||"";bv=b.symbol||""}else if(sortKey==="purchase_date"){av=dateValue(a.occurred_at);bv=dateValue(b.occurred_at)}else if(sortKey==="expiration_date"){av=dateValue(a.data?.expiration);bv=dateValue(b.data?.expiration)}else{av=relativeSize(a);bv=relativeSize(b)}const cmp=typeof av==="string"?av.localeCompare(bv):av-bv;return sortDir==="asc"?cmp:-cmp}),[events,sortKey,sortDir]);
 function changeSort(next:SortKey){if(next===sortKey)setSortDir(d=>d==="asc"?"desc":"asc");else{setSortKey(next);setSortDir(next==="ticker"?"asc":"desc")}}
 const arrow=(key:SortKey)=>sortKey===key?(sortDir==="asc"?" ↑":" ↓"):"";
 return <section className="tab-panel flow-panel">
  <div className="card reveal-card section-head"><div><span className="eyebrow">Unusual options intelligence</span><h2>Large Flow</h2><p className="muted">One shared flow response is reused by this tab and the Markets flag grids. Missing market capitalization is filled from the Markets fundamentals cache rather than triggering a second provider pull.</p></div><button className="btn" disabled={loading} onClick={onRefresh}>{loading?"Refreshing…":"Refresh"}</button></div>
  <div className="flow-summary-grid"><article className="card reveal-card stat-card"><span>Unique contracts</span><strong>{events.length}</strong></article><article className="card reveal-card stat-card"><span>Calls</span><strong>{stats.calls}</strong></article><article className="card reveal-card stat-card"><span>Puts</span><strong>{stats.puts}</strong></article><article className="card reveal-card stat-card"><span>Observed premium</span><strong>{money(stats.total)}</strong></article></div>
  <div className="card reveal-card flow-toolbar"><div><strong>{provider}</strong><p className="muted">{usage.requests_remaining!=null?`${usage.requests_remaining} anonymous requests remaining this hour`:"Backend caching and app-level sharing minimize repeated provider requests."}</p></div><div className="flow-filter"><input className="search" value={symbol} onChange={e=>setSymbol(e.target.value)} placeholder="Filter ticker"/><button className="btn" onClick={()=>setSymbol("")}>Clear</button></div></div>
  <div className="card reveal-card flow-view-controls"><div className="view-toggle"><button className={`toggle ${view==="grid"?"active":""}`} onClick={()=>setView("grid")}>Grid</button><button className={`toggle ${view==="cards"?"active":""}`} onClick={()=>setView("cards")}>Cards</button></div><div className="flow-sort-controls"><span className="muted">Sort</span><button className={`toggle ${sortKey==="size"?"active":""}`} onClick={()=>changeSort("size")}>Size{arrow("size")}</button><button className={`toggle ${sortKey==="relative_size"?"active":""}`} onClick={()=>changeSort("relative_size")}>Flow / Mkt Cap{arrow("relative_size")}</button><button className={`toggle ${sortKey==="ticker"?"active":""}`} onClick={()=>changeSort("ticker")}>Ticker{arrow("ticker")}</button><button className={`toggle ${sortKey==="purchase_date"?"active":""}`} onClick={()=>changeSort("purchase_date")}>Purchase date{arrow("purchase_date")}</button><button className={`toggle ${sortKey==="expiration_date"?"active":""}`} onClick={()=>changeSort("expiration_date")}>Expiration{arrow("expiration_date")}</button></div></div>
  {error&&<div className="error-state reveal-card"><div><strong>Large Flow unavailable</strong><p>{error}</p></div><button className="btn" onClick={onRefresh}>Retry</button></div>}
  {note&&<div className="card reveal-card flow-note"><strong>Feed note</strong><p className="muted">{note}</p></div>}
  {!loading&&!error&&!events.length&&<div className="card reveal-card"><p className="muted">No unusual-options observations matched the current filter.</p></div>}
  {view==="grid"?<div className="card reveal-card flow-grid-wrap"><table className="flow-grid-table"><thead><tr><th><button onClick={()=>changeSort("ticker")}>Ticker{arrow("ticker")}</button></th><th>Flow</th><th><button onClick={()=>changeSort("size")}>Size{arrow("size")}</button></th><th>Strike</th><th><button onClick={()=>changeSort("expiration_date")}>Expiration{arrow("expiration_date")}</button></th><th><button onClick={()=>changeSort("relative_size")}>Flow / cap{arrow("relative_size")}</button></th><th>Mkt cap</th><th>Contracts</th><th>Vol/OI</th><th><button onClick={()=>changeSort("purchase_date")}>Observed</button></th><th>Score</th><th>Source</th></tr></thead><tbody>{sortedEvents.map(e=>{const d:EventData=e.data||{};return <tr key={contractKey(e)}><td><strong>{e.symbol}</strong></td><td><span className={`flow-signal ${signalClass(e)}`}>{signalText(e)}</span></td><td><strong>{money(d.premium)}</strong></td><td>{d.strike==null?"—":`$${d.strike.toFixed(2)}`}</td><td>{d.expiration||"—"}</td><td><strong>{relativeLabel(e)}</strong></td><td>{money(d.market_cap)}</td><td>{num(d.contracts)}</td><td>{d.volume_oi_ratio==null?"—":`${d.volume_oi_ratio.toFixed(2)}x`}</td><td>{e.occurred_at?new Date(e.occurred_at).toLocaleString():"—"}</td><td>{e.outlier_score==null?"—":e.outlier_score.toFixed(1)}</td><td>{e.source_url?<a href={e.source_url} target="_blank" rel="noreferrer">Open ↗</a>:"—"}</td></tr>})}</tbody></table></div>:<div className="flow-event-grid">{sortedEvents.map(e=>{const d:EventData=e.data||{};return <article className="card reveal-card flow-event" key={contractKey(e)}><div className="flow-event-head"><div><span className={`flow-signal ${signalClass(e)}`}>{signalText(e)}</span><strong>{e.symbol}</strong></div><span className="flow-score">Score {e.outlier_score==null?"—":e.outlier_score.toFixed(1)}</span></div><div className="flow-metrics"><span>Strike <strong>{d.strike==null?"—":`$${d.strike.toFixed(2)}`}</strong></span><span>Expiry <strong>{d.expiration||"—"}</strong></span><span>Premium <strong>{money(d.premium)}</strong></span><span>Flow / cap <strong>{relativeLabel(e)}</strong></span><span>Market cap <strong>{money(d.market_cap)}</strong></span><span>Contracts <strong>{num(d.contracts)}</strong></span><span>Vol/OI <strong>{d.volume_oi_ratio==null?"—":`${d.volume_oi_ratio.toFixed(2)}x`}</strong></span><span>Execution <strong>{d.aggression||"—"}</strong></span></div><div className="flow-event-foot"><span>{e.occurred_at?new Date(e.occurred_at).toLocaleString():"Latest observation"}</span>{d.direction&&<span>Provider direction: {d.direction}</span>}{e.source_url&&<a href={e.source_url} target="_blank" rel="noreferrer">Source ↗</a>}</div></article>})}</div>}
  <div className="card reveal-card flow-disclaimer"><strong>Interpretation rule</strong><p className="muted">Green marks call buys and put sells; red marks call sells and put buys. SquawkFlow notes that public unusual-flow rows can represent aggregated contract activity, so the app now deduplicates by underlying contract rather than treating every observation timestamp as a separate purchase.</p></div>
 </section>
}
