"use client";
import {useEffect,useMemo,useState} from "react";
import type {NavigationTarget} from "./navigation-context";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function headers(){const e=typeof window!=="undefined"?localStorage.getItem("dailyReportUserEmail")||"":"",t=typeof window!=="undefined"?localStorage.getItem("dailyReportUserToken")||"":"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
function Reason({r}:{r:any}){return <details className="reason-v3"><summary><span className={`data-badge ${r.reason_type==="news"?"live":"derived"}`}>{r.reason_type==="news"?"CATALYST":"TECHNICAL"}</span><strong>{r.title}</strong><small>{r.confidence||"context"}</small><b>▾</b></summary><div><p>{r.summary||r.inference}</p>{r.evidence?.length>0&&<ul>{r.evidence.filter(Boolean).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}{r.url&&<a className="source-link" href={r.url} target="_blank" rel="noreferrer">Source ↗</a>}</div></details>}
function Bars({rows}:{rows:any[]}){const[metric,setMetric]=useState("seven_day");const config:any={day:["1D","day"],seven_day:["7D","seven_day"],thirty_day:["30D","thirty_day"],rotation_score:["Rotation","rotation_score"]};const key=config[metric][1];const sorted=useMemo(()=>[...rows].filter((r:any)=>r[key]!=null).sort((a:any,b:any)=>Number(b[key])-Number(a[key])),[rows,key]);const max=Math.max(1,...sorted.map((r:any)=>Math.abs(Number(r[key]||0))));return <div className="card macro-bars-card"><div className="section-head"><div><span className="eyebrow">Visual rotation map</span><h3>Macro bar view</h3></div><div className="bar-metric-toggle">{Object.entries(config).map(([k,v]:any)=><button key={k} className={metric===k?"active":""} onClick={()=>setMetric(k)}>{v[0]}</button>)}</div></div><div className="macro-bar-list">{sorted.map((r:any)=>{const v=Number(r[key]||0),w=Math.max(2,Math.abs(v)/max*100);return <div className="macro-bar-row" key={r.symbol}><div className="macro-bar-label"><strong>{r.symbol}</strong><span>{r.name}</span></div><div className="macro-bar-track"><i className={v>=0?"positive-bar":"negative-bar"} style={{width:`${w}%`}}/></div><b className={v>=0?"positive":"negative"}>{metric==="rotation_score"?`${v>=0?"+":""}${v.toFixed(2)}`:pct(v)}</b></div>})}</div><p className="muted small-note">Bars are normalized to the largest absolute move in the selected view. Sign and numeric value remain explicit.</p></div>}

export default function MacroWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[rotation,setRotation]=useState<any>(null),[expanded,setExpanded]=useState<any>(null),[relative,setRelative]=useState<any>(null),[liquidity,setLiquidity]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Overview");
 async function load(){setLoading(true);setError("");try{const[r,e,rs,l]=await Promise.all([api("/api/v1/macro/rotation"),api("/api/v1/macro/expanded"),api("/api/v1/analytics/relative-strength?scope=macro&limit=200"),api("/api/v1/analytics/liquidity")]);setRotation(r);setExpanded(e);setRelative(rs);setLiquidity(l)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);useEffect(()=>{if(navigation?.tab==="Macro"&&navigation.subtab)setTab(navigation.subtab)},[navigation?.nonce]);
 const reasons=useMemo(()=>[...(rotation?.possible_reasons||[]),...(rotation?.technical_reasons||[])],[rotation]);function reasonsFor(s:string){return reasons.filter((r:any)=>r.matched_symbol===s)}
 const tabs=["Overview","Bars","Leadership","Categories","Breadth","Cross-asset","Methodology"];
 return <section className="tab-panel v3-workspace macro-v3"><div className="card suite-hero"><div><span className="eyebrow">Expanded regime & rotation map</span><h2>Macro</h2><p className="muted">Table, bar and category views share the same completed-session data so visual comparison never changes the underlying calculation.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div><div className="subtab-bar">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Macro data unavailable</strong><span>{error}</span></div>}{loading&&!expanded?<div className="suite-skeleton">{Array.from({length:8}).map((_,i)=><span key={i}/>)}</div>:expanded&&<>
 {tab==="Overview"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Tracked groups</span><strong>{expanded.tracking?.available}/{expanded.tracking?.requested}</strong></article><article className="card stat-card"><span>Pending backfill</span><strong>{expanded.tracking?.pending?.length||0}</strong></article><article className="card stat-card"><span>Above 200MA</span><strong>{expanded.breadth?.above_200ma??"—"}%</strong></article><article className="card stat-card"><span>Liquidity stress</span><strong>{liquidity?.stress_score??"—"}/100</strong></article></div><Bars rows={expanded.rows||[]}/></div>}
 {tab==="Bars"&&<Bars rows={expanded.rows||[]}/>} 
 {tab==="Leadership"&&<div className="macro-ranking-v3">{[...(expanded.rows||[])].map((r:any)=><details className="card macro-rank-card" data-security-symbol={r.symbol} key={r.symbol}><summary><div><strong>{r.symbol}</strong><span>{r.name}</span><small>{r.category}</small></div><div className="rank-stats"><span>1D <b className={(r.day||0)>=0?"positive":"negative"}>{pct(r.day)}</b></span><span>7D <b className={(r.seven_day||0)>=0?"positive":"negative"}>{pct(r.seven_day)}</b></span><span>30D <b className={(r.thirty_day||0)>=0?"positive":"negative"}>{pct(r.thirty_day)}</b></span><span>Score <b>{r.rotation_score>=0?"+":""}{r.rotation_score}</b></span></div><b>▾</b></summary><div className="rank-detail">{reasonsFor(r.symbol).length?reasonsFor(r.symbol).map((x:any,i:number)=><Reason r={x} key={i}/>):<p className="muted">No specific catalyst/technical explanation met the current evidence threshold.</p>}</div></details>)}</div>}
 {tab==="Categories"&&<div className="category-accordion">{Object.entries(expanded.groups||{}).map(([category,rows]:any)=><details className="card methodology-dropdown" key={category}><summary><div><strong>{category}</strong><span className="muted">{expanded.categories?.[category]}</span></div><span className="reason-count">{rows.length}</span><b>▾</b></summary><div className="macro-category-grid">{rows.map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>{r.name}</span><b className={r.rotation_score>=0?"positive":"negative"}>{r.rotation_score>=0?"+":""}{r.rotation_score}</b><small>7D {pct(r.seven_day)} · 30D {pct(r.thirty_day)}</small></div>)}</div></details>)}</div>}
 {tab==="Breadth"&&<div className="v3-stack"><div className="card"><h3>Macro-universe breadth</h3><div className="metric-tile-grid">{[["Above 50MA",expanded.breadth?.above_50ma],["Above 100MA",expanded.breadth?.above_100ma],["Above 200MA",expanded.breadth?.above_200ma],["Positive 1D",expanded.breadth?.positive_1d],["Positive 7D",expanded.breadth?.positive_7d],["Near 52W high",expanded.breadth?.near_52w_high],["Near 52W low",expanded.breadth?.near_52w_low]].map(([k,v]:any)=><span key={k}><i>{k}</i><strong>{v==null?"—":`${v}%`}</strong></span>)}</div></div></div>}
 {tab==="Cross-asset"&&<div className="v3-stack"><details className="card methodology-dropdown"><summary><strong>Relative strength vs SPY</strong><span className="muted">30D return spread</span><b>▾</b></summary><div className="relative-grid">{(relative?.rows||[]).slice(0,60).map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>{r.category||"Macro"}</span><b className={(r.vs_spy_30d||0)>=0?"positive":"negative"}>{pct(r.vs_spy_30d)}</b><small>vs QQQ {pct(r.vs_qqq_30d)}</small></div>)}</div></details><details className="card methodology-dropdown"><summary><strong>Credit, dollar & duration stress</strong><span>{liquidity?.stress_score??"—"}/100</span><b>▾</b></summary><div className="mini-grid">{(liquidity?.signals||[]).map((x:any)=><span key={x.label}><strong>{x.label}</strong><b className={x.risk_direction==="worse"?"negative":"positive"}>{pct(x.value)}</b><small>{x.symbol}</small></span>)}</div></details></div>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown"><summary><strong>Rotation calculation</strong><b>▾</b></summary><p>{rotation?.methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Catalyst & technical explanations</strong><b>▾</b></summary><p>{rotation?.reasoning_methodology}</p></details></div>}
 </>}</section>
}
