"use client";

import {useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
function Loading(){return <div className="suite-skeleton">{Array.from({length:8}).map((_,i)=><span key={i}/>)}</div>}
function Reason({r}:{r:any}){return <details className="reason-v3"><summary><span className={`data-badge ${r.reason_type==="news"?"live":"derived"}`}>{r.reason_type==="news"?"CATALYST":"TECHNICAL"}</span><strong>{r.title}</strong><small>{r.confidence||"context"}</small><b>▾</b></summary><div><p>{r.summary||r.inference}</p>{r.inference&&r.inference!==r.summary&&<p className="muted">{r.inference}</p>}{r.evidence?.length>0&&<ul>{r.evidence.filter(Boolean).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}<div className="metric-links">{r.url&&<a className="source-link" href={r.url} target="_blank" rel="noreferrer">Source ↗</a>}</div></div></details>}

export default function MacroWorkspaceV3(){
 const[rotation,setRotation]=useState<any>(null),[expanded,setExpanded]=useState<any>(null),[relative,setRelative]=useState<any>(null),[liquidity,setLiquidity]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Overview");
 async function load(){setLoading(true);setError("");try{const[r,e,rs,l]=await Promise.all([api("/api/v1/macro/rotation"),api("/api/v1/macro/expanded"),api("/api/v1/analytics/relative-strength?scope=macro&limit=200"),api("/api/v1/analytics/liquidity")]);setRotation(r);setExpanded(e);setRelative(rs);setLiquidity(l)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const reasons=useMemo(()=>[...(rotation?.possible_reasons||[]),...(rotation?.technical_reasons||[])],[rotation]);
 function reasonsFor(s:string){return reasons.filter((r:any)=>r.matched_symbol===s)}
 const tabs=["Overview","Leadership","Categories","Breadth","Cross-asset","Methodology"];
 return <section className="tab-panel v3-workspace macro-v3"><div className="card reveal-card suite-hero"><div><span className="eyebrow">Expanded regime & rotation map</span><h2>Macro</h2><p className="muted">Broader sectors, factors, global markets, rates, credit, commodities and thematic groups—organized into drill-down views instead of one long page.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div>
  <div className="subtab-bar">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
  {error&&<div className="suite-error"><strong>Macro data unavailable</strong><span>{error}</span><button className="btn" onClick={load}>Retry</button></div>}{loading&&!expanded?<Loading/>:expanded&&<>
   {tab==="Overview"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Tracked groups</span><strong>{expanded.tracking?.available}/{expanded.tracking?.requested}</strong></article><article className="card stat-card"><span>Pending backfill</span><strong>{expanded.tracking?.pending?.length||0}</strong></article><article className="card stat-card"><span>Above 200MA</span><strong>{expanded.breadth?.above_200ma??"—"}%</strong></article><article className="card stat-card"><span>Liquidity stress</span><strong>{liquidity?.stress_score??"—"}/100</strong></article></div>
    <div className="suite-two"><LeaderList title="Leadership" rows={rotation?.leaders||[]} reasonsFor={reasonsFor}/><LeaderList title="Weakness" rows={rotation?.laggards||[]} reasonsFor={reasonsFor} weakness/></div>
    {expanded.tracking?.pending?.length>0&&<details className="card methodology-dropdown"><summary><strong>Background history backfill</strong><span className="muted">{expanded.tracking.pending.length} pending</span><b>▾</b></summary><p>New macro ETFs are using the existing queued Twelve Data history path. With the market closed, completed-session data is backfilled at provider-safe spacing; all comparison windows remain anchored to completed daily sessions.</p><div className="chip-row">{expanded.tracking.pending.map((s:string)=><span key={s}>{s}</span>)}</div></details>}
   </div>}
   {tab==="Leadership"&&<div className="macro-ranking-v3">{[...(expanded.rows||[])].map((r:any)=><details className="card macro-rank-card" key={r.symbol}><summary><div><strong>{r.symbol}</strong><span>{r.name}</span><small>{r.category}</small></div><div className="rank-stats"><span>1D <b className={(r.day||0)>=0?"positive":"negative"}>{pct(r.day)}</b></span><span>7D <b className={(r.seven_day||0)>=0?"positive":"negative"}>{pct(r.seven_day)}</b></span><span>30D <b className={(r.thirty_day||0)>=0?"positive":"negative"}>{pct(r.thirty_day)}</b></span><span>Score <b>{r.rotation_score>=0?"+":""}{r.rotation_score}</b></span></div><b>▾</b></summary><div className="rank-detail"><p className="muted">Relative volume {r.relative_volume==null?"—":`${Number(r.relative_volume).toFixed(2)}x`} · data {r.as_of||"stored"}</p>{reasonsFor(r.symbol).length?reasonsFor(r.symbol).map((x:any,i:number)=><Reason r={x} key={`${x.reason_type}-${i}`}/>):<p className="muted">No specific catalyst/technical explanation met the current evidence threshold.</p>}</div></details>)}</div>}
   {tab==="Categories"&&<div className="category-accordion">{Object.entries(expanded.groups||{}).map(([category,rows]:any)=><details className="card methodology-dropdown" key={category}><summary><div><strong>{category}</strong><span className="muted">{expanded.categories?.[category]}</span></div><span className="reason-count">{rows.length}</span><b>▾</b></summary><div className="macro-category-grid">{rows.map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>{r.name}</span><b className={r.rotation_score>=0?"positive":"negative"}>{r.rotation_score>=0?"+":""}{r.rotation_score}</b><small>7D {pct(r.seven_day)} · 30D {pct(r.thirty_day)}</small></div>)}</div></details>)}</div>}
   {tab==="Breadth"&&<div className="v3-stack"><div className="card"><h3>Macro-universe breadth</h3><div className="metric-tile-grid">{[["Above 50MA",expanded.breadth?.above_50ma],["Above 100MA",expanded.breadth?.above_100ma],["Above 200MA",expanded.breadth?.above_200ma],["Positive 1D",expanded.breadth?.positive_1d],["Positive 7D",expanded.breadth?.positive_7d],["Near 52W high",expanded.breadth?.near_52w_high],["Near 52W low",expanded.breadth?.near_52w_low]].map(([k,v]:any)=><span key={k}><i>{k}</i><strong>{v==null?"—":`${v}%`}</strong></span>)}</div></div><details className="card methodology-dropdown"><summary><strong>Breadth methodology</strong><b>▾</b></summary><p>{expanded.breadth?.methodology}</p></details></div>}
   {tab==="Cross-asset"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Relative strength vs SPY</strong><span className="muted">30D return spread</span><b>▾</b></summary><div className="relative-grid">{(relative?.rows||[]).slice(0,40).map((r:any)=><div key={r.symbol}><strong>{r.symbol}</strong><span>{r.category||"Macro"}</span><b className={(r.vs_spy_30d||0)>=0?"positive":"negative"}>{pct(r.vs_spy_30d)}</b><small>vs QQQ {pct(r.vs_qqq_30d)}</small></div>)}</div><p className="muted">{relative?.methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Credit, dollar & duration stress</strong><span>{liquidity?.stress_score??"—"}/100</span><b>▾</b></summary><div className="mini-grid">{(liquidity?.signals||[]).map((x:any)=><span key={x.label}><strong>{x.label}</strong><b className={x.risk_direction==="worse"?"negative":"positive"}>{pct(x.value)}</b><small>{x.symbol}</small></span>)}</div><p className="muted">{liquidity?.methodology}</p></details></div>}
   {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Rotation calculation</strong><b>▾</b></summary><p>{rotation?.methodology}</p></details><details className="card methodology-dropdown" open><summary><strong>Catalyst & technical explanations</strong><b>▾</b></summary><p>{rotation?.reasoning_methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Tracked categories</strong><b>▾</b></summary>{Object.entries(expanded.categories||{}).map(([k,v]:any)=><p key={k}><b>{k}:</b> {v}</p>)}</details></div>}
  </>}
 </section>
}

function LeaderList({title,rows,reasonsFor,weakness=false}:{title:string;rows:any[];reasonsFor:(s:string)=>any[];weakness?:boolean}){return <div className="card"><div className="section-head"><div><span className="eyebrow">{weakness?"Laggards":"Leaders"}</span><h3>{title}</h3></div><span className="muted">score at right</span></div><div className="compact-list">{rows.map(r=><details className="leader-detail" key={r.symbol}><summary><div><strong>{r.symbol}</strong><span>{r.name}</span></div><b className={r.rotation_score>=0?"positive":"negative"}>{r.rotation_score>=0?"+":""}{r.rotation_score}</b><i>▾</i></summary><div><div className="leader-stat-grid"><span>1D <b>{pct(r.day_percent)}</b></span><span>7D <b>{pct(r.seven_day_percent)}</b></span><span>30D <b>{pct(r.thirty_day_percent)}</b></span><span>Rel vol <b>{r.relative_volume==null?"—":`${Number(r.relative_volume).toFixed(2)}x`}</b></span></div>{reasonsFor(r.symbol).map((x:any,i:number)=><Reason r={x} key={i}/>)}</div></details>)}</div></div>}
