"use client";
import {useEffect,useMemo,useState} from "react";
import type {NavigationTarget} from "./navigation-context";

const API="/backend";
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;
function Reason({r}:{r:any}){return <details className="reason-v3"><summary><span className={`data-badge ${r.reason_type==="news"?"live":"derived"}`}>{r.reason_type==="news"?"NEWS":"TA"}</span><strong>{r.title}</strong><small>{r.confidence||"context"}</small><b>▾</b></summary><div><p>{r.summary||r.inference}</p>{r.evidence?.length>0&&<ul>{r.evidence.filter(Boolean).map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}{r.url&&<a className="source-link" href={r.url} target="_blank" rel="noreferrer">Source ↗</a>}</div></details>}
function Bars({rows,onSelect}:{rows:any[];onSelect:(symbol:string)=>void}){const[metric,setMetric]=useState("seven_day");const config:any={day:["1D","day"],seven_day:["7D","seven_day"],thirty_day:["30D","thirty_day"],rotation_score:["Rotation","rotation_score"]};const key=config[metric][1];const sorted=useMemo(()=>[...rows].filter((r:any)=>r[key]!=null).sort((a:any,b:any)=>Number(b[key])-Number(a[key])),[rows,key]);const max=Math.max(1,...sorted.map((r:any)=>Math.abs(Number(r[key]||0))));return <div className="card macro-bars-card"><div className="section-head"><div><span className="eyebrow">Visual rotation map</span><h3>Macro bar view</h3><p className="muted small-note">Select a ticker/bar to open its detailed Leadership view.</p></div><div className="bar-metric-toggle">{Object.entries(config).map(([k,v]:any)=><button key={k} className={metric===k?"active":""} onClick={()=>setMetric(k)}>{v[0]}</button>)}</div></div><div className="macro-bar-list card-scroll-region">{sorted.map((r:any)=>{const v=Number(r[key]||0),w=Math.max(2,Math.abs(v)/max*100);return <button className="macro-bar-row clickable-bar" key={r.symbol} data-security-symbol={r.symbol} onClick={()=>onSelect(r.symbol)}><div className="macro-bar-label"><strong>{r.symbol}</strong><span>{r.name}</span></div><div className="macro-bar-track"><i className={v>=0?"positive-bar":"negative-bar"} style={{width:`${w}%`}}/></div><b className={v>=0?"positive":"negative"}>{metric==="rotation_score"?`${v>=0?"+":""}${v.toFixed(2)}`:pct(v)}</b></button>})}</div></div>}
function PossibleReasons({rotation,onSelect}:{rotation:any;onSelect:(symbol:string)=>void}){const news=rotation?.possible_reasons||[],ta=rotation?.technical_reasons||[],leaders=rotation?.leaders||[],laggards=rotation?.laggards||[],lead=leaders[0],lag=laggards[0];const leadReasons=[...news,...ta].filter((r:any)=>r.matched_symbol===lead?.symbol).slice(0,2),lagReasons=[...news,...ta].filter((r:any)=>r.matched_symbol===lag?.symbol).slice(0,2);const sentence=[lead?`${lead.symbol} is the strongest current rotation leader${lead.rotation_score!=null?` at ${Number(lead.rotation_score).toFixed(2)}`:""}.`:null,lag?`${lag.symbol} is the weakest tracked group${lag.rotation_score!=null?` at ${Number(lag.rotation_score).toFixed(2)}`:""}.`:null,news.length?`${news.length} linked news explanation${news.length===1?"":"s"} met the matching threshold.`:"No linked news explanation currently meets the matching threshold.",ta.length?`${ta.length} technical explanation${ta.length===1?"":"s"} are available from stored market data.`:"No strong technical explanation is currently available."].filter(Boolean).join(" ");return <div className="card macro-possible-reasons"><div className="section-head"><div><span className="eyebrow">Possible reasons</span><h3>Why capital may be rotating</h3></div><span className="reason-count">{news.length} news · {ta.length} TA</span></div><p className="macro-written-summary">{sentence}</p><div className="intel-two">{lead&&<div><button className="reason-jump" onClick={()=>onSelect(lead.symbol)}><strong>{lead.symbol} leadership</strong><span>Open detailed Leadership view →</span></button>{leadReasons.length?leadReasons.map((r:any,i:number)=><Reason key={`l-${i}`} r={r}/>):<p className="muted">No high-confidence explanation is attached to this leader yet.</p>}</div>}{lag&&<div><button className="reason-jump" onClick={()=>onSelect(lag.symbol)}><strong>{lag.symbol} weakness</strong><span>Open detailed Leadership view →</span></button>{lagReasons.length?lagReasons.map((r:any,i:number)=><Reason key={`w-${i}`} r={r}/>):<p className="muted">No high-confidence explanation is attached to this laggard yet.</p>}</div>}</div>{rotation?.reasoning_methodology&&<p className="muted small-note">{rotation.reasoning_methodology}</p>}</div>}

export default function MacroWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[rotation,setRotation]=useState<any>(null),[expanded,setExpanded]=useState<any>(null),[relative,setRelative]=useState<any>(null),[liquidity,setLiquidity]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Overview"),[focus,setFocus]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const[r,e,rs,l]=await Promise.all([api("/api/v1/macro/rotation"),api("/api/v1/macro/expanded"),api("/api/v1/analytics/relative-strength?scope=macro&limit=200"),api("/api/v1/analytics/liquidity")]);setRotation(r);setExpanded(e);setRelative(rs);setLiquidity(l)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);useEffect(()=>{if(navigation?.tab==="Macro"&&navigation.subtab)setTab(navigation.subtab)},[navigation?.nonce]);
 const reasons=useMemo(()=>[...(rotation?.possible_reasons||[]),...(rotation?.technical_reasons||[])],[rotation]);function reasonsFor(s:string){return reasons.filter((r:any)=>r.matched_symbol===s)}function openLeadership(symbol:string){setFocus(symbol);setTab("Leadership");requestAnimationFrame(()=>setTimeout(()=>document.querySelector<HTMLElement>(`[data-leadership-symbol="${symbol}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}),80))}
 const tabs=["Overview","Bars","Leadership","Categories","Breadth","Cross-asset","Methodology"],leadershipRows=useMemo(()=>{const rows=[...(expanded?.rows||[])];if(focus){const i=rows.findIndex((r:any)=>r.symbol===focus);if(i>0)rows.unshift(...rows.splice(i,1))}return rows},[expanded,focus]);
 return <section className="tab-panel v3-workspace macro-v3"><div className="card suite-hero"><div><span className="eyebrow">Expanded regime & rotation map</span><h2>Macro</h2><p className="muted">Bars, leadership and explanation views share the same completed-session data. Possible reasons combine linked world news with stored technical evidence and remain explicitly inferential.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div><div className="subtab-bar">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Macro data unavailable</strong><span>{error}</span></div>}{loading&&!expanded?<div className="suite-skeleton">{Array.from({length:8}).map((_,i)=><span key={i}/>)}</div>:expanded&&<>
 {tab==="Overview"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Tracked groups</span><strong>{expanded.tracking?.available}/{expanded.tracking?.requested}</strong></article><article className="card stat-card"><span>Pending backfill</span><strong>{expanded.tracking?.pending?.length||0}</strong></article><article className="card stat-card"><span>Above 200MA</span><strong>{expanded.breadth?.above_200ma??"—"}%</strong></article><article className="card stat-card"><span>Liquidity stress</span><strong>{liquidity?.stress_score??"—"}/100</strong></article></div><Bars rows={expanded.rows||[]} onSelect={openLeadership}/><PossibleReasons rotation={rotation} onSelect={openLeadership}/></div>}
 {tab==="Bars"&&<div className="v3-stack"><Bars rows={expanded.rows||[]} onSelect={openLeadership}/><PossibleReasons rotation={rotation} onSelect={openLeadership}/></div>}
 {tab==="Leadership"&&<div className="macro-ranking-v3">{leadershipRows.map((r:any)=><details className={`card macro-rank-card ${focus===r.symbol?"focused-rank":""}`} data-security-symbol={r.symbol} data-leadership-symbol={r.symbol} key={r.symbol} open={focus===r.symbol||undefined}><summary><div><strong>{r.symbol}</strong><span>{r.name}</span><small>{r.category}</small></div><div className="rank-stats"><span>1D <b className={(r.day||0)>=0?"positive":"negative"}>{pct(r.day)}</b></span><span>7D <b className={(r.seven_day||0)>=0?"positive":"negative"}>{pct(r.seven_day)}</b></span><span>30D <b className={(r.thirty_day||0)>=0?"positive":"negative"}>{pct(r.thirty_day)}</b></span><span>Score <b>{r.rotation_score>=0?"+":""}{r.rotation_score}</b></span></div><b>▾</b></summary><div className="rank-detail card-scroll-region">{reasonsFor(r.symbol).length?reasonsFor(r.symbol).map((x:any,i:number)=><Reason r={x} key={i}/>):<p className="muted">No specific catalyst/technical explanation met the current evidence threshold.</p>}</div></details>)}</div>}
 {tab==="Categories"&&<div className="category-accordion">{Object.entries(expanded.groups||{}).map(([category,rows]:any)=><details className="card methodology-dropdown" key={category}><summary><div><strong>{category}</strong><span className="muted">{expanded.categories?.[category]}</span></div><span className="reason-count">{rows.length}</span><b>▾</b></summary><div className="macro-category-grid card-scroll-region">{rows.map((r:any)=><button key={r.symbol} data-security-symbol={r.symbol} onClick={()=>openLeadership(r.symbol)}><strong>{r.symbol}</strong><span>{r.name}</span><b className={r.rotation_score>=0?"positive":"negative"}>{r.rotation_score>=0?"+":""}{r.rotation_score}</b><small>7D {pct(r.seven_day)} · 30D {pct(r.thirty_day)}</small></button>)}</div></details>)}</div>}
 {tab==="Breadth"&&<div className="v3-stack"><div className="card"><h3>Macro-universe breadth</h3><div className="metric-tile-grid">{[["Above 50MA",expanded.breadth?.above_50ma],["Above 100MA",expanded.breadth?.above_100ma],["Above 200MA",expanded.breadth?.above_200ma],["Positive 1D",expanded.breadth?.positive_1d],["Positive 7D",expanded.breadth?.positive_7d],["Near 52W high",expanded.breadth?.near_52w_high],["Near 52W low",expanded.breadth?.near_52w_low]].map(([k,v]:any)=><span key={k}><i>{k}</i><strong>{v==null?"—":`${v}%`}</strong></span>)}</div></div></div>}
 {tab==="Cross-asset"&&<div className="v3-stack"><details className="card methodology-dropdown"><summary><strong>Relative strength vs SPY</strong><span className="muted">30D return spread</span><b>▾</b></summary><div className="relative-grid card-scroll-region">{(relative?.rows||[]).slice(0,60).map((r:any)=><button key={r.symbol} onClick={()=>openLeadership(r.symbol)}><strong>{r.symbol}</strong><span>{r.category||"Macro"}</span><b className={(r.vs_spy_30d||0)>=0?"positive":"negative"}>{pct(r.vs_spy_30d)}</b><small>vs QQQ {pct(r.vs_qqq_30d)}</small></button>)}</div></details><details className="card methodology-dropdown"><summary><strong>Credit, dollar & duration stress</strong><span>{liquidity?.stress_score??"—"}/100</span><b>▾</b></summary><div className="mini-grid">{(liquidity?.signals||[]).map((x:any)=><span key={x.label}><strong>{x.label}</strong><b className={x.risk_direction==="worse"?"negative":"positive"}>{pct(x.value)}</b><small>{x.symbol}</small></span>)}</div></details></div>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown"><summary><strong>Rotation calculation</strong><b>▾</b></summary><p>{rotation?.methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Catalyst & technical explanations</strong><b>▾</b></summary><p>{rotation?.reasoning_methodology}</p><p className="muted">News matches are contextual evidence, not proof of causality. Technical explanations are derived from stored price/volume history.</p></details></div>}
 </>}</section>
}
