"use client";
import {useEffect,useMemo,useState} from "react";
const API="/backend";
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
export default function MacroHistory(){
 const[data,setData]=useState<any>(null),[status,setStatus]=useState("Loading 2026 history...");
 async function load(){setStatus("Loading 2026 history...");try{const r=await fetch(`${API}/api/v1/macro/history?year=2026`,{cache:"no-store",credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);setData(d);setStatus(`${d.data_points||0} historical daily observations · updates each weekday`)}catch(e){setStatus(e instanceof Error?e.message:"History unavailable")}}
 useEffect(()=>{load()},[]);
 const monthly=useMemo(()=>{if(!data?.rotation_timeline)return[];const groups:Record<string,any[]>={};for(const x of data.rotation_timeline){const m=x.date.slice(0,7);(groups[m]??=[]).push(x)}return Object.entries(groups).map(([month,rows])=>{const latest=rows[rows.length-1];const counts:Record<string,number>={};const lagCounts:Record<string,number>={};for(const r of rows){for(const l of r.leaders||[])counts[l.symbol]=(counts[l.symbol]||0)+1;for(const l of r.laggards||[])lagCounts[l.symbol]=(lagCounts[l.symbol]||0)+1}const leader=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];const laggard=Object.entries(lagCounts).sort((a,b)=>b[1]-a[1])[0];return{month,leader:leader?.[0]||"—",leaderDays:leader?.[1]||0,laggard:laggard?.[0]||"—",laggardDays:laggard?.[1]||0,spread:latest?.spread}})},[data]);
 const recent=monthly.slice(-2).reverse(),outliers=(data?.stock_outliers||[]).slice(0,16),significant=(data?.significant_rotation_days||[]).slice(0,12);
 return <>
  <div className="card"><div className="row"><div><h2>2026 Rotation History</h2><p className="muted">{status}</p></div><button className="btn" onClick={load}>Refresh history</button></div><p className="muted">Current month and prior month stay pinned at the top; daily sector snapshots are appended automatically going forward.</p></div>
  {data&&<>
   <div className="grid report-columns">{recent.map((m:any,i:number)=><div className="card" key={m.month}><span className="eyebrow">{i===0?"Current month":"Previous month"}</span><h2>{m.month}</h2><div className="metric-grid"><span>Frequent leader <strong className="positive">{m.leader}</strong></span><span>Leader days <strong className="positive">{m.leaderDays}</strong></span><span>Frequent laggard <strong className="negative">{m.laggard}</strong></span><span>Laggard days <strong className="negative">{m.laggardDays}</strong></span><span>Latest spread <strong className={(m.spread??0)>=0?"positive":"negative"}>{m.spread?.toFixed(2)??"—"}</strong></span></div></div>)}</div>
   <div className="card"><h2>Rotation by Month</h2><div className="comparison-wrap"><table className="comparison-table"><thead><tr><th>Month</th><th>Leader</th><th>Leader days</th><th>Laggard</th><th>Spread</th></tr></thead><tbody>{monthly.map((m:any)=><tr key={m.month}><td>{m.month}</td><td className="positive"><strong>{m.leader}</strong></td><td className="positive">{m.leaderDays}</td><td className="negative"><strong>{m.laggard}</strong></td><td className={(m.spread??0)>=0?"positive":"negative"}>{m.spread?.toFixed(2)??"—"}</td></tr>)}</tbody></table></div></div>
   <div className="card"><h2>Largest Rotation Days</h2><p className="muted">Widest leader/laggard spreads. Macro events within ±2 calendar days are possible catalysts, not asserted causes.</p><div className="outlier-list">{significant.map((r:any)=><div className="outlier-row" key={r.date}><div><strong>{r.date} · spread <span className="positive">{r.spread?.toFixed(2)??"—"}</span></strong><p>Leaders: <span className="positive">{(r.leaders||[]).map((x:any)=>x.symbol).join(", ")}</span> · Laggards: <span className="negative">{(r.laggards||[]).map((x:any)=>x.symbol).join(", ")}</span></p>{(r.possible_catalysts||[]).slice(0,3).map((c:any)=><p key={`${r.date}-${c.title}`}>Possible catalyst: {c.title}{c.distance_days===0?" · same day":` · ${c.distance_days}d away`}</p>)}</div></div>)}</div></div>
   <div className="card"><h2>Stock / Sector Divergences</h2><p className="muted">Large 5-day deviations from mapped sectors/themes.</p><div className="outlier-list">{outliers.map((o:any)=><div className="outlier-row" key={`${o.date}-${o.symbol}`}><div><strong>{o.symbol} vs {o.benchmark}</strong><p>{o.date} · stock <span className={(o.stock_5d_percent??0)>=0?"positive":"negative"}>{pct(o.stock_5d_percent)}</span> · benchmark <span className={(o.benchmark_5d_percent??0)>=0?"positive":"negative"}>{pct(o.benchmark_5d_percent)}</span> · {o.direction}</p>{(o.possible_catalysts||[]).slice(0,2).map((c:any)=><p key={`${o.date}-${o.symbol}-${c.title}`}>Nearby macro event: {c.title}</p>)}</div><span className={o.relative_gap_points>=0?"positive":"negative"}>{o.relative_gap_points>=0?"+":""}{o.relative_gap_points.toFixed(2)} pts</span></div>)}</div></div>
   <div className="card"><h2>Methodology</h2><p className="muted">{data.methodology}</p>{data.catalyst_source?.provider&&<p className="source-line">Catalyst calendar: {data.catalyst_source.provider}{data.catalyst_source.source_url?<> · <a href={data.catalyst_source.source_url} target="_blank" rel="noreferrer">source</a></>:null}</p>}</div>
  </>}
 </>;
}
