"use client";
import {useState} from "react";

type Reason={reason_type?:"news"|"technical";title:string;summary?:string;url?:string;domain?:string;published_at?:string;discovery_source?:string;matched_symbol?:string;matched_group?:string;inference?:string;confidence?:string;match_score?:number;evidence?:string[];move_context?:string};
type Row={symbol:string;name:string;day_percent?:number|null;seven_day_percent?:number|null;thirty_day_percent?:number|null;relative_volume?:number|null;rotation_score:number;as_of?:string|null;source_url?:string};
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;

function ReasonDetail({reason}:{reason:Reason}){
 return <details className="ticker-reason-detail"><summary><span className={`reason-type ${reason.reason_type||"news"}`}>{reason.reason_type==="technical"?"TA":"News"}</span><span>{reason.title}</span><span className={`confidence ${reason.confidence||"low"}`}>{reason.confidence||"low"}</span></summary><div className="ticker-reason-body"><p>{reason.summary||reason.inference}</p>{reason.inference&&reason.inference!==reason.summary&&<p className="muted">{reason.inference}</p>}{reason.evidence?.filter(Boolean).length?<div className="reason-evidence">{reason.evidence.filter(Boolean).map(x=><span key={x}>{x}</span>)}</div>:null}<div className="reason-meta">{reason.domain&&<span>{reason.domain}</span>}{reason.discovery_source&&<span>{reason.discovery_source}</span>}{reason.published_at&&<span>{reason.published_at}</span>}{reason.match_score!=null&&<span>match {reason.match_score.toFixed(0)}</span>}</div>{reason.url&&<a className="source-link" href={reason.url} target="_blank" rel="noreferrer">Open source ↗</a>}</div></details>;
}

function MacroGrid({title,rows,rotation,tone}:{title:string;rows:Row[];rotation:any;tone:"leader"|"laggard"}){
 const[open,setOpen]=useState<string|null>(null);
 const news:Reason[]=rotation?.possible_reasons||[];
 const technical:Reason[]=rotation?.technical_reasons||[];
 return <div className="card reveal-card macro-rank-card"><div className="section-head"><div><span className="eyebrow">{tone==="leader"?"Relative leadership":"Relative weakness"}</span><h2>{title}</h2></div><span className="reason-count">Rotation score</span></div><p className="muted small-note">Right-side score = 25% 1D + 45% 7D + 30% 30D performance, amplified by above-normal relative volume. Click a ticker for catalysts and technical context.</p><div className="macro-rank-grid"><div className="macro-rank-head"><span>Ticker</span><span>1D</span><span>7D</span><span>30D</span><span>Rel Vol</span><span>Score</span></div>{rows.map(r=>{const rn=news.filter(x=>x.matched_symbol===r.symbol),rt=technical.filter(x=>x.matched_symbol===r.symbol),expanded=open===r.symbol;return <div className={`macro-rank-item ${expanded?"expanded":""}`} key={r.symbol}><button className="macro-rank-row" onClick={()=>setOpen(expanded?null:r.symbol)}><span><strong>{r.symbol}</strong><small>{r.name}</small></span><span className={(r.day_percent??0)>=0?"positive":"negative"}>{pct(r.day_percent)}</span><span className={(r.seven_day_percent??0)>=0?"positive":"negative"}>{pct(r.seven_day_percent)}</span><span className={(r.thirty_day_percent??0)>=0?"positive":"negative"}>{pct(r.thirty_day_percent)}</span><span>{r.relative_volume==null?"—":`${r.relative_volume.toFixed(2)}x`}</span><span className={r.rotation_score>=0?"positive":"negative"}>{r.rotation_score>=0?"+":""}{r.rotation_score.toFixed(2)} {expanded?"⌃":"⌄"}</span></button>{expanded&&<div className="macro-rank-details"><div><div className="reason-section-title"><strong>News catalysts</strong><span>{rn.length} matches</span></div>{rn.length?rn.map((x,i)=><ReasonDetail key={`${x.url||x.title}-${i}`} reason={{...x,reason_type:"news"}}/>):<p className="muted empty-reason">No sufficiently strong catalyst match for this ticker.</p>}</div><div><div className="reason-section-title"><strong>Technical analysis</strong><span>{rt.length} signals</span></div>{rt.length?rt.map((x,i)=><ReasonDetail key={`${x.title}-${i}`} reason={{...x,reason_type:"technical"}}/>):<p className="muted empty-reason">No strong technical explanation from the stored snapshot.</p>}</div></div>}</div>})}</div></div>;
}

export function MacroLeadership({rotation}:{rotation:any}){
 return <div className="macro-leadership-layout"><MacroGrid title="Leadership" rows={rotation?.leaders||[]} rotation={rotation} tone="leader"/><MacroGrid title="Weakness / Sources of Capital" rows={rotation?.laggards||[]} rotation={rotation} tone="laggard"/><div className="card reveal-card macro-reasons-card"><div className="section-head"><div><span className="eyebrow">Possible reasons</span><h2>How to read the explanations</h2></div><span className="reason-count">Expandable by ticker</span></div><p className="muted">News catalysts and technical-analysis candidates now live directly under each ranked ticker. Expand a ticker, then expand any individual explanation for its summary, evidence, source metadata, and detailed interpretation.</p>{rotation?.reasoning_methodology&&<p className="reason-methodology">{rotation.reasoning_methodology}</p>}</div></div>;
}
