"use client";
import {Fragment,useState} from "react";
import LoadingRing from "./loading-ring";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
type Market={symbol:string;price:number|null;change_percent:number|null;seven_day_percent:number|null;thirty_day_percent:number|null;ytd_percent:number|null;ma50?:number|null;ma100:number|null;ma200:number|null;price_vs_ma50_percent?:number|null;price_vs_ma100_percent?:number|null;price_vs_ma200_percent?:number|null;all_time_high?:number|null;price_vs_ath_percent?:number|null;williams_r_14?:number|null;relative_volume:number|null;pe_ratio?:number|null;peg_ratio?:number|null;price_to_sales_ratio?:number|null;market_cap?:number|null;sector?:string|null;volume?:number|null;high_52_week:number|null;low_52_week:number|null;provider?:string;source_url?:string;as_of?:string|null;verification_status?:string;fundamentals_cache?:string;valuation_source?:string;pe_ratio_method?:string;price_to_sales_method?:string;peg_ratio_method?:string};
type Williams={period:number;timeframe:string;points:{date:string;value:number}[];latest:number|null;overbought_level:number;oversold_level:number;source_url?:string};
const money=(v:number|null|undefined)=>v==null?"—":`$${v.toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const ratio=(v:number|null|undefined)=>v==null?"—":v.toFixed(2);
const cls=(v:number|null|undefined,invert=false)=>v==null?"":((invert?v<=0:v>=0)?"positive":"negative");

export function MarketGrid({tickers,market,loading,onRefresh,onRemove,onEnrich,errors}:{tickers:string[];market:Record<string,Market>;loading:Record<string,boolean>;onRefresh:(s:string)=>void;onRemove:(s:string)=>void;onEnrich?:(s:string,d:Partial<Market>)=>void;errors?:Record<string,string>}){
 const[expanded,setExpanded]=useState<string|null>(null),[fundamentals,setFundamentals]=useState<Record<string,Partial<Market>>>({}),[williams,setWilliams]=useState<Record<string,Williams>>({}),[detailLoading,setDetailLoading]=useState<Record<string,boolean>>({}),[detailError,setDetailError]=useState<Record<string,string>>({});
 async function loadDetails(s:string){if(detailLoading[s])return;setDetailLoading(x=>({...x,[s]:true}));setDetailError(x=>({...x,[s]:""}));const [f,w]=await Promise.allSettled([fetch(`${API}/api/v1/markets/${encodeURIComponent(s)}/fundamentals`,{cache:"no-store"}),fetch(`${API}/api/v1/markets/${encodeURIComponent(s)}/williams-r?period=14`,{cache:"no-store"})]);const problems:string[]=[];
  if(f.status==="fulfilled"){try{const d=await f.value.json();if(f.value.ok){setFundamentals(x=>({...x,[s]:d}));onEnrich?.(s,d)}else problems.push(d?.detail||`Fundamentals HTTP ${f.value.status}`)}catch{problems.push("Fundamentals response was invalid")}}else problems.push("Fundamentals request failed");
  if(w.status==="fulfilled"){try{const d=await w.value.json();if(w.value.ok){setWilliams(x=>({...x,[s]:d}));onEnrich?.(s,{williams_r_14:d.latest})}else problems.push(d?.detail||`Williams %R HTTP ${w.value.status}`)}catch{problems.push("Williams %R response was invalid")}}else problems.push("Williams %R request failed");
  if(problems.length)setDetailError(x=>({...x,[s]:problems.join(" · ")}));setDetailLoading(x=>({...x,[s]:false}))}
 function toggle(s:string){const opening=expanded!==s;setExpanded(opening?s:null);if(opening&&(!fundamentals[s]||!williams[s]))loadDetails(s)}
 return <div className="card comparison-wrap reveal-card"><table className="comparison-table market-expand-table"><thead><tr><th>Ticker</th><th>Price</th><th>Day</th><th>7D</th><th>30D</th><th>YTD</th><th>50MA</th><th>100MA</th><th>200MA</th><th>ATH</th><th>vs ATH</th><th>P/S</th><th>P/E</th><th>PEG</th><th>Rel Vol</th><th></th></tr></thead><tbody>{tickers.map(s=>{const base=market[s],d=base?{...base,...fundamentals[s]}:base,open=expanded===s,error=errors?.[s];return <Fragment key={s}>
  <tr className={`market-click-row ${open?"expanded":""} ${error?"has-market-error":""}`} onClick={()=>toggle(s)} aria-expanded={open}>
   <td><strong>{s}</strong>{!d&&!error&&<span className="ticker-state-note">No stored data</span>}{error&&<span className="ticker-state-note error-note">Data error</span>}</td><td>{d?money(d.price):"—"}</td><td className={cls(d?.change_percent)}>{d?pct(d.change_percent):"—"}</td><td className={cls(d?.seven_day_percent)}>{d?pct(d.seven_day_percent):"—"}</td><td className={cls(d?.thirty_day_percent)}>{d?pct(d.thirty_day_percent):"—"}</td><td className={cls(d?.ytd_percent)}>{d?pct(d.ytd_percent):"—"}</td><td className={cls(d?.price_vs_ma50_percent)}>{d?money(d.ma50):"—"}</td><td className={cls(d?.price_vs_ma100_percent)}>{d?money(d.ma100):"—"}</td><td className={cls(d?.price_vs_ma200_percent)}>{d?money(d.ma200):"—"}</td><td>{d?money(d.all_time_high):"—"}</td><td className={cls(d?.price_vs_ath_percent)}>{d?pct(d.price_vs_ath_percent):"—"}</td><td>{d?ratio(d.price_to_sales_ratio):"—"}</td><td>{d?ratio(d.pe_ratio):"—"}</td><td>{d?ratio(d.peg_ratio):"—"}</td><td className={d?.relative_volume!=null?(d.relative_volume>=1?"positive":"negative"):""}>{d?.relative_volume!=null?`${d.relative_volume.toFixed(2)}x`:"—"}</td><td className="expand-cell">{open?"▴":"▾"}</td>
  </tr>
  {error&&<tr className="market-grid-error-row"><td colSpan={16}><div><div><strong>{s} market data failed</strong><span>{error}</span></div><button className="btn" disabled={!!loading[s]} onClick={e=>{e.stopPropagation();onRefresh(s)}}>{loading[s]?"Retrying…":"Retry"}</button></div></td></tr>}
  {open&&<tr className="market-detail-row"><td colSpan={16}><div className={`market-expanded-panel ${detailLoading[s]?"is-loading":""}`}><div className="section-head"><div><span className="eyebrow">Expanded security</span><h2>{s} {d?money(d.price):""}</h2></div><div className="expanded-actions">{detailLoading[s]&&<LoadingRing label={`Loading ${s} fundamentals and technicals`}/>}<button className="btn" disabled={!!loading[s]} onClick={e=>{e.stopPropagation();onRefresh(s);loadDetails(s)}}>{loading[s]?"Refreshing…":"Refresh"}</button><button className="btn danger" onClick={e=>{e.stopPropagation();onRemove(s);setExpanded(null)}}>Remove ticker</button></div></div>{d?<><div className="expanded-price-line"><strong className={cls(d.change_percent)}>{pct(d.change_percent)} today</strong><span className="muted">As of {d.as_of||"latest stored snapshot"} · {d.provider||"market provider"}</span></div><MarketCardMetrics d={d}/><div className="expanded-secondary"><span>Williams %R <strong>{d.williams_r_14==null?"—":d.williams_r_14.toFixed(1)}</strong></span><span>52W high <strong>{money(d.high_52_week)}</strong></span><span>52W low <strong>{money(d.low_52_week)}</strong></span><span>Market cap <strong>{d.market_cap==null?"—":`$${(d.market_cap/1_000_000_000).toFixed(2)}B`}</strong></span><span>Volume <strong>{d.volume==null?"—":Math.round(d.volume).toLocaleString()}</strong></span><span>Verification <strong>{d.verification_status||"—"}</strong></span></div>{d.fundamentals_cache&&<p className="muted small-note">Valuation cache: {d.fundamentals_cache}. {d.valuation_source||"Fundamentals provider"}. {d.pe_ratio_method||""} {d.price_to_sales_method||""} {d.peg_ratio_method||""}</p>}{d.source_url&&<a className="source-link" href={d.source_url} target="_blank" rel="noreferrer">Open market-data source ↗</a>}</>:<div className="inline-state"><span className="loader-dot"/><span>No stored snapshot yet. Refresh this ticker to request market data.</span></div>}
  <WilliamsChart data={williams[s]} loading={!!detailLoading[s]} error={detailError[s]}/>{error&&<div className="market-error"><strong>Could not refresh {s}</strong><span>{error}</span></div>}</div></td></tr>}
 </Fragment>})}</tbody></table></div>
}

function WilliamsChart({data,loading,error}:{data?:Williams;loading:boolean;error?:string}){
 if(loading&&!data)return <div className="indicator-card is-loading"><span className="eyebrow">Technical indicator</span><h3>Williams %R · all-time view</h3><div className="inline-loading"><LoadingRing label="Loading Williams percent range"/><p className="muted">Loading provider history…</p></div></div>;
 if(!data?.points?.length)return <div className="indicator-card"><span className="eyebrow">Technical indicator</span><h3>Williams %R · all-time view</h3><p className="muted">{error||"Indicator history is not available."}</p></div>;
 const pts=data.points,W=720,H=210,pad=24,x=(i:number)=>pad+(i/Math.max(pts.length-1,1))*(W-pad*2),y=(v:number)=>pad+((-v)/100)*(H-pad*2),path=pts.map((p,i)=>`${i?"L":"M"}${x(i).toFixed(1)},${y(p.value).toFixed(1)}`).join(" ");
 return <div className="indicator-card"><div className="section-head"><div><span className="eyebrow">Technical indicator</span><h3>Williams %R · 14-day · all-time</h3></div><strong className={(data.latest??-50)>-20?"positive":(data.latest??-50)<-80?"negative":""}>{data.latest==null?"—":data.latest.toFixed(1)}</strong></div><svg className="williams-chart" viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Williams percent range across all available provider history"><line x1={pad} x2={W-pad} y1={y(-20)} y2={y(-20)} className="indicator-guide"/><line x1={pad} x2={W-pad} y1={y(-80)} y2={y(-80)} className="indicator-guide"/><path d={path} className="indicator-line" fill="none"/><text x={pad} y={y(-20)-5}>-20</text><text x={pad} y={y(-80)-5}>-80</text></svg><div className="indicator-axis"><span>{pts[0].date}</span><span>Overbought &gt; -20 · Oversold &lt; -80</span><span>{pts[pts.length-1].date}</span></div>{data.source_url&&<a className="source-link" href={data.source_url} target="_blank" rel="noreferrer">Indicator source ↗</a>}{error&&<p className="muted small-note">{error}</p>}</div>
}

export function MarketCardMetrics({d}:{d:Market}){
 const rows=[["7D",pct(d.seven_day_percent),cls(d.seven_day_percent)],["30D",pct(d.thirty_day_percent),cls(d.thirty_day_percent)],["YTD",pct(d.ytd_percent),cls(d.ytd_percent)],["50MA",money(d.ma50),cls(d.price_vs_ma50_percent)],["100MA",money(d.ma100),cls(d.price_vs_ma100_percent)],["200MA",money(d.ma200),cls(d.price_vs_ma200_percent)],["ATH",money(d.all_time_high),""],["vs ATH",pct(d.price_vs_ath_percent),cls(d.price_vs_ath_percent)],["P/S",ratio(d.price_to_sales_ratio),""],["P/E",ratio(d.pe_ratio),""],["PEG",ratio(d.peg_ratio),""],["Rel Vol",d.relative_volume==null?"—":`${d.relative_volume.toFixed(2)}x`,d.relative_volume==null?"":d.relative_volume>=1?"positive":"negative"]];
 return <div className="metric-grid">{rows.map(([label,value,c])=><span key={label}>{label} <strong className={c}>{value}</strong></span>)}</div>
}
