"use client";
import {Fragment,useState} from "react";
import LoadingRing from "./loading-ring";

const API="/backend";
type Market={symbol:string;price:number|null;change_percent:number|null;seven_day_percent:number|null;thirty_day_percent:number|null;ytd_percent:number|null;ma50?:number|null;ma100:number|null;ma200:number|null;price_vs_ma50_percent?:number|null;price_vs_ma100_percent?:number|null;price_vs_ma200_percent?:number|null;all_time_high?:number|null;price_vs_ath_percent?:number|null;williams_r_14?:number|null;relative_volume:number|null;pe_ratio?:number|null;peg_ratio?:number|null;price_to_sales_ratio?:number|null;market_cap?:number|null;sector?:string|null;volume?:number|null;high_52_week:number|null;low_52_week:number|null;provider?:string;source_url?:string;as_of?:string|null;verification_status?:string;fundamentals_cache?:string;valuation_source?:string;pe_ratio_method?:string;price_to_sales_method?:string;peg_ratio_method?:string};
type Williams={period:number;timeframe:string;points:{date:string;value:number}[];latest:number|null;overbought_level:number;oversold_level:number;source_url?:string};
const money=(v:number|null|undefined)=>v==null?"—":`$${v.toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const ratio=(v:number|null|undefined)=>v==null?"—":v.toFixed(2);
const cls=(v:number|null|undefined)=>v==null?"":v>=0?"positive":"negative";

export function MarketGrid({tickers,market,loading,onRefresh,onRemove,onEnrich,errors}:{tickers:string[];market:Record<string,Market>;loading:Record<string,boolean>;onRefresh:(s:string)=>void;onRemove:(s:string)=>void;onEnrich?:(s:string,d:Partial<Market>)=>void;errors?:Record<string,string>}){
 const[expanded,setExpanded]=useState<string|null>(null),[fundamentals,setFundamentals]=useState<Record<string,Partial<Market>>>({}),[williams,setWilliams]=useState<Record<string,Williams>>({}),[detailLoading,setDetailLoading]=useState<Record<string,boolean>>({}),[detailError,setDetailError]=useState<Record<string,string>>({});
 async function read(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
 async function loadDetails(s:string){if(detailLoading[s])return;setDetailLoading(x=>({...x,[s]:true}));setDetailError(x=>({...x,[s]:""}));const[f,w]=await Promise.allSettled([read(`/api/v1/markets/${encodeURIComponent(s)}/fundamentals`),read(`/api/v1/markets/${encodeURIComponent(s)}/williams-r?period=14`)]);const problems:string[]=[];if(f.status==="fulfilled"){setFundamentals(x=>({...x,[s]:f.value}));onEnrich?.(s,f.value)}else problems.push(f.reason?.message||"Fundamentals request failed");if(w.status==="fulfilled"){setWilliams(x=>({...x,[s]:w.value}));onEnrich?.(s,{williams_r_14:w.value.latest})}else problems.push(w.reason?.message||"Williams %R request failed");if(problems.length)setDetailError(x=>({...x,[s]:problems.join(" · ")}));setDetailLoading(x=>({...x,[s]:false}))}
 function toggle(s:string){const opening=expanded!==s;setExpanded(opening?s:null);if(opening&&(!fundamentals[s]||!williams[s]))loadDetails(s)}
 return <div className="card comparison-wrap reveal-card"><table className="comparison-table market-expand-table"><thead><tr><th>Ticker</th><th>Price</th><th>Day</th><th>7D</th><th>30D</th><th>YTD</th><th>50MA</th><th>100MA</th><th>200MA</th><th>ATH</th><th>vs ATH</th><th>P/S</th><th>P/E</th><th>PEG</th><th>Rel Vol</th><th/></tr></thead><tbody>{tickers.map(s=>{const base=market[s],d=base?{...base,...fundamentals[s]}:base,open=expanded===s,error=errors?.[s];return <Fragment key={s}><tr className={`market-click-row ${open?"expanded":""}`} onClick={()=>toggle(s)}><td><strong>{s}</strong>{!d&&!error&&<span className="ticker-state-note">No stored data</span>}</td><td>{d?money(d.price):"—"}</td><td className={cls(d?.change_percent)}>{pct(d?.change_percent)}</td><td className={cls(d?.seven_day_percent)}>{pct(d?.seven_day_percent)}</td><td className={cls(d?.thirty_day_percent)}>{pct(d?.thirty_day_percent)}</td><td className={cls(d?.ytd_percent)}>{pct(d?.ytd_percent)}</td><td>{money(d?.ma50)}</td><td>{money(d?.ma100)}</td><td>{money(d?.ma200)}</td><td>{money(d?.all_time_high)}</td><td className={cls(d?.price_vs_ath_percent)}>{pct(d?.price_vs_ath_percent)}</td><td>{ratio(d?.price_to_sales_ratio)}</td><td>{ratio(d?.pe_ratio)}</td><td>{ratio(d?.peg_ratio)}</td><td>{d?.relative_volume==null?"—":`${d.relative_volume.toFixed(2)}x`}</td><td>{open?"▴":"▾"}</td></tr>{error&&<tr className="market-grid-error-row"><td colSpan={16}><div><strong>{error}</strong><button className="btn" onClick={e=>{e.stopPropagation();onRefresh(s)}}>Retry</button></div></td></tr>}{open&&<tr className="market-detail-row"><td colSpan={16}><div className="market-expanded-panel"><div className="section-head"><div><span className="eyebrow">Expanded security</span><h2>{s} {d?money(d.price):""}</h2></div><div className="expanded-actions">{detailLoading[s]&&<LoadingRing label={`Loading ${s} details`}/>}<button className="btn" disabled={!!loading[s]} onClick={e=>{e.stopPropagation();onRefresh(s);loadDetails(s)}}>Refresh</button><button className="btn danger" onClick={e=>{e.stopPropagation();onRemove(s);setExpanded(null)}}>Remove ticker</button></div></div>{d&&<><div className="expanded-secondary"><span>Williams %R <strong>{d.williams_r_14==null?"—":d.williams_r_14.toFixed(1)}</strong></span><span>52W high <strong>{money(d.high_52_week)}</strong></span><span>52W low <strong>{money(d.low_52_week)}</strong></span><span>Market cap <strong>{d.market_cap==null?"—":`$${(d.market_cap/1e9).toFixed(2)}B`}</strong></span><span>Volume <strong>{d.volume==null?"—":Math.round(d.volume).toLocaleString()}</strong></span><span>Verification <strong>{d.verification_status||"—"}</strong></span></div>{d.source_url&&<a className="source-link" href={d.source_url} target="_blank" rel="noreferrer">Open market-data source ↗</a>}</>}<WilliamsChart data={williams[s]} loading={!!detailLoading[s]} error={detailError[s]}/></div></td></tr>}</Fragment>})}</tbody></table></div>
}

function WilliamsChart({data,loading,error}:{data?:Williams;loading:boolean;error?:string}){
 if(loading&&!data)return <div className="indicator-card"><LoadingRing label="Loading Williams percent range"/></div>;
 if(!data?.points?.length)return <div className="indicator-card"><p className="muted">{error||"Indicator history is not available."}</p></div>;
 const pts=data.points,W=720,H=210,pad=24,x=(i:number)=>pad+(i/Math.max(pts.length-1,1))*(W-pad*2),y=(v:number)=>pad+((-v)/100)*(H-pad*2),path=pts.map((p,i)=>`${i?"L":"M"}${x(i).toFixed(1)},${y(p.value).toFixed(1)}`).join(" ");
 return <div className="indicator-card"><div className="section-head"><h3>Williams %R · 14-day · all-time</h3><strong>{data.latest==null?"—":data.latest.toFixed(1)}</strong></div><svg className="williams-chart" viewBox={`0 0 ${W} ${H}`}><line x1={pad} x2={W-pad} y1={y(-20)} y2={y(-20)} className="indicator-guide"/><line x1={pad} x2={W-pad} y1={y(-80)} y2={y(-80)} className="indicator-guide"/><path d={path} className="indicator-line" fill="none"/></svg><div className="indicator-axis"><span>{pts[0].date}</span><span>Overbought &gt; -20 · Oversold &lt; -80</span><span>{pts[pts.length-1].date}</span></div></div>
}
