"use client";
import {useEffect} from "react";
import type {AccessState} from "./user-customization";

const GROUPS=[{label:"Daily",items:["Report","Markets","Portfolio"]},{label:"Analysis",items:["Opportunities","Research","Macro","Regime"]},{label:"Intelligence",items:["World News","Events","Large Flow"]},{label:"Monitor",items:["Alerts","Theses"]},{label:"System",items:["Settings"]}];
export default function GroupedNavigation({nav,active,commandActive,access,onCommand}:{nav:Element;active:string;commandActive:boolean;access:AccessState|null;onCommand:()=>void}){
 useEffect(()=>{nav.classList.add("nav-v3-ready");return()=>nav.classList.remove("nav-v3-ready")},[nav]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key!=="Escape")return;const open=document.activeElement?.closest?.("details.nav-group[open]") as HTMLDetailsElement|null;if(open){open.open=false;(open.querySelector("summary") as HTMLElement|null)?.focus()}};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{const onPointer=(e:PointerEvent)=>{document.querySelectorAll<HTMLDetailsElement>("details.nav-group[open]").forEach(d=>{if(!d.contains(e.target as Node))d.open=false})};document.addEventListener("pointerdown",onPointer);return()=>document.removeEventListener("pointerdown",onPointer)},[]);
 const visible=new Set(access?.preferences?.visible_tabs?.length?access.preferences.visible_tabs:access?.allowed_tabs||["Command Center","Report","Markets","Portfolio","Opportunities","World News","Events","Large Flow","Macro","Regime","Research","Alerts","Theses","Settings"]);
 function select(name:string,e?:React.MouseEvent){e?.currentTarget.closest("details")?.removeAttribute("open");if(name==="Command Center"){onCommand();return}window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:name}))}
 return <div className="nav-v3" role="navigation" aria-label="Primary navigation">{visible.has("Command Center")&&<button className={`nav-command ${commandActive?"active":""}`} aria-current={commandActive?"page":undefined} onClick={e=>select("Command Center",e)}>Command Center</button>}{GROUPS.map(group=>{const items=group.items.filter(x=>visible.has(x));if(!items.length)return null;const selected=!commandActive&&items.includes(active);return <details className={`nav-group ${selected?"active-group":""}`} key={group.label}><summary aria-label={`${group.label} navigation${selected?`, current page ${active}`:""}`}>{group.label}{selected&&<span aria-hidden="true">{active}</span>}<b aria-hidden="true">▾</b></summary><div className="nav-menu" role="group" aria-label={`${group.label} pages`}>{items.map(item=><button key={item} aria-current={!commandActive&&active===item?"page":undefined} className={!commandActive&&active===item?"active":""} onClick={e=>select(item,e)}>{item}</button>)}</div></details>})}</div>
}
