"use client";

import {useEffect,useState} from "react";

const API="/backend";
async function api(path:string,timeout=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${API}${path}`,{cache:"no-store",credentials:"include",signal:c.signal});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("Request timed out");throw e}finally{clearTimeout(t)}}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;

export function FactorProxyPanel(){
 const[portfolioId,setPortfolioId]=useState<number|null>(null),[benchmark,setBenchmark]=useState("SPY"),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let live=true;(async()=>{try{const d=await api("/api/v1/portfolios");if(!live)return;const rows=d.portfolios||[];let chosen=Number(localStorage.getItem("dailyReportPortfolioId")||0)||rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null;if(chosen&&!rows.some((x:any)=>x.id===chosen))chosen=rows[0]?.id||null;setPortfolioId(chosen)}catch(e:any){if(live)setError(e.message)}})();return()=>{live=false}},[]);
 async function load(id=portfolioId,b=benchmark){if(!id)return;setLoading(true);setError("");try{setData(await api(`/api/v1/future/portfolio/${id}/factor-proxies?benchmark=${encodeURIComponent(b.trim().toUpperCase()||"SPY")}&days=126`))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(portfolioId)load(portfolioId,benchmark)},[portfolioId]);
 return <section className="future-panel"><div className="card section-head"><div><span className="eyebrow">Proxy sensitivities</span><h3>Factor & benchmark context</h3><p className="muted">Descriptive correlation/beta to liquid proxies using stored daily returns. These are not institutional factor-model loadings.</p></div><form onSubmit={e=>{e.preventDefault();load()}} className="future-inline-form"><label>Custom benchmark<input className="search" value={benchmark} onChange={e=>setBenchmark(e.target.value.toUpperCase())} placeholder="SPY"/></label><button className="btn" disabled={!portfolioId||loading}>{loading?"Calculating…":"Compare"}</button></form></div>{error&&<div className="suite-error"><span>{error}</span></div>}{data&&<><div className="future-proxy-grid">{(data.proxies||[]).map((x:any)=><details className="card methodology-dropdown" key={`${x.factor}-${x.symbol}`}><summary><div><strong>{x.label}</strong><span>{x.symbol} · {x.observations} obs</span></div><b>▾</b></summary><div className="metric-tile-grid"><span><i>Correlation</i><strong>{x.correlation??"—"}</strong></span><span><i>Beta</i><strong>{x.beta??"—"}</strong></span><span><i>Portfolio return</i><strong>{pct(x.portfolio_return_percent)}</strong></span><span><i>Proxy return</i><strong>{pct(x.proxy_return_percent)}</strong></span><span><i>Relative</i><strong className={(x.relative_return_percent||0)>=0?"positive":"negative"}>{pct(x.relative_return_percent)}</strong></span></div></details>)}</div><p className="muted">{data.methodology}</p></>}</section>
}

export function RegimeDimensionsPanel(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setData(await api("/api/v1/future/regime/dimensions"))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 return <section className="future-panel"><div className="card section-head"><div><span className="eyebrow">Multidimensional regime</span><h3>{data?.headline||"Regime dimensions"}</h3><p className="muted">Risk appetite, growth, inflation pressure, liquidity and rates/dollar pressure are scored independently so mixed conditions remain visible.</p></div><button className="btn" onClick={load} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></div>{error&&<div className="suite-error"><span>{error}</span></div>}{data&&<div className="future-dimension-grid">{(data.dimensions||[]).map((d:any)=><details className={`card methodology-dropdown dimension-${d.state}`} key={d.dimension} open={d.state==="uncertain"}><summary><div><strong>{d.label}</strong><span>{d.state} · {d.score} pts</span></div><b>▾</b></summary><div className="metric-tile-grid"><span><i>Confidence</i><strong>{d.confidence_percent}%</strong></span><span><i>Coverage</i><strong>{d.coverage_percent}%</strong></span><span><i>Agreement</i><strong>{d.agreement_percent}%</strong></span></div><div className="history-row-list">{(d.evidence||[]).map((x:any)=><span key={x.symbol}><strong>{x.symbol}</strong><b>{x.contribution>=0?"+":""}{x.contribution}</b><small>signal {x.signal} × weight {x.weight} · {x.as_of||"stored"}</small></span>)}</div></details>)}</div>}{data&&<p className="muted">{data.methodology}</p>}</section>
}
