"use client";

import {useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;const n=(v:any)=>v==null?"—":Number(v).toFixed(2);
function go(name:string){window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:name}))}
const META:any={technical:{label:"Technicals",weight:"25%",desc:"Williams %R, 100/200MA proximity and multi-timeframe price momentum from the shared Markets snapshot.",tab:"Markets"},valuation:{label:"Valuation",weight:"20%",desc:"P/E, P/S and PEG from the global fundamentals hierarchy: Yahoo → SEC EDGAR → quota-aware Alpha fallback.",tab:"Research"},sector:{label:"Sector",weight:"15%",desc:"Related-sector rotation score from Macro. Positive leadership raises this component.",tab:"Macro"},flow:{label:"Flow",weight:"15%",desc:"Bullish minus bearish unusual-options premium, scaled relative to cached market capitalization.",tab:"Large Flow"},momentum:{label:"Relative Strength / Momentum",weight:"15%",desc:"7D and 30D price momentum. The Relative Strength view also compares the same return windows to SPY and QQQ.",tab:"Macro"},risk:{label:"Risk",weight:"10%",desc:"Simple setup-risk context using ATH proximity and elevated relative volume; transparent screening input, not a risk model.",tab:"Research"}};
function Spark({rows}:{rows:any[]}){if(!rows?.length)return <span className="muted">No historical snapshots yet.</span>;const vals=rows.map(x=>Number(x.buy_score||0)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const d=vals.map((v,i)=>`${i?"L":"M"} ${(i/Math.max(1,vals.length-1))*100} ${90-((v-min)/span)*80}`).join(" ");return <svg className="score-spark" viewBox="0 0 100 100" preserveAspectRatio="none"><path d={d} fill="none" vectorEffect="non-scaling-stroke"/></svg>}

export default function OpportunitiesWorkspaceV3(){
 const[data,setData]=useState<any>(null),[changes,setChanges]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Rankings"),[history,setHistory]=useState<Record<string,any>>({}),[sort,setSort]=useState("buy");
 async function load(){setLoading(true);setError("");try{const[d,c]=await Promise.all([api("/api/v1/opportunities?limit=200"),api("/api/v1/command-center")]);setData(d);setChanges(c)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 async function loadHistory(s:string){if(history[s])return;try{setHistory(h=>({...h,[s]:{loading:true}}));const d=await api(`/api/v1/opportunities/${s}/history?days=180`);setHistory(h=>({...h,[s]:d}))}catch{setHistory(h=>({...h,[s]:{history:[]}}))}}
 const rows=useMemo(()=>{const x=[...(data?.opportunities||[])];x.sort((a:any,b:any)=>sort==="sell"?(b.sell_score||0)-(a.sell_score||0):(b.buy_score||0)-(a.buy_score||0));return x},[data,sort]);
 return <section className="tab-panel v3-workspace opportunities-v3"><div className="card suite-hero"><div><span className="eyebrow">Auditable multi-factor screener</span><h2>Opportunities</h2><p className="muted">A compact ranking first; every component, source pathway and score history stays one click deeper.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div><div className="subtab-bar">{["Rankings","Changes","Methodology"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Opportunities unavailable</strong><span>{error}</span></div>}
 {tab==="Rankings"&&<div className="v3-stack"><div className="card sort-strip"><span className="muted">Rank by</span><button className={sort==="buy"?"active":""} onClick={()=>setSort("buy")}>Buy setup</button><button className={sort==="sell"?"active":""} onClick={()=>setSort("sell")}>Sell / trim setup</button></div><div className="opportunity-v3-list">{rows.map((o:any)=><details className="card opportunity-v3-card" key={o.symbol} onToggle={(e:any)=>e.currentTarget.open&&loadHistory(o.symbol)}><summary><div><strong>{o.symbol}</strong><span>Buy {n(o.buy_score)}</span><span>Sell {n(o.sell_score)}</span></div><div className="opportunity-mini-components">{Object.entries(o.components||{}).slice(0,4).map(([k,v]:any)=><span key={k}>{META[k]?.label||k}<b>{n(v)}</b></span>)}</div><b>▾</b></summary><div className="opportunity-v3-detail"><div className="component-grid-v3">{Object.entries(o.components||{}).map(([k,v]:any)=><details className="metric-explainer" key={k}><summary><div><span>{META[k]?.label||k}</span><strong>{n(v)}</strong></div><small>{META[k]?.weight||""}</small><b>▾</b></summary><p>{META[k]?.desc}</p><div className="metric-links"><button className="text-btn" onClick={()=>go(META[k]?.tab||"Research")}>Open {META[k]?.tab||"Research"} →</button></div></details>)}</div><details className="methodology-dropdown"><summary><strong>Current inputs</strong><span className="muted">raw context</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Sector score</i><strong>{n(o.sector_score)}</strong></span><span><i>Bullish flow</i><strong>${Math.round(o.flow?.bullish_premium||0).toLocaleString()}</strong></span><span><i>Bearish flow</i><strong>${Math.round(o.flow?.bearish_premium||0).toLocaleString()}</strong></span><span><i>Flow events</i><strong>{o.flow?.events??0}</strong></span></div></details><details className="methodology-dropdown" open><summary><strong>Score history</strong><span className="muted">up to 180D stored features</span><b>▾</b></summary>{history[o.symbol]?.loading?<span className="spinner-line"><i/>Loading history…</span>:<><Spark rows={history[o.symbol]?.history||[]}/><div className="history-inline-values">{(history[o.symbol]?.history||[]).slice(-8).map((h:any)=><span key={h.as_of}><small>{h.as_of}</small><b>{h.buy_score}</b></span>)}</div></>}</details></div></details>)}</div></div>}
 {tab==="Changes"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><div><span className="eyebrow">Change detection</span><strong>Material score moves & new technical flags</strong></div><span>{changes?.score_changes?.length||0}</span><b>▾</b></summary><div className="compact-list">{(changes?.score_changes||[]).map((x:any)=><button key={x.symbol} onClick={()=>setTab("Rankings")}><strong>{x.symbol}</strong><span className={(x.buy_change||0)>=0?"positive":"negative"}>Buy {x.buy_change>=0?"+":""}{x.buy_change}</span><span>Sell {x.sell_change>=0?"+":""}{x.sell_change}</span><small>{(x.new_flags||[]).join(" · ")||x.as_of}</small></button>)}</div></details></div>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Composite formula</strong><b>▾</b></summary><p>{data?.methodology}</p></details>{Object.entries(META).map(([k,m]:any)=><details className="card methodology-dropdown" key={k}><summary><div><strong>{m.label}</strong><span className="muted">{m.weight}</span></div><b>▾</b></summary><p>{m.desc}</p><button className="text-btn" onClick={()=>go(m.tab)}>Open {m.tab} →</button></details>)}</div>}
 </section>
}
