"use client";
import {useEffect,useMemo,useState} from "react";
import {navigateTo,type NavigationTarget} from "./navigation-context";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function headers(){const e=typeof window!=="undefined"?localStorage.getItem("dailyReportUserEmail")||"":"",t=typeof window!=="undefined"?localStorage.getItem("dailyReportUserToken")||"":"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const n=(v:any)=>v==null?"—":Number(v).toFixed(2);
const META:any={
 technical:{label:"Technicals",weight:"25%",desc:"Williams %R, 100/200MA proximity and multi-timeframe momentum from the shared market/history store.",target:(s:string)=>({tab:"Research",symbol:s,subtab:"Technicals"})},
 valuation:{label:"Valuation",weight:"20%",desc:"P/E, P/S and PEG from the fundamentals hierarchy and derived-input fallbacks.",target:(s:string)=>({tab:"Research",symbol:s,subtab:"Valuation"})},
 sector:{label:"Sector",weight:"15%",desc:"Sector-proxy rotation score from Macro leadership/weakness.",target:()=>({tab:"Macro",subtab:"Leadership"})},
 flow:{label:"Flow",weight:"15%",desc:"Bullish minus bearish unusual-options premium, normalized by market capitalization when available.",target:(s:string)=>({tab:"Large Flow",subtab:"Feed",filter:s})},
 momentum:{label:"Relative Strength / Momentum",weight:"15%",desc:"7D/30D momentum plus same-window relative-return context versus SPY and QQQ.",target:(s:string)=>({tab:"Research",symbol:s,subtab:"Technicals"})},
 risk:{label:"Risk",weight:"10%",desc:"ATH proximity and relative-volume context used as a transparent screening input.",target:(s:string)=>({tab:"Research",symbol:s,subtab:"Overview"})},
};
function Spark({rows}:{rows:any[]}){if(!rows?.length)return <span className="muted">No historical snapshots yet.</span>;const vals=rows.map(x=>Number(x.buy_score||0)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,d=vals.map((v,i)=>`${i?"L":"M"} ${(i/Math.max(1,vals.length-1))*100} ${90-((v-min)/span)*80}`).join(" ");return <svg className="score-spark" viewBox="0 0 100 100" preserveAspectRatio="none"><path d={d} fill="none" vectorEffect="non-scaling-stroke"/></svg>}

export default function OpportunitiesWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[data,setData]=useState<any>(null),[changes,setChanges]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[tab,setTab]=useState("Rankings"),[history,setHistory]=useState<Record<string,any>>({}),[sort,setSort]=useState("buy"),[focus,setFocus]=useState<string|null>(null);
 async function load(){setLoading(true);setError("");try{const[d,c]=await Promise.all([api("/api/v1/opportunities?limit=200"),api("/api/v1/command-center")]);setData(d);setChanges(c)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);useEffect(()=>{if(navigation?.tab!=="Opportunities")return;if(navigation.subtab)setTab(navigation.subtab);if(navigation.symbol){setFocus(navigation.symbol);setTab("Rankings")}},[navigation?.nonce]);
 async function loadHistory(s:string){if(history[s])return;setHistory(h=>({...h,[s]:{loading:true}}));try{const d=await api(`/api/v1/opportunities/${s}/history?days=180`);setHistory(h=>({...h,[s]:d}))}catch{setHistory(h=>({...h,[s]:{history:[]}}))}}
 const rows=useMemo(()=>{const x=[...(data?.opportunities||[])];x.sort((a:any,b:any)=>sort==="sell"?(b.sell_score||0)-(a.sell_score||0):(b.buy_score||0)-(a.buy_score||0));if(focus){const i=x.findIndex((r:any)=>r.symbol===focus);if(i>0)x.unshift(...x.splice(i,1))}return x},[data,sort,focus]);
 return <section className="tab-panel v3-workspace opportunities-v3"><div className="card suite-hero"><div><span className="eyebrow">Auditable multi-factor screener</span><h2>Opportunities</h2><p className="muted">Scores stay compact until expanded; source links retain the selected ticker and open the exact supporting view.</p></div><button className="btn" disabled={loading} onClick={load}>{loading?"Updating…":"Refresh"}</button></div><div className="subtab-bar">{["Rankings","Changes","Methodology"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Opportunities unavailable</strong><span>{error}</span></div>}
 {tab==="Rankings"&&<div className="v3-stack"><div className="card sort-strip"><span className="muted">Rank by</span><button className={sort==="buy"?"active":""} onClick={()=>setSort("buy")}>Buy setup</button><button className={sort==="sell"?"active":""} onClick={()=>setSort("sell")}>Sell / trim</button></div><div className="opportunity-v3-list">{rows.map((o:any)=><details className="card opportunity-v3-card" data-security-symbol={o.symbol} key={o.symbol} onToggle={(e:any)=>e.currentTarget.open&&loadHistory(o.symbol)}><summary><div><strong>{o.symbol}</strong><span>Buy {n(o.buy_score)}</span><span>Sell {n(o.sell_score)}</span></div><div className="opportunity-mini-components">{Object.entries(o.components||{}).slice(0,4).map(([k,v]:any)=><span key={k}>{META[k]?.label||k}<b>{n(v)}</b></span>)}</div><b>▾</b></summary><div className="opportunity-v3-detail"><div className="component-grid-v3">{Object.entries(o.components||{}).map(([k,v]:any)=>{const m=META[k];return <details className="metric-explainer" key={k}><summary><div><span>{m?.label||k}</span><strong>{n(v)}</strong></div><small>{m?.weight||""}</small><b>▾</b></summary><p>{m?.desc}</p><button className="text-btn" onClick={()=>navigateTo(m?.target?.(o.symbol)||{tab:"Research",symbol:o.symbol})}>Open source detail →</button></details>})}</div><details className="methodology-dropdown"><summary><strong>Current inputs</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Sector score</i><strong>{n(o.sector_score)}</strong></span><span><i>Bullish flow</i><strong>${Math.round(o.flow?.bullish_premium||0).toLocaleString()}</strong></span><span><i>Bearish flow</i><strong>${Math.round(o.flow?.bearish_premium||0).toLocaleString()}</strong></span><span><i>Flow events</i><strong>{o.flow?.events??0}</strong></span></div></details><details className="methodology-dropdown"><summary><strong>Score history</strong><span className="muted">180D feature snapshots</span><b>▾</b></summary>{history[o.symbol]?.loading?<span className="spinner-line"><i/>Loading…</span>:<Spark rows={history[o.symbol]?.history||[]}/>}</details></div></details>)}</div></div>}
 {tab==="Changes"&&<details className="card methodology-dropdown" open><summary><strong>Material score moves & new flags</strong><span>{changes?.score_changes?.length||0}</span><b>▾</b></summary><div className="compact-list">{(changes?.score_changes||[]).map((x:any)=><button key={x.symbol} onClick={()=>{setFocus(x.symbol);setTab("Rankings")}}><strong>{x.symbol}</strong><span>Buy {x.buy_change>=0?"+":""}{x.buy_change}</span><span>Sell {x.sell_change>=0?"+":""}{x.sell_change}</span></button>)}</div></details>}
 {tab==="Methodology"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Composite formula</strong><b>▾</b></summary><p>{data?.methodology}</p></details>{Object.entries(META).map(([k,m]:any)=><details className="card methodology-dropdown" key={k}><summary><div><strong>{m.label}</strong><span>{m.weight}</span></div><b>▾</b></summary><p>{m.desc}</p></details>)}</div>}
 </section>
}
