"use client";
import {useEffect,useState} from "react";
import MacroHistory from "./macro-history";
import HomeDashboard from "./home-dashboard";
import SectorPerformance from "./sector-performance";
const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
const TABS=["Report","Markets","World News","Large Flow","Macro","Settings"];
type Market={symbol:string;price:number|null;change_percent:number|null;seven_day_percent:number|null;thirty_day_percent:number|null;ytd_percent:number|null;ma100:number|null;ma200:number|null;relative_volume:number|null;volume:number|null;high_52_week:number|null;low_52_week:number|null;provider:string;source_url:string;as_of:string|null;verification_status:string};
type News={title:string;url:string;domain?:string;source_country?:string;published_at?:string;topics?:string[];sectors?:string[];relevance_score?:number;why_it_matters?:string};
type Rotation={methodology:string;sectors:any[];leaders:any[];laggards:any[];evidence:string[];possible_reasons:any[]};
const money=(v:number|null)=>v==null?"—":`$${v.toFixed(2)}`;const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
export default function Home(){
 const[tickers,setTickers]=useState<string[]>([]),[active,setActive]=useState("Report"),[status,setStatus]=useState("Connecting...");
 const[market,setMarket]=useState<Record<string,Market>>({}),[loading,setLoading]=useState<Record<string,boolean>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[view,setView]=useState("grid");
 const[query,setQuery]=useState(""),[search,setSearch]=useState<any[]>([]),[news,setNews]=useState<News[]>([]),[topic,setTopic]=useState("All"),[newsStatus,setNewsStatus]=useState("Not loaded");
 const[rotation,setRotation]=useState<Rotation|null>(null),[macroStatus,setMacroStatus]=useState("Not loaded"),[report,setReport]=useState<any>(null),[reportStatus,setReportStatus]=useState("Loading...");
 async function json(url:string,options?:RequestInit){const r=await fetch(url,{cache:"no-store",...options});const d=await r.json();if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
 async function init(){try{const w=await json(`${API}/api/v1/watchlist`);setTickers(w.tickers||[]);setStatus("Backend connected");const latest=await json(`${API}/api/v1/markets/latest`);const m:Record<string,Market>={};(latest.markets||[]).forEach((x:Market)=>m[x.symbol]=x);setMarket(m)}catch{setStatus("Backend connection failed")}loadReport();loadMacro()}
 useEffect(()=>{init()},[]);
 useEffect(()=>{if(query.trim().length<2){setSearch([]);return}const t=setTimeout(async()=>{try{const d=await json(`${API}/api/v1/securities/search?q=${encodeURIComponent(query)}`);setSearch(d.results||[])}catch{setSearch([])}},450);return()=>clearTimeout(t)},[query]);
 async function loadOne(s:string){setLoading(x=>({...x,[s]:true}));setErrors(x=>({...x,[s]:""}));try{const d=await json(`${API}/api/v1/markets/${encodeURIComponent(s)}`);setMarket(x=>({...x,[s]:d}))}catch(e){setErrors(x=>({...x,[s]:e instanceof Error?e.message:"Unavailable"}))}finally{setLoading(x=>({...x,[s]:false}))}}
 async function add(s?:string){const sym=(s||query).trim().toUpperCase();if(!sym)return;try{await json(`${API}/api/v1/watchlist`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:sym})});setQuery("");setSearch([]);const w=await json(`${API}/api/v1/watchlist`);setTickers(w.tickers||[])}catch{}}
 async function remove(s:string){try{await json(`${API}/api/v1/watchlist/${encodeURIComponent(s)}`,{method:"DELETE"});setTickers(x=>x.filter(y=>y!==s));setMarket(x=>{const n={...x};delete n[s];return n})}catch{}}
 async function loadNews(t=topic){setNewsStatus("Loading...");try{const u=t==="All"?`${API}/api/v1/news/world?limit=40`:`${API}/api/v1/news/world?limit=40&topic=${encodeURIComponent(t)}`;const d=await json(u);setNews(d.articles||[]);setNewsStatus(`${d.articles?.length||0} intelligence items · ${d.provider}`)}catch(e){setNewsStatus(e instanceof Error?e.message:"Unavailable")}}
 async function loadMacro(){setMacroStatus("Loading rotation data...");try{const d=await json(`${API}/api/v1/macro/rotation`);setRotation(d);setMacroStatus(`${d.sectors?.length||0} tracked groups with stored market data`)}catch(e){setMacroStatus(e instanceof Error?e.message:"Unavailable")}}
 async function loadReport(){try{const d=await json(`${API}/api/v1/report/current`);setReport(d);setReportStatus(`Generated ${new Date(d.generated_at).toLocaleString()}`)}catch(e){setReportStatus(e instanceof Error?e.message:"Unavailable")}}
 async function saveReport(){try{const d=await json(`${API}/api/v1/report/generate`,{method:"POST"});setReport(d);setReportStatus(`Saved report #${d.id}`)}catch{}}
 const topics=["All","AI & Semiconductors","Rates & Central Banks","Energy & Commodities","Trade & Geopolitics","Economy & Inflation"];
 return <main className="container"><header className="app-header"><div className="brand-lockup"><div className="brand-mark">⌁</div><div><h1>Daily Report</h1><p className="muted">Market intelligence dashboard</p></div></div><span className={`status ${status==="Backend connected"?"ok":""}`}>{status}</span></header>
 <nav className="nav">{TABS.map(t=><button key={t} className={active===t?"active":""} onClick={()=>{setActive(t);if(t==="World News"&&!news.length)loadNews();if(t==="Macro")loadMacro()}}>{t}</button>)}</nav>
 {active==="Report"&&<section><HomeDashboard market={market} rotation={rotation} onOpenMarkets={()=>setActive("Markets")} onOpenMacro={()=>setActive("Macro")}/><div className="card row report-utility"><div><h2>Daily Report</h2><p className="muted">{reportStatus}</p></div><div className="report-actions"><button className="btn" onClick={loadReport}>Refresh</button><button className="btn" onClick={saveReport}>Save snapshot</button></div></div>{report&&<><div className="report-summary-grid"><article className="card stat-card"><span>Watchlist</span><strong>{report.watchlist_count}</strong></article><article className="card stat-card"><span>Loaded</span><strong>{report.market_data_count}</strong></article><article className="card stat-card"><span>Verified</span><strong>{report.verification_summary?.verified||0}</strong></article><article className="card stat-card"><span>Primary only</span><strong>{report.verification_summary?.primary_only||0}</strong></article></div><div className="card"><h2>Notable Outliers</h2><div className="outlier-list">{(report.outliers||[]).map((o:any)=><div className="outlier-row" key={o.symbol}><div><strong>{o.symbol}</strong><p className="muted">{o.reason}</p></div><span>{o.score?.toFixed(1)}</span></div>)}</div></div><div className="card"><h2>Top Market News</h2>{(report.top_market_news||[]).map((n:News)=><a className="news-card-inline" href={n.url} target="_blank" key={n.url}><strong>{n.title}</strong><span>{n.domain}</span></a>)}</div></>}</section>}
 {active==="Markets"&&<section><div className="card"><h2>Markets</h2><p className="muted">Stored data loads automatically. Manual refreshes are independent.</p><div className="ticker-add-row"><div className="search-wrap"><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker or company"/>{search.length>0&&<div className="search-results">{search.map(r=><button key={`${r.symbol}-${r.exchange}`} onClick={()=>add(r.symbol)}><strong>{r.symbol}</strong><span>{r.name}</span></button>)}</div>}</div><button className="btn" onClick={()=>add()}>Add</button></div><div className="view-toggle"><button className={`toggle ${view==="grid"?"active":""}`} onClick={()=>setView("grid")}>Comparison grid</button><button className={`toggle ${view==="cards"?"active":""}`} onClick={()=>setView("cards")}>Cards</button></div></div>{view==="grid"?<div className="card comparison-wrap"><table className="comparison-table"><thead><tr><th>Ticker</th><th>Price</th><th>Day</th><th>7D</th><th>30D</th><th>YTD</th><th>100MA</th><th>200MA</th><th>Rel Vol</th><th></th></tr></thead><tbody>{tickers.map(s=>{const d=market[s];return <tr key={s}><td><strong>{s}</strong></td><td>{d?money(d.price):"—"}</td><td className={(d?.change_percent??0)>=0?"positive":"negative"}>{d?pct(d.change_percent):"—"}</td><td>{d?pct(d.seven_day_percent):"—"}</td><td>{d?pct(d.thirty_day_percent):"—"}</td><td>{d?pct(d.ytd_percent):"—"}</td><td>{d?money(d.ma100):"—"}</td><td>{d?money(d.ma200):"—"}</td><td>{d?.relative_volume!=null?`${d.relative_volume.toFixed(2)}x`:"—"}</td><td><button className="btn" disabled={!!loading[s]} onClick={()=>loadOne(s)}>{loading[s]?"Loading":"Refresh"}</button></td></tr>})}</tbody></table></div>:<div className="grid ticker-grid">{tickers.map(s=>{const d=market[s];return <article className="card ticker-card" key={s}><div className="row"><strong className="ticker-symbol">{s}</strong><button className="btn danger" onClick={()=>remove(s)}>Remove</button></div>{d?<div className="market-metrics"><div className="price-line"><strong>{money(d.price)}</strong><span className={(d.change_percent??0)>=0?"positive":"negative"}>{pct(d.change_percent)}</span></div><div className="metric-grid"><span>7D <strong>{pct(d.seven_day_percent)}</strong></span><span>30D <strong>{pct(d.thirty_day_percent)}</strong></span><span>100MA <strong>{money(d.ma100)}</strong></span><span>200MA <strong>{money(d.ma200)}</strong></span></div></div>:<p className="muted">No stored snapshot</p>}<button className="btn load-market" disabled={!!loading[s]} onClick={()=>loadOne(s)}>{loading[s]?"Loading...":"Refresh market data"}</button>{errors[s]&&<div className="market-error">{errors[s]}</div>}</article>})}</div>}</section>}
 {active==="World News"&&<section><div className="card"><div className="row"><div><h2>World News Intelligence</h2><p className="muted">{newsStatus}</p></div><button className="btn" onClick={()=>loadNews()}>Refresh</button></div><div className="topic-filter">{topics.map(t=><button className={`toggle ${topic===t?"active":""}`} key={t} onClick={()=>{setTopic(t);loadNews(t)}}>{t}</button>)}</div></div><div className="news-list">{news.map(n=><a className="card news-card" href={n.url} target="_blank" rel="noreferrer" key={n.url}><strong>{n.title}</strong><div className="chips">{(n.topics||[]).map(x=><span className="chip" key={x}>{x}</span>)}{(n.sectors||[]).map(x=><span className="chip" key={x}>{x}</span>)}</div><p className="why">{n.why_it_matters}</p><p className="source-line">Relevance {n.relevance_score??"—"}/100 · {n.domain||"Source"} · {n.source_country||""} · {n.published_at||""}</p></a>)}</div></section>}
 {active==="Large Flow"&&<section><div className="card"><h2>Large Flow</h2><p className="muted">Storage and analysis infrastructure are ready; the remaining limitation is low-cost trade-level data licensing.</p></div><div className="flow-research"><article className="card research-card"><h2>Equity blocks</h2><p>FINRA public OTC/ATS data provides delayed institutional context and historical baselines.</p></article><article className="card research-card"><h2>Options flow</h2><p>Trade-level options flow requires options transactions, NBBO-at-trade, open interest, premium and conditions.</p></article><article className="card research-card"><h2>Planned scoring</h2><p>Size, execution aggressiveness, volume/OI, persistence and market context stay separate from directional inference.</p></article></div></section>}
 {active==="Macro"&&<section><div className="card row"><div><h2>Sector Rotation</h2><p className="muted">{macroStatus}</p></div><button className="btn" onClick={loadMacro}>Refresh</button></div>{rotation&&<><SectorPerformance sectors={rotation.sectors}/><div className="card"><h2>What is rotating?</h2><p>{rotation.evidence.join(" ")||"More sector snapshots are needed before rotation can be measured."}</p><p className="muted">{rotation.methodology}</p></div><div className="grid report-columns"><div className="card"><h2>Leadership</h2><div className="rotation-list">{rotation.leaders.map((r:any)=><div className="rotation-item leader" key={r.symbol}><div className="row"><strong>{r.name} ({r.symbol})</strong><span>{r.rotation_score}</span></div><p className="muted">Day {pct(r.day_percent)} · 7D {pct(r.seven_day_percent)} · 30D {pct(r.thirty_day_percent)} · RelVol {r.relative_volume?.toFixed(2)??"—"}x</p></div>)}</div></div><div className="card"><h2>Weakness / Sources of Capital</h2><div className="rotation-list">{rotation.laggards.map((r:any)=><div className="rotation-item laggard" key={r.symbol}><div className="row"><strong>{r.name} ({r.symbol})</strong><span>{r.rotation_score}</span></div><p className="muted">Day {pct(r.day_percent)} · 7D {pct(r.seven_day_percent)} · 30D {pct(r.thirty_day_percent)}</p></div>)}</div></div></div><div className="card"><h2>Possible reasons</h2>{rotation.possible_reasons.length?rotation.possible_reasons.map((r:any)=><a className="news-card-inline" href={r.url} target="_blank" key={r.url}><strong>{r.title}</strong><span>{r.inference} · confidence: {r.confidence}</span></a>):<p className="muted">No sufficiently matched catalyst in the current feed.</p>}</div></>}<MacroHistory/></section>}
 {active==="Settings"&&<section className="card"><h2>Settings</h2><p className="muted">Provider status, report configuration, thresholds and alerts will live here.</p></section>}</main>}
