"use client";
import {useEffect,useState} from "react";
import MacroHistory from "./macro-history";
import HomeDashboard from "./home-dashboard";
import SectorPerformance from "./sector-performance";
import BackendStatus from "./backend-status";
import CurrencyPanel from "./currency-panel";
import LargeFlow from "./large-flow";
import MarketFlags from "./market-flags";
import ReportOutliers from "./report-outliers";
import {MacroLeadership} from "./macro-intelligence";
import {MarketGrid} from "./market-metrics";
import {ErrorState,LoadingState} from "./loading-state";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
const TABS=["Report","Markets","World News","Large Flow","Macro","Settings"];
type Market={symbol:string;price:number|null;change_percent:number|null;seven_day_percent:number|null;thirty_day_percent:number|null;ytd_percent:number|null;ma50?:number|null;ma100:number|null;ma200:number|null;price_vs_ma50_percent?:number|null;price_vs_ma100_percent?:number|null;price_vs_ma200_percent?:number|null;all_time_high?:number|null;price_vs_ath_percent?:number|null;williams_r_14?:number|null;pe_ratio?:number|null;peg_ratio?:number|null;price_to_sales_ratio?:number|null;market_cap?:number|null;sector?:string|null;relative_volume:number|null;volume:number|null;high_52_week:number|null;low_52_week:number|null;provider:string;source_url:string;as_of:string|null;verification_status:string};
type News={title:string;url:string;domain?:string;source_country?:string;published_at?:string;topics?:string[];sectors?:string[];relevance_score?:number;why_it_matters?:string};
type Rotation={methodology:string;sectors:any[];leaders:any[];laggards:any[];evidence:string[];possible_reasons:any[];technical_reasons?:any[];reasoning_methodology?:string;news_context?:any;tracking_status?:any};
function errText(context:string,e:unknown){const raw=e instanceof Error?e.message:String(e||"Unknown error");if(raw.includes("timed out")||raw.includes("AbortError"))return `${context} timed out. Check the internet connection and retry.`;if(raw.includes("Failed to fetch")||raw.includes("NetworkError"))return `${context} could not reach the server. Check the internet connection.`;if(raw.includes("HTTP 502")||raw.includes("HTTP 503"))return `${context} is temporarily unavailable from the backend/provider.`;return `${context}: ${raw}`}

export default function Home(){
 const[tickers,setTickers]=useState<string[]>([]),[active,setActive]=useState("Report"),[status,setStatus]=useState("Connecting…"),[initializing,setInitializing]=useState(true),[initialError,setInitialError]=useState("");
 const[market,setMarket]=useState<Record<string,Market>>({}),[loading,setLoading]=useState<Record<string,boolean>>({}),[errors,setErrors]=useState<Record<string,string>>({});
 const[query,setQuery]=useState(""),[search,setSearch]=useState<any[]>([]),[searchError,setSearchError]=useState(""),[marketActionError,setMarketActionError]=useState("");
 const[news,setNews]=useState<News[]>([]),[topic,setTopic]=useState("All"),[newsLoading,setNewsLoading]=useState(false),[newsError,setNewsError]=useState(""),[newsStatus,setNewsStatus]=useState("Not loaded");
 const[rotation,setRotation]=useState<Rotation|null>(null),[macroLoading,setMacroLoading]=useState(false),[macroError,setMacroError]=useState(""),[macroStatus,setMacroStatus]=useState("Not loaded");
 const[report,setReport]=useState<any>(null),[reportLoading,setReportLoading]=useState(false),[reportError,setReportError]=useState(""),[reportStatus,setReportStatus]=useState("Not loaded");
 const[currencies,setCurrencies]=useState<any>(null),[currencyError,setCurrencyError]=useState("");
 const[flowData,setFlowData]=useState<any>({events:[],provider:"SquawkFlow",usage:{}}),[flowLoading,setFlowLoading]=useState(false),[flowError,setFlowError]=useState("");

 async function json(url:string,options?:RequestInit){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{cache:"no-store",...options,signal:controller.signal});let d:any;try{d=await r.json()}catch{throw new Error(`HTTP ${r.status}: invalid server response`)}if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);setStatus(current=>current==="Connection problem"?"Backend connected":current);return d}catch(e:any){if(e?.name==="AbortError")throw new Error("Request timed out after 15 seconds");throw e}finally{clearTimeout(timer)}}
 async function init(){setInitializing(true);setInitialError("");setStatus("Connecting…");const [w,l]=await Promise.allSettled([json(`${API}/api/v1/watchlist`),json(`${API}/api/v1/markets/latest`)]);if(w.status==="fulfilled")setTickers(w.value.tickers||[]);if(l.status==="fulfilled"){const m:Record<string,Market>={};(l.value.markets||[]).forEach((x:Market)=>m[x.symbol]=x);setMarket(m)}const failures=[];if(w.status==="rejected")failures.push(errText("Watchlist",w.reason));if(l.status==="rejected")failures.push(errText("Market snapshots",l.reason));if(failures.length){setInitialError(failures.join(" "));setStatus(w.status==="rejected"&&l.status==="rejected"?"Connection problem":"Backend connected · partial data")}else setStatus("Backend connected");setInitializing(false);loadReport();loadMacro();loadCurrencies();loadFlow()}
 useEffect(()=>{init()},[]);
 useEffect(()=>{const cards=Array.from(document.querySelectorAll<HTMLElement>(".reveal-card"));if(!cards.length)return;const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).classList.add("in-view");observer.unobserve(entry.target)}}),{threshold:.06,rootMargin:"0px 0px -18px 0px"});cards.forEach((card,index)=>{card.classList.remove("in-view");card.style.setProperty("--reveal-delay",`${Math.min(index%8,7)*42}ms`);observer.observe(card)});return()=>observer.disconnect()},[active,report,rotation,news,currencies,flowData]);
 useEffect(()=>{if(query.trim().length<2){setSearch([]);setSearchError("");return}const t=setTimeout(async()=>{setSearchError("");try{const d=await json(`${API}/api/v1/securities/search?q=${encodeURIComponent(query)}`);setSearch(d.results||[])}catch(e){setSearch([]);setSearchError(errText("Ticker search",e))}},450);return()=>clearTimeout(t)},[query]);
 async function loadOne(s:string){setLoading(x=>({...x,[s]:true}));setErrors(x=>({...x,[s]:""}));try{const d=await json(`${API}/api/v1/markets/${encodeURIComponent(s)}?verify=false`);setMarket(x=>({...x,[s]:d}))}catch(e){setErrors(x=>({...x,[s]:errText(`${s} market data`,e)}))}finally{setLoading(x=>({...x,[s]:false}))}}
 async function add(s?:string){const sym=(s||query).trim().toUpperCase();if(!sym)return;setMarketActionError("");try{await json(`${API}/api/v1/watchlist`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:sym})});setQuery("");setSearch([]);const w=await json(`${API}/api/v1/watchlist`);setTickers(w.tickers||[]);loadOne(sym)}catch(e){setMarketActionError(errText(`Adding ${sym}`,e))}}
 async function remove(s:string){setMarketActionError("");try{await json(`${API}/api/v1/watchlist/${encodeURIComponent(s)}`,{method:"DELETE"});setTickers(x=>x.filter(y=>y!==s));setMarket(x=>{const n={...x};delete n[s];return n})}catch(e){setMarketActionError(errText(`Removing ${s}`,e))}}
 async function loadNews(t=topic){setNewsLoading(true);setNewsError("");setNewsStatus("Loading news intelligence…");try{const u=t==="All"?`${API}/api/v1/news/world?limit=40`:`${API}/api/v1/news/world?limit=40&topic=${encodeURIComponent(t)}`;const d=await json(u);setNews(d.articles||[]);setNewsStatus(`${d.articles?.length||0} intelligence items · ${d.provider}`)}catch(e){const m=errText("World News",e);setNewsError(m);setNewsStatus("Load failed")}finally{setNewsLoading(false)}}
 async function loadCurrencies(){setCurrencyError("");try{setCurrencies(await json(`${API}/api/v1/macro/currencies`))}catch(e){setCurrencyError(errText("World currencies",e))}}
 async function loadMacro(){setMacroLoading(true);setMacroError("");setMacroStatus("Loading rotation data…");try{const d=await json(`${API}/api/v1/macro/rotation`);setRotation(d);const pending=d.tracking_status?.pending_backfill?.length||0;setMacroStatus(`${d.sectors?.length||0} tracked groups${pending?` · ${pending} backfilling from the latest completed session`:""}`)}catch(e){const m=errText("Macro rotation",e);setMacroError(m);setMacroStatus("Load failed")}finally{setMacroLoading(false)}}
 async function loadFlow(){setFlowLoading(true);setFlowError("");try{setFlowData(await json(`${API}/api/v1/flow/recent?limit=100`))}catch(e){setFlowError(errText("Large Flow",e))}finally{setFlowLoading(false)}}
 async function loadReport(){setReportLoading(true);setReportError("");setReportStatus("Loading report…");try{const d=await json(`${API}/api/v1/report/current`);setReport(d);if(d.currencies?.rates)setCurrencies(d.currencies);setReportStatus(`Generated ${new Date(d.generated_at).toLocaleString()}`)}catch(e){const m=errText("Daily Report",e);setReportError(m);setReportStatus("Load failed")}finally{setReportLoading(false)}}
 async function saveReport(){setReportError("");try{const d=await json(`${API}/api/v1/report/generate`,{method:"POST"});setReport(d);setReportStatus(`Saved report #${d.id}`)}catch(e){setReportError(errText("Saving report snapshot",e))}}
 function selectTab(t:string){if(t===active)return;setActive(t);if(t==="World News"&&!news.length&&!newsLoading)loadNews();if(t==="Macro"){if(!rotation&&!macroLoading)loadMacro();if(!currencies)loadCurrencies()}if(t==="Report"&&!report&&!reportLoading)loadReport();if(t==="Large Flow"&&!flowData.events?.length&&!flowLoading)loadFlow()}
 const topics=["All","AI & Semiconductors","Rates & Central Banks","Energy & Commodities","Trade & Geopolitics","Economy & Inflation"];
 if(initializing)return <main className="container startup-screen"><div className="brand-lockup"><div className="brand-mark">⌁</div><div><h1>Daily Report</h1><p className="muted">Market intelligence dashboard</p></div></div><LoadingState title="Starting Daily Report" detail="Connecting to the backend, loading your watchlist, and restoring the latest market snapshots."/></main>;

 return <main className="container"><header className="app-header"><div className="brand-lockup"><div className="brand-mark">⌁</div><div><h1>Daily Report</h1><p className="muted">Market intelligence dashboard</p></div></div><span className={`status ${status.startsWith("Backend connected")?"ok":""}`}>{status}</span></header>
 {initialError&&<ErrorState title="Initial data load was incomplete" detail={initialError} onRetry={init}/>}<nav className="nav">{TABS.map(t=><button key={t} className={active===t?"active":""} onClick={()=>selectTab(t)}>{t}</button>)}</nav>
 {active==="Report"&&<section className="tab-panel"><HomeDashboard market={market} rotation={rotation} onOpenMarkets={()=>selectTab("Markets")} onOpenMacro={()=>selectTab("Macro")}/><div className="card row report-utility reveal-card"><div><h2>Daily Report</h2><p className="muted">{reportStatus}</p></div><div className="report-actions"><button className="btn" disabled={reportLoading} onClick={loadReport}>{reportLoading?"Loading…":"Refresh"}</button><button className="btn" onClick={saveReport}>Save snapshot</button></div></div>{reportLoading&&!report&&<LoadingState title="Loading report" detail="Compiling stored market data, macro context, currencies, and market news."/>}{reportError&&<ErrorState title="Report unavailable" detail={reportError} onRetry={loadReport}/>} {report&&<><div className="report-summary-grid"><article className="card stat-card reveal-card"><span>Watchlist</span><strong>{report.watchlist_count}</strong></article><article className="card stat-card reveal-card"><span>Loaded</span><strong>{report.market_data_count}</strong></article><article className="card stat-card reveal-card"><span>Verified</span><strong>{report.verification_summary?.verified||0}</strong></article><article className="card stat-card reveal-card"><span>Primary only</span><strong>{report.verification_summary?.primary_only||0}</strong></article></div><CurrencyPanel data={report.currencies||currencies}/>{currencyError&&<ErrorState title="Currency data unavailable" detail={currencyError} onRetry={loadCurrencies}/>}<ReportOutliers items={report.outliers||[]}/><div className="card reveal-card"><h2>Top Market News</h2>{(report.top_market_news||[]).map((n:News)=><a className="news-card-inline" href={n.url} target="_blank" key={n.url}><strong>{n.title}</strong><span>{n.domain}</span></a>)}</div></>}</section>}
 {active==="Markets"&&<section className="tab-panel"><div className="card reveal-card"><h2>Markets</h2><p className="muted">Market snapshots now carry the current Williams %R from the same daily-history pull. Valuation ratios use a persistent Alpha Vantage cache; missing P/E, P/S and PEG can be derived from the same fundamental payload where the required inputs exist.</p></div><MarketGrid tickers={tickers} market={market} loading={loading} onRefresh={loadOne} onRemove={remove} errors={errors}/><div className="card reveal-card ticker-add-card"><div><span className="eyebrow">Watchlist</span><h2>Add ticker</h2><p className="muted">Search by ticker or company. New symbols are provider-validated before being added.</p></div><div className="ticker-add-row"><div className="search-wrap"><input className="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker or company"/>{search.length>0&&<div className="search-results">{search.map(r=><button key={`${r.symbol}-${r.exchange}`} onClick={()=>add(r.symbol)}><strong>{r.symbol}</strong><span>{r.name}</span></button>)}</div>}</div><button className="btn" onClick={()=>add()}>Add</button></div>{searchError&&<div className="inline-error">{searchError}</div>}{marketActionError&&<ErrorState title="Watchlist update failed" detail={marketActionError}/>}</div><MarketFlags tickers={tickers} market={market} rotation={rotation} flowEvents={flowData.events||[]}/></section>}
 {active==="World News"&&<section className="tab-panel"><div className="card reveal-card"><div className="row"><div><h2>World News Intelligence</h2><p className="muted">{newsStatus}</p></div><button className="btn" disabled={newsLoading} onClick={()=>loadNews()}>{newsLoading?"Loading…":"Refresh"}</button></div><div className="topic-filter">{topics.map(t=><button className={`toggle ${topic===t?"active":""}`} key={t} onClick={()=>{setTopic(t);loadNews(t)}}>{t}</button>)}</div></div>{newsLoading&&!news.length&&<LoadingState title="Loading World News" detail={`Retrieving and classifying ${topic==="All"?"market-relevant global stories":topic}.`}/>} {newsError&&<ErrorState title="World News unavailable" detail={newsError} onRetry={()=>loadNews(topic)}/>}<div className="news-list">{news.map(n=><a className="card news-card reveal-card" href={n.url} target="_blank" rel="noreferrer" key={n.url}><strong>{n.title}</strong><div className="chips">{(n.topics||[]).map(x=><span className="chip" key={x}>{x}</span>)}{(n.sectors||[]).map(x=><span className="chip" key={x}>{x}</span>)}</div><p className="why">{n.why_it_matters}</p><p className="source-line">Relevance {n.relevance_score??"—"}/100 · {n.domain||"Source"} · {n.source_country||""} · {n.published_at||""}</p></a>)}</div></section>}
 {active==="Large Flow"&&<LargeFlow data={flowData} loading={flowLoading} error={flowError} onRefresh={loadFlow} market={market}/>} 
 {active==="Macro"&&<section className="tab-panel"><div className="card row reveal-card"><div><h2>Sector Rotation</h2><p className="muted">{macroStatus}</p></div><button className="btn" disabled={macroLoading} onClick={()=>{loadMacro();loadCurrencies()}}>{macroLoading?"Loading…":"Refresh"}</button></div>{macroLoading&&!rotation&&<LoadingState title="Loading Macro" detail="Restoring sector performance, leadership, laggards, catalyst matches, and technical context."/>}{macroError&&<ErrorState title="Macro data unavailable" detail={macroError} onRetry={loadMacro}/>}<CurrencyPanel data={currencies}/>{currencyError&&<ErrorState title="Currency data unavailable" detail={currencyError} onRetry={loadCurrencies}/>} {rotation&&<><SectorPerformance sectors={rotation.sectors}/>{rotation.tracking_status?.pending_backfill?.length>0&&<div className="card reveal-card backfill-note"><strong>Macro history backfill in progress</strong><p className="muted">Adding {rotation.tracking_status.pending_backfill.join(", ")} from the latest completed market session. All snapshots use their provider `as_of` date so closed-market backfill is not mixed with a newer timeframe.</p></div>}<div className="card reveal-card"><h2>What is rotating?</h2><p>{rotation.evidence.join(" ")||"More sector snapshots are needed before rotation can be measured."}</p><p className="muted">{rotation.methodology}</p></div><MacroLeadership rotation={rotation}/></>}<MacroHistory/></section>}
 {active==="Settings"&&<section className="tab-panel"><BackendStatus/></section>}</main>}
