"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:Math.abs(Number(v))>=1e6?`$${(Number(v)/1e6).toFixed(2)}M`:Number(v).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2});
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;const cls=(v:any)=>v==null?"":Number(v)>=0?"positive":"negative";
const qty=(v:any)=>v==null?"—":Number(v).toLocaleString(undefined,{maximumFractionDigits:4});
function go(name:string){window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:name}))}
function Spark({points}:{points:any[]}){if(!points?.length)return <div className="empty-spark">History begins as daily live snapshots accumulate.</div>;const vals=points.map(x=>Number(x.market_value||0)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const d=vals.map((v,i)=>`${i?"L":"M"} ${(i/(Math.max(vals.length-1,1)))*100} ${90-((v-min)/span)*80}`).join(" ");return <svg className="history-spark" viewBox="0 0 100 100" preserveAspectRatio="none"><path d={d} fill="none" vectorEffect="non-scaling-stroke"/></svg>}

export default function PortfolioWorkspaceV3(){
 const[list,setList]=useState<any[]>([]),[id,setId]=useState<number|null>(null),[data,setData]=useState<any>(null),[analytics,setAnalytics]=useState<any>(null),[revisions,setRevisions]=useState<any[]>([]),[tab,setTab]=useState("Overview"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[newName,setNewName]=useState(""),[newBrokerage,setNewBrokerage]=useState(""),[newCash,setNewCash]=useState("0"),[sym,setSym]=useState(""),[shares,setShares]=useState(""),[cost,setCost]=useState(""),[note,setNote]=useState("");
 async function loadList(){setLoading(true);setError("");try{const d=await api("/api/v1/portfolios"),rows=d.portfolios||[];setList(rows);let chosen=Number(localStorage.getItem("dailyReportPortfolioId")||0)||rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null;if(chosen&&!rows.some((x:any)=>x.id===chosen))chosen=rows[0]?.id||null;setId(chosen);if(chosen)await loadDetail(chosen)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function loadDetail(pid:number){try{const[d,a,r]=await Promise.all([api(`/api/v1/portfolios/${pid}`),api(`/api/v1/portfolios/${pid}/analytics`),api(`/api/v1/portfolios/${pid}/revisions`)]);setData(d);setAnalytics(a);setRevisions(r.revisions||[]);localStorage.setItem("dailyReportPortfolioId",String(pid))}catch(e:any){setError(e.message)}}
 useEffect(()=>{loadList()},[]);useEffect(()=>{if(!id)return;const t=setInterval(()=>loadDetail(id),60000);return()=>clearInterval(t)},[id]);
 async function switchP(pid:number){setId(pid);setLoading(true);await loadDetail(pid);setLoading(false)}
 async function savePosition(e:FormEvent){e.preventDefault();if(!id||!sym)return;await api(`/api/v1/portfolios/${id}/positions/live`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:sym.toUpperCase(),shares:Number(shares),average_cost:Number(cost),note:note||null})});setSym("");setShares("");setCost("");setNote("");await loadDetail(id);await loadList()}
 async function createPortfolio(e:FormEvent){e.preventDefault();if(!newName.trim())return;const d=await api("/api/v1/portfolios",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName.trim(),brokerage:newBrokerage||null,cash:Number(newCash||0)})});setNewName("");setNewBrokerage("");setNewCash("0");await loadList();setId(d.id);await loadDetail(d.id)}
 const holdings=data?.holdings||[],portfolio=data?.portfolio,baseline=data?.baseline;const sorted=useMemo(()=>[...holdings].sort((a:any,b:any)=>(b.market_value||0)-(a.market_value||0)),[holdings]);
 return <section className="tab-panel v3-workspace portfolio-v3"><div className="card suite-hero"><div><span className="eyebrow">Live multi-portfolio tracking</span><h2>{portfolio?.name||"Portfolio"}</h2><p className="muted">Starting shares, average cost and baseline values remain fixed. Live prices, weights, totals and unrealized P/L update from shared Markets data.</p></div><div className="portfolio-switch"><select className="search" value={id??""} onChange={e=>switchP(Number(e.target.value))}>{list.map(p=><option value={p.id} key={p.id}>{p.name}{p.brokerage?` · ${p.brokerage}`:""}</option>)}</select><button className="btn" onClick={()=>id&&loadDetail(id)} disabled={!id||loading}>{loading?"Updating…":"Refresh live"}</button></div></div>
  <div className="subtab-bar">{["Overview","Holdings","Risk","History","Manage"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Portfolio unavailable</strong><span>{error}</span></div>}
  {data&&tab==="Overview"&&<div className="v3-stack"><div className="portfolio-summary-grid"><article className="card stat-card"><span>Live account value</span><strong>{money(data.market_value)}</strong></article><article className="card stat-card"><span>Invested</span><strong>{money(data.invested_value)}</strong></article><article className="card stat-card"><span>Cash</span><strong>{money(portfolio.cash)}</strong><small>{data.cash_percent?.toFixed?.(1)}%</small></article><article className="card stat-card"><span>Unrealized P/L</span><strong className={cls(data.unrealized_pl)}>{money(data.unrealized_pl)}</strong><small className={cls(data.unrealized_percent)}>{pct(data.unrealized_percent)}</small></article><article className="card stat-card"><span>Portfolio beta</span><strong>{analytics?.portfolio_beta_spy??"—"}</strong><small>vs SPY</small></article><article className="card stat-card"><span>Ann. volatility</span><strong>{analytics?.annualized_volatility_percent==null?"—":`${analytics.annualized_volatility_percent}%`}</strong></article></div>
   <details className="card methodology-dropdown" open><summary><div><span className="eyebrow">Largest positions</span><strong>Current concentration</strong></div><b>▾</b></summary><div className="mini-grid">{sorted.slice(0,8).map((h:any)=><button key={h.symbol} onClick={()=>setTab("Holdings")}><strong>{h.symbol}</strong><span>{money(h.market_value)}</span><b>{h.account_percent?.toFixed?.(2)}%</b><small className={cls(h.unrealized_percent)}>{pct(h.unrealized_percent)} return</small></button>)}</div></details>
   {baseline&&<details className="card methodology-dropdown"><summary><strong>Tracking baseline</strong><span className="muted">preserved</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Initial cash</i><strong>{money(baseline.initial_cash)}</strong></span><span><i>Initial invested</i><strong>{money(baseline.initial_invested_value)}</strong></span><span><i>Initial total</i><strong>{money(baseline.initial_total_value)}</strong></span><span><i>Recorded</i><strong>{baseline.recorded_at?new Date(baseline.recorded_at).toLocaleDateString():"—"}</strong></span></div></details>}
  </div>}
  {data&&tab==="Holdings"&&<div className="portfolio-position-list">{holdings.map((h:any)=><details className="card portfolio-holding-v3" key={h.symbol}><summary><div><strong>{h.symbol}</strong><small>{h.market?.sector||""}</small></div><span>{money(h.price)}<small>{h.live?.provider||h.market?.provider||""}</small></span><span>{money(h.market_value)}<small>{h.account_percent?.toFixed?.(2)}%</small></span><span className={cls(h.unrealized_pl)}>{money(h.unrealized_pl)}<small>{pct(h.unrealized_percent)}</small></span><b>▾</b></summary><div className="holding-detail-v3"><details className="methodology-dropdown" open><summary><strong>Market & technicals</strong><b>▾</b></summary><div className="metric-tile-grid">{[["1D",pct(h.market?.change_percent)],["7D",pct(h.market?.seven_day_percent)],["30D",pct(h.market?.thirty_day_percent)],["Williams %R",h.market?.williams_r_14==null?"—":Number(h.market.williams_r_14).toFixed(1)],["50MA",money(h.market?.ma50)],["100MA",money(h.market?.ma100)],["200MA",money(h.market?.ma200)],["Rel volume",h.market?.relative_volume==null?"—":`${Number(h.market.relative_volume).toFixed(2)}x`]].map(([k,v])=><span key={k}><i>{k}</i><strong>{v}</strong></span>)}</div><div className="metric-links"><button className="text-btn" onClick={()=>go("Markets")}>Markets →</button><button className="text-btn" onClick={()=>go("Research")}>Research →</button></div></details><details className="methodology-dropdown"><summary><strong>Valuation & scores</strong><b>▾</b></summary><div className="metric-tile-grid">{[["P/E",h.market?.pe_ratio],["P/S",h.market?.price_to_sales_ratio],["PEG",h.market?.peg_ratio],["Market cap",money(h.market?.market_cap)],["Buy score",h.buy_score],["Sell score",h.sell_score]].map(([k,v]:any)=><span key={k}><i>{k}</i><strong>{typeof v==="number"?v.toFixed(2):v??"—"}</strong></span>)}</div></details><details className="methodology-dropdown"><summary><strong>Position & baseline</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Shares</i><strong>{qty(h.shares)}</strong></span><span><i>Current avg cost</i><strong>{money(h.average_cost)}</strong></span><span><i>Cost basis</i><strong>{money(h.cost_basis)}</strong></span><span><i>Initial shares</i><strong>{qty(h.baseline?.shares)}</strong></span><span><i>Initial avg cost</i><strong>{money(h.baseline?.average_cost)}</strong></span><span><i>Initial market value</i><strong>{money(h.baseline?.market_value)}</strong></span></div></details></div></details>)}</div>}
  {data&&tab==="Risk"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Beta vs SPY</span><strong>{analytics?.portfolio_beta_spy??"—"}</strong></article><article className="card stat-card"><span>Annualized vol</span><strong>{analytics?.annualized_volatility_percent==null?"—":`${analytics.annualized_volatility_percent}%`}</strong></article><article className="card stat-card"><span>Historical max DD</span><strong className="negative">{analytics?.historical_max_drawdown_percent==null?"—":`${analytics.historical_max_drawdown_percent}%`}</strong></article><article className="card stat-card"><span>Cash weight</span><strong>{analytics?.cash_weight??data.cash_percent}%</strong></article></div><details className="card methodology-dropdown" open><summary><strong>Approximate risk contribution</strong><span className="muted">weight × volatility</span><b>▾</b></summary><div className="relative-grid">{(analytics?.risk_contribution||[]).map((x:any)=><div key={x.symbol}><strong>{x.symbol}</strong><span>Weight {x.weight}%</span><b>{x.risk_contribution==null?"—":`${x.risk_contribution}% risk`}</b></div>)}</div></details><details className="card methodology-dropdown"><summary><strong>Correlation clusters</strong><span>{analytics?.correlation_clusters?.length||0} pairs ≥ .65</span><b>▾</b></summary><div className="mini-grid">{(analytics?.correlation_clusters||[]).map((x:any)=><span key={`${x.a}-${x.b}`}><strong>{x.a} ↔ {x.b}</strong><b>{x.correlation}</b></span>)}</div></details><details className="card methodology-dropdown"><summary><strong>Sector concentration</strong><b>▾</b></summary><div className="mini-grid">{(analytics?.sector_exposure||[]).map((x:any)=><span key={x.sector}><strong>{x.sector}</strong><b>{x.weight}%</b></span>)}</div></details><details className="card methodology-dropdown"><summary><strong>Risk methodology & limitations</strong><b>▾</b></summary><p>{analytics?.methodology}</p><p className="muted">Exact ETF constituent overlap and realized tax-lot P/L are not estimated without an authoritative holdings/transaction source; the app leaves those unavailable rather than fabricating them.</p></details></div>}
  {data&&tab==="History"&&<div className="v3-stack"><div className="card"><div className="section-head"><div><span className="eyebrow">Daily account snapshots</span><h3>Portfolio value history</h3></div></div><Spark points={analytics?.history||[]}/><div className="history-row-list">{(analytics?.history||[]).slice(-30).reverse().map((x:any)=><span key={x.as_of}><time>{x.as_of}</time><b>{money(x.market_value)}</b><small>Invested {money(x.invested_value)} · Cash {money(x.cash)}</small></span>)}</div></div><details className="card methodology-dropdown"><summary><strong>Position revision history</strong><span>{revisions.length}</span><b>▾</b></summary><div className="history-row-list">{revisions.map((r:any)=><span key={r.id}><time>{new Date(r.created_at).toLocaleString()}</time><b>{r.symbol} · {qty(r.shares)} sh @ {money(r.average_cost)}</b><small>{r.note||"Position revision"}</small></span>)}</div></details></div>}
  {tab==="Manage"&&<div className="portfolio-editor-grid"><form className="card suite-form" onSubmit={savePosition}><span className="eyebrow">Current portfolio</span><h3>Add / update position</h3><input className="search" value={sym} onChange={e=>setSym(e.target.value.toUpperCase())} placeholder="Ticker"/><input className="search" value={shares} onChange={e=>setShares(e.target.value)} inputMode="decimal" placeholder="Current shares"/><input className="search" value={cost} onChange={e=>setCost(e.target.value)} inputMode="decimal" placeholder="Average cost / share"/><input className="search" value={note} onChange={e=>setNote(e.target.value)} placeholder="Update note"/><button className="btn">Save position</button><p className="muted">The original baseline is retained; edits add a revision record.</p></form><form className="card suite-form" onSubmit={createPortfolio}><span className="eyebrow">Accounts</span><h3>Create portfolio</h3><input className="search" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Portfolio name"/><input className="search" value={newBrokerage} onChange={e=>setNewBrokerage(e.target.value)} placeholder="Brokerage"/><input className="search" value={newCash} onChange={e=>setNewCash(e.target.value)} inputMode="decimal" placeholder="Cash"/><button className="btn">Create portfolio</button></form></div>}
 </section>
}
