"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const email=localStorage.getItem("dailyReportUserEmail")||"",token=localStorage.getItem("dailyReportUserToken")||"";return {...(email?{"X-User-Email":email}:{}),...(token?{"X-User-Token":token}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const money=(v:number|null|undefined)=>v==null?"—":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:Math.abs(v)>=1e6?`$${(v/1e6).toFixed(2)}M`:Math.abs(v)>=1e3?`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:`$${v.toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(2)}%`;
const ratio=(v:number|null|undefined)=>v==null?"—":Number(v).toFixed(2);
const qty=(v:number|null|undefined)=>v==null?"—":Number.isInteger(v)?String(v):Number(v).toFixed(3).replace(/0+$/," ").trim();
const positive=(v:number|null|undefined)=>v==null?"":v>=0?"positive":"negative";

export default function PortfolioWorkspace(){
 const[list,setList]=useState<any[]>([]),[activeId,setActiveId]=useState<number|null>(null),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState("");
 const[newName,setNewName]=useState(""),[newBrokerage,setNewBrokerage]=useState(""),[newCash,setNewCash]=useState("0"),[positionSymbol,setPositionSymbol]=useState(""),[positionShares,setPositionShares]=useState(""),[positionCost,setPositionCost]=useState("");
 async function loadList(){setLoading(true);setError("");try{const d=await api("/api/v1/portfolios");const rows=d.portfolios||[];setList(rows);let chosen=Number(localStorage.getItem("dailyReportPortfolioId")||0)||rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null;if(chosen&&!rows.some((x:any)=>x.id===chosen))chosen=rows[0]?.id||null;setActiveId(chosen);if(chosen)await loadDetail(chosen)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function loadDetail(id:number){setDetailLoading(true);setError("");try{const d=await api(`/api/v1/portfolios/${id}`);setData(d);localStorage.setItem("dailyReportPortfolioId",String(id))}catch(e:any){setError(e.message)}finally{setDetailLoading(false)}}
 useEffect(()=>{loadList()},[]);
 async function switchPortfolio(id:number){setActiveId(id);await loadDetail(id)}
 async function createPortfolio(e:FormEvent){e.preventDefault();if(!newName.trim())return;try{const d=await api("/api/v1/portfolios",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName.trim(),brokerage:newBrokerage.trim()||null,cash:Number(newCash||0)})});setNewName("");setNewBrokerage("");setNewCash("0");await loadList();setActiveId(d.id);await loadDetail(d.id)}catch(e:any){setError(e.message)}}
 async function savePosition(e:FormEvent){e.preventDefault();if(!activeId||!positionSymbol.trim())return;try{await api(`/api/v1/portfolios/${activeId}/positions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:positionSymbol.trim().toUpperCase(),shares:Number(positionShares||0),average_cost:Number(positionCost||0)})});setPositionSymbol("");setPositionShares("");setPositionCost("");await loadDetail(activeId);await loadList()}catch(e:any){setError(e.message)}}
 async function removePosition(symbol:string){if(!activeId)return;try{await api(`/api/v1/portfolios/${activeId}/positions/${encodeURIComponent(symbol)}`,{method:"DELETE"});await loadDetail(activeId);await loadList()}catch(e:any){setError(e.message)}}
 const portfolio=data?.portfolio,holdings=data?.holdings||[];
 const winner=useMemo(()=>[...holdings].sort((a:any,b:any)=>(b.unrealized_percent||-999)-(a.unrealized_percent||-999))[0],[holdings]);
 return <section className="tab-panel portfolio-workspace">
  <div className="card reveal-card portfolio-hero"><div><span className="eyebrow">Multi-account portfolio intelligence</span><h2>{portfolio?.name||"Portfolio"}</h2><p className="muted">Switch between separate portfolios while reusing the same shared market, fundamentals, technical, macro and flow caches.</p></div><div className="portfolio-switch"><label>Portfolio</label><select className="search" value={activeId??""} onChange={e=>switchPortfolio(Number(e.target.value))}>{list.map(p=><option key={p.id} value={p.id}>{p.name}{p.brokerage?` · ${p.brokerage}`:""}</option>)}</select>{detailLoading&&<span className="suite-spinner"><i/>Refreshing</span>}</div></div>
  {error&&<div className="suite-error"><strong>Portfolio data unavailable</strong><span>{error}</span><button className="btn" onClick={loadList}>Retry</button></div>}
  {loading&&!data?<div className="suite-skeleton">{Array.from({length:6}).map((_,i)=><span key={i}/>)}</div>:data&&<>
   <div className="portfolio-summary-grid"><article className="card stat-card reveal-card"><span>Total account</span><strong>{money(data.market_value)}</strong></article><article className="card stat-card reveal-card"><span>Invested</span><strong>{money(data.invested_value)}</strong></article><article className="card stat-card reveal-card"><span>Cash</span><strong>{money(portfolio.cash)}</strong><small>{data.cash_percent?.toFixed?.(1)}%</small></article><article className="card stat-card reveal-card"><span>Unrealized P/L</span><strong className={positive(data.unrealized_pl)}>{money(data.unrealized_pl)}</strong><small className={positive(data.unrealized_percent)}>{pct(data.unrealized_percent)}</small></article><article className="card stat-card reveal-card"><span>Positions</span><strong>{holdings.length}</strong></article><article className="card stat-card reveal-card"><span>Best return</span><strong>{winner?.symbol||"—"}</strong><small className={positive(winner?.unrealized_percent)}>{pct(winner?.unrealized_percent)}</small></article></div>
   {portfolio.source_note&&<div className="card reveal-card portfolio-source-note" data-info-module="portfolio_imported_snapshot"><span className="data-badge cached">IMPORTED ACCOUNT SNAPSHOT</span><p>{portfolio.source_note}</p></div>}
   <div className="card reveal-card portfolio-holdings-card"><div className="section-head"><div><span className="eyebrow">Expandable holdings</span><h2>Positions</h2></div><span className="data-badge cached">MARKET DATA SHARED BY SYMBOL</span></div>
    <div className="portfolio-grid-head"><span>Symbol</span><span>Price</span><span>Value</span><span>Total P/L</span><span>Account</span><span>Quantity</span><span>Cost basis</span><span></span></div>
    <div className="portfolio-position-list">{holdings.map((h:any)=><details className="portfolio-position" key={h.symbol} data-security-symbol={h.symbol}><summary><strong>{h.symbol}<small>{h.market?.name||h.market?.sector||""}</small></strong><span>{money(h.price)}</span><span>{money(h.market_value)}</span><span className={positive(h.unrealized_pl)}>{money(h.unrealized_pl)}<small>{pct(h.unrealized_percent)}</small></span><span>{h.account_percent?.toFixed?.(2)}%</span><span>{qty(h.shares)}</span><span>{money(h.cost_basis)}<small>{money(h.average_cost)} / sh</small></span><b>▾</b></summary>
      <div className="portfolio-position-detail">
       <div className="portfolio-detail-title"><div><span className="eyebrow">Markets-style security detail</span><h3>{h.symbol} · {money(h.price)}</h3></div><div><strong className={positive(h.market?.change_percent)}>{pct(h.market?.change_percent)} today</strong><span className="muted">As of {h.market?.as_of||"imported account snapshot"}</span></div></div>
       <div className="portfolio-market-metrics" data-info-module="portfolio_market_data">
        <Metric label="1D" value={pct(h.market?.change_percent)} cls={positive(h.market?.change_percent)}/><Metric label="7D" value={pct(h.market?.seven_day_percent)} cls={positive(h.market?.seven_day_percent)}/><Metric label="30D" value={pct(h.market?.thirty_day_percent)} cls={positive(h.market?.thirty_day_percent)}/><Metric label="YTD" value={pct(h.market?.ytd_percent)} cls={positive(h.market?.ytd_percent)}/>
        <Metric label="50MA" value={money(h.market?.ma50)} sub={pct(h.market?.price_vs_ma50_percent)}/><Metric label="100MA" value={money(h.market?.ma100)} sub={pct(h.market?.price_vs_ma100_percent)}/><Metric label="200MA" value={money(h.market?.ma200)} sub={pct(h.market?.price_vs_ma200_percent)}/><Metric label="ATH" value={money(h.market?.all_time_high)} sub={pct(h.market?.price_vs_ath_percent)}/>
        <Metric label="P/S" value={ratio(h.market?.price_to_sales_ratio)}/><Metric label="P/E" value={ratio(h.market?.pe_ratio)}/><Metric label="PEG" value={ratio(h.market?.peg_ratio)}/><Metric label="Williams %R" value={h.market?.williams_r_14==null?"—":Number(h.market.williams_r_14).toFixed(1)}/>
        <Metric label="Rel volume" value={h.market?.relative_volume==null?"—":`${Number(h.market.relative_volume).toFixed(2)}x`}/><Metric label="Volume" value={h.market?.volume==null?"—":Number(h.market.volume).toLocaleString()}/><Metric label="52W high" value={money(h.market?.high_52_week)}/><Metric label="52W low" value={money(h.market?.low_52_week)}/>
        <Metric label="Market cap" value={money(h.market?.market_cap)}/><Metric label="Sector" value={h.market?.sector||"—"}/><Metric label="Buy score" value={h.buy_score==null?"—":String(h.buy_score)}/><Metric label="Sell score" value={h.sell_score==null?"—":String(h.sell_score)}/>
       </div>
       <div className="portfolio-imported-grid" data-info-module="portfolio_imported_snapshot"><div><span className="eyebrow">Fidelity snapshot</span><h3>Imported position values</h3></div><span>Last price <b>{money(h.imported_snapshot?.last_price)}</b></span><span>Day gain <b className={positive(h.imported_snapshot?.day_gain)}>{money(h.imported_snapshot?.day_gain)} · {pct(h.imported_snapshot?.day_gain_percent)}</b></span><span>Total gain <b className={positive(h.imported_snapshot?.total_gain)}>{money(h.imported_snapshot?.total_gain)} · {pct(h.imported_snapshot?.total_gain_percent)}</b></span><span>Account weight <b>{h.imported_snapshot?.account_percent?.toFixed?.(2)??"—"}%</b></span></div>
       <div className="portfolio-detail-footer"><span className="muted">{h.market?.provider||"Imported account data"}{h.market?.source_url?" · source available":""}</span>{h.market?.source_url&&<a className="source-link" href={h.market.source_url} target="_blank" rel="noreferrer">Open market-data source ↗</a>}<button className="text-btn" onClick={()=>removePosition(h.symbol)}>Remove from portfolio</button></div>
      </div>
    </details>)}</div>
   </div>
   <div className="portfolio-editor-grid"><form className="card reveal-card suite-form" onSubmit={savePosition}><span className="eyebrow">Active portfolio</span><h2>Add / update position</h2><input className="search" value={positionSymbol} onChange={e=>setPositionSymbol(e.target.value.toUpperCase())} placeholder="Ticker"/><input className="search" inputMode="decimal" value={positionShares} onChange={e=>setPositionShares(e.target.value)} placeholder="Quantity / shares"/><input className="search" inputMode="decimal" value={positionCost} onChange={e=>setPositionCost(e.target.value)} placeholder="Average cost per share"/><button className="btn">Save position</button></form>
    <form className="card reveal-card suite-form" onSubmit={createPortfolio}><span className="eyebrow">Multiple accounts</span><h2>Create another portfolio</h2><input className="search" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Portfolio name"/><input className="search" value={newBrokerage} onChange={e=>setNewBrokerage(e.target.value)} placeholder="Brokerage (optional)"/><input className="search" inputMode="decimal" value={newCash} onChange={e=>setNewCash(e.target.value)} placeholder="Cash"/><button className="btn">Create portfolio</button></form></div>
  </>}
 </section>
}

function Metric({label,value,sub,cls=""}:{label:string;value:string;sub?:string;cls?:string}){return <span><i>{label}</i><strong className={cls}>{value}</strong>{sub&&<small>{sub}</small>}</span>}
