"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const email=localStorage.getItem("dailyReportUserEmail")||"",token=localStorage.getItem("dailyReportUserToken")||"";return {...(email?{"X-User-Email":email}:{}),...(token?{"X-User-Token":token}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const money=(v:number|null|undefined)=>v==null?"—":Math.abs(v)>=1e9?`$${(v/1e9).toFixed(2)}B`:Math.abs(v)>=1e6?`$${(v/1e6).toFixed(2)}M`:Math.abs(v)>=1e3?`$${Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:`$${Number(v).toFixed(2)}`;
const pct=(v:number|null|undefined)=>v==null?"—":`${v>=0?"+":""}${Number(v).toFixed(2)}%`;
const ratio=(v:number|null|undefined)=>v==null?"—":Number(v).toFixed(2);
const qty=(v:number|null|undefined)=>v==null?"—":Number.isInteger(v)?String(v):Number(v).toFixed(3).replace(/0+$/," ").trim();
const pos=(v:number|null|undefined)=>v==null?"":v>=0?"positive":"negative";
function goTab(name:string){Array.from(document.querySelectorAll<HTMLButtonElement>(".nav button")).find(x=>(x.textContent||"").trim()===name)?.click()}

export default function PortfolioWorkspaceV2(){
 const[list,setList]=useState<any[]>([]),[activeId,setActiveId]=useState<number|null>(null),[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[error,setError]=useState("");
 const[newName,setNewName]=useState(""),[newBrokerage,setNewBrokerage]=useState(""),[newCash,setNewCash]=useState("0"),[positionSymbol,setPositionSymbol]=useState(""),[positionShares,setPositionShares]=useState(""),[positionCost,setPositionCost]=useState(""),[positionNote,setPositionNote]=useState("");
 async function loadList(){setLoading(true);setError("");try{const d=await api("/api/v1/portfolios");const rows=d.portfolios||[];setList(rows);let chosen=Number(localStorage.getItem("dailyReportPortfolioId")||0)||rows.find((x:any)=>x.is_default)?.id||rows[0]?.id||null;if(chosen&&!rows.some((x:any)=>x.id===chosen))chosen=rows[0]?.id||null;setActiveId(chosen);if(chosen)await loadDetail(chosen)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function loadDetail(id:number){setDetailLoading(true);setError("");try{const d=await api(`/api/v1/portfolios/${id}`);setData(d);localStorage.setItem("dailyReportPortfolioId",String(id))}catch(e:any){setError(e.message)}finally{setDetailLoading(false)}}
 useEffect(()=>{loadList()},[]);
 useEffect(()=>{if(!activeId)return;const id=setInterval(()=>loadDetail(activeId),60000);return()=>clearInterval(id)},[activeId]);
 async function switchPortfolio(id:number){setActiveId(id);await loadDetail(id)}
 async function createPortfolio(e:FormEvent){e.preventDefault();if(!newName.trim())return;try{const d=await api("/api/v1/portfolios",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:newName.trim(),brokerage:newBrokerage.trim()||null,cash:Number(newCash||0)})});setNewName("");setNewBrokerage("");setNewCash("0");await loadList();setActiveId(d.id);await loadDetail(d.id)}catch(e:any){setError(e.message)}}
 async function savePosition(e:FormEvent){e.preventDefault();if(!activeId||!positionSymbol.trim())return;try{await api(`/api/v1/portfolios/${activeId}/positions/live`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:positionSymbol.trim().toUpperCase(),shares:Number(positionShares||0),average_cost:Number(positionCost||0),note:positionNote||null})});setPositionSymbol("");setPositionShares("");setPositionCost("");setPositionNote("");await loadDetail(activeId);await loadList()}catch(e:any){setError(e.message)}}
 async function removePosition(symbol:string){if(!activeId)return;try{await api(`/api/v1/portfolios/${activeId}/positions/${encodeURIComponent(symbol)}`,{method:"DELETE"});await loadDetail(activeId);await loadList()}catch(e:any){setError(e.message)}}
 const portfolio=data?.portfolio,holdings=data?.holdings||[],baseline=data?.baseline;
 const winner=useMemo(()=>[...holdings].sort((a:any,b:any)=>(b.unrealized_percent||-999)-(a.unrealized_percent||-999))[0],[holdings]);
 const liveVsStart=baseline?.initial_total_value?((data.market_value/baseline.initial_total_value)-1)*100:null;
 return <section className="tab-panel portfolio-workspace">
  <div className="card reveal-card portfolio-hero"><div><span className="eyebrow">Live multi-account holdings</span><h2>{portfolio?.name||"Portfolio"}</h2><p className="muted">Initial position metrics stay fixed. Prices, account weights, portfolio totals and unrealized P/L recalculate from the latest shared market snapshot.</p></div><div className="portfolio-switch"><label>Portfolio</label><select className="search" value={activeId??""} onChange={e=>switchPortfolio(Number(e.target.value))}>{list.map(p=><option key={p.id} value={p.id}>{p.name}{p.brokerage?` · ${p.brokerage}`:""}</option>)}</select><button className="btn" disabled={!activeId||detailLoading} onClick={()=>activeId&&loadDetail(activeId)}>{detailLoading?"Refreshing…":"Refresh live values"}</button></div></div>
  {error&&<div className="suite-error"><strong>Portfolio data unavailable</strong><span>{error}</span><button className="btn" onClick={loadList}>Retry</button></div>}
  {loading&&!data?<div className="suite-skeleton">{Array.from({length:6}).map((_,i)=><span key={i}/>)}</div>:data&&<>
   <div className="portfolio-summary-grid"><article className="card stat-card reveal-card"><span>Live account value</span><strong>{money(data.market_value)}</strong><small>{portfolio.updated_at?`Portfolio updated ${new Date(portfolio.updated_at).toLocaleDateString()}`:""}</small></article><article className="card stat-card reveal-card"><span>Invested value</span><strong>{money(data.invested_value)}</strong></article><article className="card stat-card reveal-card"><span>Cash</span><strong>{money(portfolio.cash)}</strong><small>{data.cash_percent?.toFixed?.(1)}%</small></article><article className="card stat-card reveal-card"><span>Unrealized P/L</span><strong className={pos(data.unrealized_pl)}>{money(data.unrealized_pl)}</strong><small className={pos(data.unrealized_percent)}>{pct(data.unrealized_percent)}</small></article><article className="card stat-card reveal-card"><span>Since tracking start</span><strong className={pos(liveVsStart)}>{pct(liveVsStart)}</strong><small>{baseline?`from ${money(baseline.initial_total_value)}`:"baseline pending"}</small></article><article className="card stat-card reveal-card"><span>Best return</span><strong>{winner?.symbol||"—"}</strong><small className={pos(winner?.unrealized_percent)}>{pct(winner?.unrealized_percent)}</small></article></div>
   {baseline&&<details className="card reveal-card methodology-dropdown" data-info-module="portfolio_imported_snapshot"><summary><div><span className="eyebrow">Tracking baseline</span><strong>Initial portfolio metrics</strong></div><b>▾</b></summary><div className="portfolio-imported-grid"><span>Recorded <b>{baseline.recorded_at?new Date(baseline.recorded_at).toLocaleString():"—"}</b></span><span>Initial cash <b>{money(baseline.initial_cash)}</b></span><span>Initial invested value <b>{money(baseline.initial_invested_value)}</b></span><span>Initial total value <b>{money(baseline.initial_total_value)}</b></span><span>Live total <b>{money(data.market_value)}</b></span></div><p className="muted">This baseline is preserved even when shares or average cost are later edited. Position revisions are stored separately.</p></details>}
   {portfolio.source_note&&<div className="card reveal-card portfolio-source-note"><span className="data-badge cached">IMPORTED SNAPSHOT</span><p>{portfolio.source_note}</p></div>}
   <div className="card reveal-card portfolio-holdings-card"><div className="section-head"><div><span className="eyebrow">Expandable live holdings</span><h2>Positions</h2></div><span className="data-badge live">LIVE FROM SHARED CACHE</span></div><div className="portfolio-grid-head"><span>Symbol</span><span>Price</span><span>Value</span><span>Total P/L</span><span>Account</span><span>Quantity</span><span>Cost basis</span><span></span></div>
    <div className="portfolio-position-list">{holdings.map((h:any)=><details className="portfolio-position" key={h.symbol} data-security-symbol={h.symbol}><summary><strong>{h.symbol}<small>{h.market?.name||h.market?.sector||""}</small></strong><span>{money(h.price)}<small>{h.live?.provider||h.market?.provider||""}</small></span><span>{money(h.market_value)}</span><span className={pos(h.unrealized_pl)}>{money(h.unrealized_pl)}<small>{pct(h.unrealized_percent)}</small></span><span>{h.account_percent?.toFixed?.(2)}%</span><span>{qty(h.shares)}</span><span>{money(h.cost_basis)}<small>{money(h.average_cost)} / sh</small></span><b>▾</b></summary><div className="portfolio-position-detail">
      <div className="portfolio-detail-title"><div><span className="eyebrow">Live security detail</span><h3>{h.symbol} · {money(h.price)}</h3></div><div><strong className={pos(h.market?.change_percent)}>{pct(h.market?.change_percent)} today</strong><span className="muted">As of {h.live?.as_of||h.market?.as_of||"stored"}</span></div></div>
      <details className="methodology-dropdown"><summary><strong>Market & technical metrics</strong><span className="muted">expand</span><b>▾</b></summary><div className="portfolio-market-metrics"><Metric label="1D" value={pct(h.market?.change_percent)} cls={pos(h.market?.change_percent)}/><Metric label="7D" value={pct(h.market?.seven_day_percent)} cls={pos(h.market?.seven_day_percent)}/><Metric label="30D" value={pct(h.market?.thirty_day_percent)} cls={pos(h.market?.thirty_day_percent)}/><Metric label="YTD" value={pct(h.market?.ytd_percent)} cls={pos(h.market?.ytd_percent)}/><Metric label="50MA" value={money(h.market?.ma50)} sub={pct(h.market?.price_vs_ma50_percent)}/><Metric label="100MA" value={money(h.market?.ma100)} sub={pct(h.market?.price_vs_ma100_percent)}/><Metric label="200MA" value={money(h.market?.ma200)} sub={pct(h.market?.price_vs_ma200_percent)}/><Metric label="ATH" value={money(h.market?.all_time_high)} sub={pct(h.market?.price_vs_ath_percent)}/><Metric label="P/S" value={ratio(h.market?.price_to_sales_ratio)}/><Metric label="P/E" value={ratio(h.market?.pe_ratio)}/><Metric label="PEG" value={ratio(h.market?.peg_ratio)}/><Metric label="Williams %R" value={h.market?.williams_r_14==null?"—":Number(h.market.williams_r_14).toFixed(1)}/><Metric label="Rel volume" value={h.market?.relative_volume==null?"—":`${Number(h.market.relative_volume).toFixed(2)}x`}/><Metric label="Market cap" value={money(h.market?.market_cap)}/><Metric label="Buy score" value={h.buy_score==null?"—":String(h.buy_score)}/><Metric label="Sell score" value={h.sell_score==null?"—":String(h.sell_score)}/></div><div className="metric-links"><button className="text-btn" onClick={()=>goTab("Markets")}>Open Markets →</button><button className="text-btn" onClick={()=>goTab("Research")}>Open Research →</button>{h.market?.source_url&&<a className="source-link" href={h.market.source_url} target="_blank" rel="noreferrer">Market source ↗</a>}</div></details>
      <details className="methodology-dropdown"><summary><strong>Initial position baseline</strong><span className="muted">preserved</span><b>▾</b></summary><div className="portfolio-imported-grid"><span>Initial shares <b>{qty(h.baseline?.shares)}</b></span><span>Initial avg cost <b>{money(h.baseline?.average_cost)}</b></span><span>Initial cost basis <b>{money(h.baseline?.cost_basis)}</b></span><span>Initial market price <b>{money(h.baseline?.market_price)}</b></span><span>Initial market value <b>{money(h.baseline?.market_value)}</b></span></div>{h.imported_snapshot?.imported_at&&<p className="muted">Original brokerage snapshot price {money(h.imported_snapshot.last_price)} · total gain then {money(h.imported_snapshot.total_gain)} ({pct(h.imported_snapshot.total_gain_percent)}).</p>}</details>
      <div className="portfolio-detail-footer"><span className="muted">Live values: {h.live?.provider||h.market?.provider||"stored market data"}</span><button className="text-btn danger" onClick={()=>removePosition(h.symbol)}>Remove from portfolio</button></div>
     </div></details>)}</div>
   </div>
   <div className="portfolio-editor-grid"><form className="card reveal-card suite-form" onSubmit={savePosition}><span className="eyebrow">Active portfolio</span><h2>Add / update position</h2><input className="search" value={positionSymbol} onChange={e=>setPositionSymbol(e.target.value.toUpperCase())} placeholder="Ticker"/><input className="search" inputMode="decimal" value={positionShares} onChange={e=>setPositionShares(e.target.value)} placeholder="Current shares"/><input className="search" inputMode="decimal" value={positionCost} onChange={e=>setPositionCost(e.target.value)} placeholder="Current average cost / share"/><input className="search" value={positionNote} onChange={e=>setPositionNote(e.target.value)} placeholder="Update note (optional)"/><button className="btn">Save position</button><p className="muted small-note">First entry creates the tracking baseline. Later edits update the live holding while preserving the initial metrics and adding a revision record.</p></form><form className="card reveal-card suite-form" onSubmit={createPortfolio}><span className="eyebrow">Multiple accounts</span><h2>Create another portfolio</h2><input className="search" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Portfolio name"/><input className="search" value={newBrokerage} onChange={e=>setNewBrokerage(e.target.value)} placeholder="Brokerage (optional)"/><input className="search" inputMode="decimal" value={newCash} onChange={e=>setNewCash(e.target.value)} placeholder="Cash"/><button className="btn">Create portfolio</button></form></div>
  </>}
 </section>
}
function Metric({label,value,sub,cls=""}:{label:string;value:string;sub?:string;cls?:string}){return <span><i>{label}</i><strong className={cls}>{value}</strong>{sub&&<small>{sub}</small>}</span>}
