"use client";
import {FormEvent,useEffect,useState} from "react";
import {navigateTo,type NavigationTarget} from "./navigation-context";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function headers(){const e=typeof window!=="undefined"?localStorage.getItem("dailyReportUserEmail")||"":"",t=typeof window!=="undefined"?localStorage.getItem("dailyReportUserToken")||"":"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;const n=(v:any)=>v==null?"—":Number(v).toFixed(2);const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:`$${Number(v).toLocaleString()}`;
function Metric({label,value,source,detail,target}:{label:string;value:string;source:string;detail:string;target?:NavigationTarget}){return <details className="metric-explainer"><summary><div><span>{label}</span><strong>{value}</strong></div><small>{source}</small><b>▾</b></summary><p>{detail}</p>{target&&<button className="text-btn" onClick={()=>navigateTo(target)}>Open supporting view →</button>}</details>}

export default function ResearchWorkspaceV4({navigation}:{navigation?:(NavigationTarget&{nonce:number})|null}){
 const[symbol,setSymbol]=useState("NVDA"),[query,setQuery]=useState("NVDA"),[data,setData]=useState<any>(null),[fund,setFund]=useState<any>(null),[catalysts,setCatalysts]=useState<any>(null),[analogs,setAnalogs]=useState<any>(null),[relative,setRelative]=useState<any>(null),[tab,setTab]=useState("Overview"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(raw:string,requestedTab?:string){const s=raw.trim().toUpperCase();if(!s)return;setLoading(true);setError("");setQuery(s);try{const results=await Promise.allSettled([api(`/api/v1/security/${s}/workspace`),api(`/api/v1/markets/${s}/fundamentals`),api(`/api/v1/security/${s}/catalysts`),api(`/api/v1/security/${s}/analogs?limit=10`),api("/api/v1/analytics/relative-strength?scope=user&limit=200")]);const w=results[0].status==="fulfilled"?results[0].value:null;if(!w)throw new Error(results[0].status==="rejected"?String(results[0].reason):`Unable to hydrate ${s}`);setData(w);setFund(results[1].status==="fulfilled"?results[1].value:null);setCatalysts(results[2].status==="fulfilled"?results[2].value:null);setAnalogs(results[3].status==="fulfilled"?results[3].value:null);const rr=results[4].status==="fulfilled"?results[4].value:null;setRelative((rr?.rows||[]).find((x:any)=>x.symbol===s)||null);setSymbol(s);if(requestedTab)setTab(requestedTab)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load("NVDA")},[]);useEffect(()=>{if(navigation?.tab!=="Research")return;const s=navigation.symbol||symbol;load(s,navigation.subtab||undefined)},[navigation?.nonce]);function submit(e:FormEvent){e.preventDefault();load(query)}
 const m=data?.market||{},o=data?.opportunity||{},features=data?.features||{};
 return <section className="tab-panel v3-workspace research-v3"><div className="card suite-hero"><div><span className="eyebrow">Universal security workspace</span><h2>Research · {symbol}</h2><p className="muted">Missing symbols are hydrated on demand. Metrics expand into methodology, lineage and exact cross-tab destinations.</p></div><form className="research-search" onSubmit={submit}><input className="search" value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Ticker"/><button className="btn" disabled={loading}>{loading?"Loading…":"Open"}</button></form></div><div className="subtab-bar">{["Overview","Technicals","Valuation","Intelligence","History"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Research unavailable</strong><span>{error}</span></div>}{loading&&!data&&<div className="suite-skeleton">{Array.from({length:6}).map((_,i)=><span key={i}/>)}</div>}{data&&<>
 {tab==="Overview"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Price</span><strong>{m.price==null?"—":`$${Number(m.price).toFixed(2)}`}</strong><small>{m.provider||"stored market"}</small></article><article className="card stat-card"><span>1D</span><strong className={(m.change_percent||0)>=0?"positive":"negative"}>{pct(m.change_percent)}</strong></article><article className="card stat-card"><span>Buy score</span><strong>{n(o.buy_score)}</strong></article><article className="card stat-card"><span>Sell score</span><strong>{n(o.sell_score)}</strong></article></div><details className="card methodology-dropdown"><summary><strong>Data state</strong><span className="muted">{data.data_state||"stored"}</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Name</i><strong>{data.registry?.name||symbol}</strong></span><span><i>Sector</i><strong>{data.registry?.sector||m.sector||"—"}</strong></span><span><i>Market as-of</i><strong>{m.as_of||"—"}</strong></span><span><i>History</i><strong>{data.history_state?.bars??"—"} bars</strong></span></div></details></div>}
 {tab==="Technicals"&&<div className="component-grid-v3"><Metric label="Williams %R" value={m.williams_r_14==null?"—":Number(m.williams_r_14).toFixed(1)} source="Markets · stored daily history" detail="14-session Williams %R derived from the same stored history used by Markets and Opportunities." target={{tab:"Markets",symbol}}/><Metric label="100MA distance" value={pct(m.price_vs_ma100_percent)} source="Markets · daily bars" detail="Current price distance from the 100-session moving average." target={{tab:"Markets",symbol}}/><Metric label="200MA distance" value={pct(m.price_vs_ma200_percent)} source="Markets · daily bars" detail="Current price distance from the 200-session moving average." target={{tab:"Markets",symbol}}/><Metric label="Relative volume" value={m.relative_volume==null?"—":`${Number(m.relative_volume).toFixed(2)}x`} source="Markets · daily volume" detail="Completed-session volume relative to the app comparison baseline." target={{tab:"Markets",symbol}}/><Metric label="7D momentum" value={pct(m.seven_day_percent)} source="Markets" detail="Seven-session return used by the opportunity momentum component."/><Metric label="30D momentum" value={pct(m.thirty_day_percent)} source="Markets" detail="Thirty-session return used for persistence and relative strength."/><Metric label="Relative strength vs SPY" value={pct(relative?.vs_spy_30d)} source="Macro analytics" detail="30D return spread versus SPY over aligned completed sessions." target={{tab:"Macro",subtab:"Cross-asset"}}/><Metric label="Relative strength vs QQQ" value={pct(relative?.vs_qqq_30d)} source="Macro analytics" detail="30D return spread versus QQQ over aligned completed sessions." target={{tab:"Macro",subtab:"Cross-asset"}}/></div>}
 {tab==="Valuation"&&<div className="v3-stack"><div className="component-grid-v3"><Metric label="P/E" value={n(fund?.pe_ratio)} source={fund?.field_sources?.pe_ratio||fund?.provider||"Unavailable"} detail={fund?.pe_ratio_method||"Trailing/direct P/E when supportable."}/><Metric label="P/S" value={n(fund?.price_to_sales_ratio)} source={fund?.field_sources?.price_to_sales_ratio||fund?.provider||"Unavailable"} detail={fund?.price_to_sales_method||"Provider P/S or market cap divided by trailing revenue."}/><Metric label="PEG" value={n(fund?.peg_ratio)} source={fund?.field_sources?.peg_ratio||fund?.provider||"Unavailable"} detail={fund?.peg_ratio_method||"Provider PEG or derived P/E divided by positive earnings growth."}/><Metric label="Market cap" value={money(fund?.market_cap||m.market_cap)} source={fund?.field_sources?.market_cap||fund?.provider||m.provider||"stored"} detail={fund?.market_cap_method||"Provider market cap or price × shares outstanding."}/></div>{fund?.source_url&&<a className="source-link" href={fund.source_url} target="_blank" rel="noreferrer">Primary valuation source ↗</a>}</div>}
 {tab==="Intelligence"&&<div className="v3-stack"><div className="suite-two"><details className="card methodology-dropdown"><summary><strong>Flow</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Bullish premium</i><strong>{money(data.flow?.bullish_premium)}</strong></span><span><i>Bearish premium</i><strong>{money(data.flow?.bearish_premium)}</strong></span></div><button className="text-btn" onClick={()=>navigateTo({tab:"Large Flow",subtab:"Feed",filter:symbol})}>Open {symbol} flow →</button></details><details className="card methodology-dropdown"><summary><strong>Opportunity context</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Sector score</i><strong>{n(o.sector_score)}</strong></span><span><i>Buy score</i><strong>{n(o.buy_score)}</strong></span><span><i>Sell score</i><strong>{n(o.sell_score)}</strong></span></div><button className="text-btn" onClick={()=>navigateTo({tab:"Opportunities",symbol})}>Open {symbol} opportunity →</button></details></div><details className="card methodology-dropdown"><summary><strong>Matched catalysts</strong><span>{catalysts?.news?.length||0}</span><b>▾</b></summary>{(catalysts?.news||[]).map((x:any,i:number)=><details className="reason-v3" key={i}><summary><strong>{x.title}</strong><small>{x.domain}</small><b>▾</b></summary><p>{x.why_it_matters||x.relationship}</p>{x.url&&<a className="source-link" href={x.url} target="_blank" rel="noreferrer">Source ↗</a>}</details>)}</details></div>}
 {tab==="History"&&<div className="v3-stack"><details className="card methodology-dropdown"><summary><strong>Historical analogs</strong><span>{analogs?.analogs?.length||0}</span><b>▾</b></summary><div className="analog-grid-v3">{(analogs?.analogs||[]).map((a:any)=><div key={a.date}><strong>{a.date}</strong><span>Similarity {a.distance}</span><small>1D {pct(a.return_1d)} · 5D {pct(a.return_5d)} · 21D {pct(a.return_21d)}</small><b className={(a.following_5d||0)>=0?"positive":"negative"}>Next 5D {pct(a.following_5d)}</b></div>)}</div></details><details className="card methodology-dropdown"><summary><strong>Latest feature snapshot</strong><b>▾</b></summary><pre className="data-pre">{JSON.stringify(features,null,2)}</pre></details></div>}
 </>}</section>
}
