"use client";

import {FormEvent,useEffect,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const e=localStorage.getItem("dailyReportUserEmail")||"",t=localStorage.getItem("dailyReportUserToken")||"";return {...(e?{"X-User-Email":e}:{}),...(t?{"X-User-Token":t}:{})}}
async function api(path:string){const r=await fetch(`${API}${path}`,{cache:"no-store",headers:authHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}
const pct=(v:any)=>v==null?"—":`${Number(v)>=0?"+":""}${Number(v).toFixed(2)}%`;const n=(v:any)=>v==null?"—":Number(v).toFixed(2);const money=(v:any)=>v==null?"—":Math.abs(Number(v))>=1e9?`$${(Number(v)/1e9).toFixed(2)}B`:`$${Number(v).toLocaleString()}`;
function go(name:string){window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:name}))}
function Metric({label,value,source,detail,tab}:{label:string;value:string;source:string;detail:string;tab?:string}){return <details className="metric-explainer"><summary><div><span>{label}</span><strong>{value}</strong></div><small>{source}</small><b>▾</b></summary><p>{detail}</p><div className="metric-links">{tab&&<button className="text-btn" onClick={()=>go(tab)}>Open {tab} →</button>}</div></details>}

export default function ResearchWorkspaceV3(){
 const[symbol,setSymbol]=useState("NVDA"),[query,setQuery]=useState("NVDA"),[data,setData]=useState<any>(null),[fund,setFund]=useState<any>(null),[catalysts,setCatalysts]=useState<any>(null),[analogs,setAnalogs]=useState<any>(null),[relative,setRelative]=useState<any>(null),[tab,setTab]=useState("Overview"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(s:string){setLoading(true);setError("");try{const[w,f,c,a,r]=await Promise.all([api(`/api/v1/security/${s}/workspace`),api(`/api/v1/markets/${s}/fundamentals`),api(`/api/v1/security/${s}/catalysts`),api(`/api/v1/security/${s}/analogs?limit=10`),api("/api/v1/analytics/relative-strength?scope=user&limit=200")]);setData(w);setFund(f);setCatalysts(c);setAnalogs(a);setRelative((r.rows||[]).find((x:any)=>x.symbol===s)||null);setSymbol(s)}catch(e:any){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load(symbol)},[]);function submit(e:FormEvent){e.preventDefault();const s=query.trim().toUpperCase();if(s)load(s)}
 const m=data?.market||{},o=data?.opportunity||{},features=data?.features||{};
 return <section className="tab-panel v3-workspace research-v3"><div className="card suite-hero"><div><span className="eyebrow">Universal security workspace</span><h2>Research · {symbol}</h2><p className="muted">Every important metric expands into methodology, source lineage and a link to the deeper tab that produced it.</p></div><form className="research-search" onSubmit={submit}><input className="search" value={query} onChange={e=>setQuery(e.target.value.toUpperCase())} placeholder="Ticker"/><button className="btn" disabled={loading}>{loading?"Loading…":"Open"}</button></form></div><div className="subtab-bar">{["Overview","Technicals","Valuation","Intelligence","History"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className="suite-error"><strong>Research unavailable</strong><span>{error}</span></div>}{data&&<>
 {tab==="Overview"&&<div className="v3-stack"><div className="command-stat-grid"><article className="card stat-card"><span>Price</span><strong>{m.price==null?"—":`$${Number(m.price).toFixed(2)}`}</strong><small>{m.provider||"stored market"}</small></article><article className="card stat-card"><span>1D</span><strong className={(m.change_percent||0)>=0?"positive":"negative"}>{pct(m.change_percent)}</strong></article><article className="card stat-card"><span>Buy score</span><strong>{n(o.buy_score)}</strong></article><article className="card stat-card"><span>Sell score</span><strong>{n(o.sell_score)}</strong></article></div><details className="card methodology-dropdown" open><summary><strong>Identity & data state</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Name</i><strong>{data.registry?.name||symbol}</strong></span><span><i>Sector</i><strong>{data.registry?.sector||m.sector||"—"}</strong></span><span><i>Industry</i><strong>{data.registry?.industry||"—"}</strong></span><span><i>Market as-of</i><strong>{m.as_of||"—"}</strong></span><span><i>Retrieved</i><strong>{m.retrieved_at?new Date(m.retrieved_at).toLocaleString():"—"}</strong></span><span><i>Fundamentals cache</i><strong>{fund?.fundamentals_cache||"—"}</strong></span></div></details></div>}
 {tab==="Technicals"&&<div className="component-grid-v3"><Metric label="Williams %R" value={m.williams_r_14==null?"—":Number(m.williams_r_14).toFixed(1)} source="Markets · stored daily history" detail="14-period Williams %R. Values near -100 indicate price near the recent range low; values near 0 indicate price near the range high." tab="Markets"/><Metric label="100MA distance" value={pct(m.price_vs_ma100_percent)} source="Markets · daily bars" detail="Percentage distance of current stored price from the 100-session moving average." tab="Markets"/><Metric label="200MA distance" value={pct(m.price_vs_ma200_percent)} source="Markets · daily bars" detail="Percentage distance from the 200-session moving average, used by Buy/Sell Flags and Opportunities." tab="Markets"/><Metric label="Relative volume" value={m.relative_volume==null?"—":`${Number(m.relative_volume).toFixed(2)}x`} source="Markets · daily volume history" detail="Current completed-session volume divided by the app's historical comparison baseline." tab="Markets"/><Metric label="7D momentum" value={pct(m.seven_day_percent)} source="Markets" detail="Same-session return window used in Macro rotation and the Opportunities momentum component." tab="Macro"/><Metric label="30D momentum" value={pct(m.thirty_day_percent)} source="Markets" detail="30-session return window; used together with 7D momentum for persistence and relative-strength comparisons." tab="Macro"/><Metric label="Relative strength vs SPY" value={pct(relative?.vs_spy_30d)} source="Macro analytics" detail="30D return spread: this security's stored 30D return minus SPY's stored 30D return. This is not RSI." tab="Macro"/><Metric label="Relative strength vs QQQ" value={pct(relative?.vs_qqq_30d)} source="Macro analytics" detail="30D return spread versus QQQ over the same stored window." tab="Macro"/></div>}
 {tab==="Valuation"&&<div className="v3-stack"><div className="component-grid-v3"><Metric label="P/E" value={n(fund?.pe_ratio)} source={fund?.field_sources?.pe_ratio||fund?.provider||"Unavailable"} detail={fund?.pe_ratio_method||"Trailing/direct P/E when available. Negative/non-meaningful earnings are represented as unavailable rather than forced into a ratio."}/><Metric label="P/S" value={n(fund?.price_to_sales_ratio)} source={fund?.field_sources?.price_to_sales_ratio||fund?.provider||"Unavailable"} detail={fund?.price_to_sales_method||"Price-to-sales using provider value or market cap divided by trailing revenue when the underlying inputs are available."}/><Metric label="PEG" value={n(fund?.peg_ratio)} source={fund?.field_sources?.peg_ratio||fund?.provider||"Unavailable"} detail={fund?.peg_ratio_method||"Provider PEG or P/E divided by positive earnings growth when that derivation is supportable."}/><Metric label="Market cap" value={money(fund?.market_cap||m.market_cap)} source={fund?.field_sources?.market_cap||fund?.provider||m.provider||"stored"} detail={fund?.market_cap_method||"Provider market cap, or shared price × provider shares outstanding when needed."}/></div><details className="card methodology-dropdown" open><summary><strong>Valuation source path</strong><span className="muted">{(fund?.valuation_sources||[]).join(" → ")}</span><b>▾</b></summary><p>Primary no-key enrichment is Yahoo Finance. SEC EDGAR standardized company facts fill missing revenue/EPS/share inputs. Alpha Vantage is used only when still incomplete and daily quota remains.</p>{fund?.source_url&&<a className="source-link" href={fund.source_url} target="_blank" rel="noreferrer">Primary source ↗</a>}<p className="muted">Quality: P/E {fund?.quality?.pe||"—"} · P/S {fund?.quality?.ps||"—"} · PEG {fund?.quality?.peg||"—"}</p></details></div>}
 {tab==="Intelligence"&&<div className="v3-stack"><div className="suite-two"><details className="card methodology-dropdown" open><summary><strong>Flow</strong><span className="muted">shared Large Flow cache</span><b>▾</b></summary><div className="metric-tile-grid"><span><i>Bullish premium</i><strong>{money(data.flow?.bullish_premium)}</strong></span><span><i>Bearish premium</i><strong>{money(data.flow?.bearish_premium)}</strong></span><span><i>Events</i><strong>{data.flow?.events??0}</strong></span></div><button className="text-btn" onClick={()=>go("Large Flow")}>Large Flow →</button></details><details className="card methodology-dropdown" open><summary><strong>Sector / opportunity</strong><b>▾</b></summary><div className="metric-tile-grid"><span><i>Sector score</i><strong>{n(o.sector_score)}</strong></span><span><i>Buy score</i><strong>{n(o.buy_score)}</strong></span><span><i>Sell score</i><strong>{n(o.sell_score)}</strong></span></div><button className="text-btn" onClick={()=>go("Opportunities")}>Opportunities →</button></details></div><details className="card methodology-dropdown"><summary><strong>Matched catalysts</strong><span>{catalysts?.news?.length||0}</span><b>▾</b></summary>{(catalysts?.news||[]).map((x:any,i:number)=><details className="reason-v3" key={i}><summary><strong>{x.title}</strong><small>{x.domain}</small><b>▾</b></summary><p>{x.why_it_matters||x.relationship}</p>{x.url&&<a className="source-link" href={x.url} target="_blank" rel="noreferrer">Source ↗</a>}</details>)}</details></div>}
 {tab==="History"&&<div className="v3-stack"><details className="card methodology-dropdown" open><summary><strong>Historical analogs</strong><span>{analogs?.analogs?.length||0}</span><b>▾</b></summary><div className="analog-grid-v3">{(analogs?.analogs||[]).map((a:any)=><div key={a.date}><strong>{a.date}</strong><span>Similarity {a.distance}</span><small>1D {pct(a.return_1d)} · 5D {pct(a.return_5d)} · 21D {pct(a.return_21d)}</small><b className={(a.following_5d||0)>=0?"positive":"negative"}>Next 5D {pct(a.following_5d)}</b></div>)}</div><p className="muted">{analogs?.methodology}</p></details><details className="card methodology-dropdown"><summary><strong>Latest feature snapshot</strong><b>▾</b></summary><pre className="data-pre">{JSON.stringify(features,null,2)}</pre></details></div>}
 </>}</section>
}
