"use client";

import {FormEvent,useEffect,useState} from "react";

const API=process.env.NEXT_PUBLIC_API_BASE_URL||"https://daily-report-api-ero2.onrender.com";
function authHeaders(){if(typeof window==="undefined")return{};const email=localStorage.getItem("dailyReportUserEmail")||"",token=localStorage.getItem("dailyReportUserToken")||"";return {...(email?{"X-User-Email":email}:{}),...(token?{"X-User-Token":token}:{})}}
async function api(path:string,options:RequestInit={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.detail||`HTTP ${r.status}`);return d}

export type AccessState={email:string;role:string;enabled:boolean;permissions:Record<string,boolean>;allowed_tabs:string[];preferences:{visible_tabs:string[];information_modules:Record<string,boolean>;settings:Record<string,any>};auth_enabled:boolean};

export function useUserAccess(){const[data,setData]=useState<AccessState|null>(null),[error,setError]=useState("");async function load(){try{setData(await api("/api/v1/user/access"));setError("")}catch(e:any){setError(e.message)}}useEffect(()=>{load();const h=()=>load();window.addEventListener("daily-report-auth-changed",h);return()=>window.removeEventListener("daily-report-auth-changed",h)},[]);return{data,error,reload:load}}

export function applyUserVisibility(access:AccessState|null){if(!access)return;const visible=new Set(access.preferences.visible_tabs||access.allowed_tabs);document.querySelectorAll<HTMLButtonElement>(".nav button").forEach(btn=>{const name=(btn.textContent||"").trim();btn.style.display=visible.has(name)?"":"none"});const mods=access.preferences.information_modules||{};document.querySelectorAll<HTMLElement>("[data-info-module]").forEach(el=>{const key=el.dataset.infoModule||"";el.style.display=mods[key]===false?"none":""});const context=document.querySelector<HTMLElement>(".context-bar");if(context)context.style.display=mods.context_bar===false?"none":"";const flags=document.querySelector<HTMLElement>(".market-flags-section");if(flags)flags.style.display=mods.market_flags===false?"none":"";document.querySelectorAll<HTMLElement>(".card h2").forEach(h=>{if(h.textContent?.trim()==="Notable Outliers"){const card=h.closest<HTMLElement>(".card");if(card)card.style.display=mods.report_outliers===false?"none":""}})}

export function UserCustomizationPanel({access,onChanged}:{access:AccessState;onChanged:()=>void}){
 const[tabs,setTabs]=useState<string[]>(access.preferences.visible_tabs||[]),[mods,setMods]=useState<Record<string,boolean>>(access.preferences.information_modules||{}),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{setTabs(access.preferences.visible_tabs||[]);setMods(access.preferences.information_modules||{})},[access]);
 async function save(){setSaving(true);setError("");try{await api("/api/v1/user/preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({visible_tabs:tabs,information_modules:mods})});onChanged()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 const canTabs=!!access.permissions.can_customize_tabs,canInfo=!!access.permissions.can_customize_information;
 return <div className="card reveal-card user-customization-card"><div className="section-head"><div><span className="eyebrow">Private user layout</span><h2>My Tabs & Information</h2></div><span className="data-badge cached">{access.email}</span></div><p className="muted">These choices are stored for this user only. Admin permissions determine which tabs and customization controls are available.</p>{canTabs&&<><h3>Visible tabs</h3><div className="permission-grid">{access.allowed_tabs.map(t=><label key={t}><input type="checkbox" checked={tabs.includes(t)} onChange={e=>setTabs(x=>e.target.checked?[...x,t]:x.filter(v=>v!==t))}/><span>{t}</span></label>)}</div></>}{canInfo&&<><h3>Information modules</h3><div className="permission-grid">{Object.keys(mods).map(k=><label key={k}><input type="checkbox" checked={mods[k]!==false} onChange={e=>setMods(x=>({...x,[k]:e.target.checked}))}/><span>{k.replaceAll("_"," ")}</span></label>)}</div></>}{!canTabs&&!canInfo&&<p className="muted">Customization is currently controlled by the owner for this account.</p>}{(canTabs||canInfo)&&<button className="btn" onClick={save} disabled={saving}>{saving?"Saving…":"Save my layout"}</button>}{error&&<p className="negative">{error}</p>}</div>
}

export function AdminUserPanel(){
 const[data,setData]=useState<any>(null),[error,setError]=useState(""),[newEmail,setNewEmail]=useState(""),[issued,setIssued]=useState<any>(null);
 async function load(){try{setData(await api("/api/v1/admin/users"));setError("")}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!newEmail.trim())return;await api(`/api/v1/admin/users/${encodeURIComponent(newEmail.trim().toLowerCase())}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:true,role:"approved_user",permissions:{},allowed_tabs:data?.tabs||[]})});setNewEmail("");load()}
 async function saveUser(u:any){await api(`/api/v1/admin/users/${encodeURIComponent(u.email)}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:u.enabled,role:u.role,permissions:u.permissions,allowed_tabs:u.allowed_tabs})});load()}
 async function issue(email:string){setIssued(await api(`/api/v1/admin/users/${encodeURIComponent(email)}/issue-token`,{method:"POST"}))}
 function patch(email:string,fn:(u:any)=>any){setData((d:any)=>({...d,users:d.users.map((u:any)=>u.email===email?fn({...u,permissions:{...u.permissions},allowed_tabs:[...u.allowed_tabs]}):u)}))}
 return <div className="card reveal-card admin-users-card"><div className="section-head"><div><span className="eyebrow">Owner controls</span><h2>User Verification & Permissions</h2></div><span className={`data-badge ${data?.auth_enabled?"live":"cached"}`}>{data?.auth_enabled?"AUTH ACTIVE":"PREPARED · NOT ACTIVE"}</span></div><p className="muted">Create approved users, control tab access, grant customization rights, and issue one-time access tokens. Authentication remains off until USER_AUTH_ENABLED=true is set on Render.</p>{error&&<p className="negative">{error}</p>}<form className="admin-add-user" onSubmit={create}><input className="search" type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="new.user@example.com"/><button className="btn">Add user</button></form>{issued&&<div className="token-issued"><strong>New token for {issued.email}</strong><code>{issued.access_token}</code><p>Copy this now. The plaintext token is not stored or shown again.</p></div>}<div className="admin-user-list">{data?.users?.map((u:any)=><details className="admin-user" key={u.email}><summary><div><strong>{u.email}</strong><span>{u.role} · {u.has_token?"token ready":"no token"}</span></div><span className={`data-badge ${u.enabled?"cached":"stale"}`}>{u.enabled?"ENABLED":"DISABLED"}</span></summary><div className="admin-user-body"><label className="inline-toggle"><input type="checkbox" checked={u.enabled} onChange={e=>patch(u.email,x=>({...x,enabled:e.target.checked}))}/> Enabled</label><h4>Permissions</h4><div className="permission-grid">{Object.keys(u.permissions||{}).map(k=><label key={k}><input type="checkbox" checked={!!u.permissions[k]} onChange={e=>patch(u.email,x=>({...x,permissions:{...x.permissions,[k]:e.target.checked}}))}/><span>{k.replaceAll("_"," ")}</span></label>)}</div><h4>Allowed tabs</h4><div className="permission-grid">{(data.tabs||[]).map((t:string)=><label key={t}><input type="checkbox" checked={u.allowed_tabs.includes(t)} onChange={e=>patch(u.email,x=>({...x,allowed_tabs:e.target.checked?[...x.allowed_tabs,t]:x.allowed_tabs.filter((v:string)=>v!==t)}))}/><span>{t}</span></label>)}</div><div className="admin-user-actions"><button className="btn" onClick={()=>saveUser(u)}>Save permissions</button><button className="btn" onClick={()=>issue(u.email)}>Issue new token</button></div></div></details>)}</div></div>
}
