import {expect,test,Page,Route} from "@playwright/test";

const respond=(r:Route,b:any)=>r.fulfill({status:200,contentType:"application/json",body:JSON.stringify(b)});
const account={id:"u",email:"audit@example.com",name:"UI Audit",role:"owner",status:"approved",enabled:true};
async function mock(page:Page){await page.route("**/backend/**",async r=>{const u=new URL(r.request().url()),p=u.pathname,m=r.request().method();
 if(p.endsWith("/auth/session"))return respond(r,{account});
 if(p.endsWith("/stack/overview"))return respond(r,{version:"audit",layers:{research:{tracked_symbols:5,stored_market_snapshots:10,stored_feature_snapshots:8},macro:{rotation_history_days:21},opportunity:{methodology:"audit"},deployment:{}}});
 if(p.includes("/stack/research/"))return respond(r,{symbol:p.split("/").pop(),registry:{name:"Audit Co",sector:"Technology"},market:{price:100,provider:"audit",retrieved_at:"2026-09-10T17:00:00Z",source_url:"https://example.com",verification_status:"verified",seven_day_percent:2,thirty_day_percent:5,price_vs_ma100_percent:1},latest_features:{buy_score:80,williams_r:-82,model_version:"audit"},score_history:{buy_score_change:2,history:[{}],largest_positive_drivers:[],largest_negative_drivers:[],raw_driver_changes:[]},rotation_context:{proxy:"SMH",basis:"sector",state:{state:"leading_stable",rotation_pressure:1,conviction:80,observations:4,data_age_hours:1}},flow_72h:{events:1},data_state:{market:true,fundamentals:true,feature_history_points:1},fundamentals:{pe_ratio:20,price_to_sales_ratio:4,quarterly_revenue_growth_yoy:.2},theses:[]});
 if(p.endsWith("/stack/rotation"))return respond(r,{rows:[{symbol:"SMH",name:"Semis",state:"leading_stable",rotation_pressure:2,rotation_score:2,conviction:90,delta_1_observation:.2,delta_3_observations:.5,forward_bias:"leaders"},{symbol:"XLK",name:"Tech",state:"lagging_improving",rotation_pressure:.5,rotation_score:.4,conviction:60,delta_1_observation:.1,delta_3_observations:.2,forward_bias:"early_rotation_candidate"}],early_rotation:[{symbol:"XLK",name:"Tech",conviction:60}],outflow_risk:[],methodology:"audit"});
 if(p.endsWith("/stack/candidates"))return respond(r,{candidates:[{symbol:"NBIS",score:80,williams_r:-82,ma100_proximity:2,liquidity_score:9}],stages:[{name:"Universe coverage",input:100,output:80,rule:"cached"}],coverage:{market_wide_ready:false,cached_snapshot_coverage_percent:80,registry_scannable:100,cached_scannable:80,technical_complete:70,technical_coverage_percent:70,limitation:"partial"},verification:{verified:60,primary_only:10},last_cache_update:"2026-09-10T17:00:00Z",deep_enrichment_symbols:["NBIS"],methodology:"audit"});
 if(p.endsWith("/stack/candidates/enrich"))return respond(r,{jobs_added:1});
 if(p.endsWith("/stack/deployment"))return respond(r,{basket:u.searchParams.get("basket")||"watchlist",capital:Number(u.searchParams.get("capital")||2500),model:"Williams Priority",eligible:[{priority_rank:1,symbol:"NBIS",williams_r:-82,signal_month:"2026-09",priority_weight:1,suggested_dollars:Number(u.searchParams.get("capital")||2500),fundamental_score:{score:70,grade:"B",coverage:.8,components:[]}}],unavailable:[],methodology:"audit",fundamental_score_policy:"informational"});
 if(p.endsWith("/opportunities/criteria"))return respond(r,{criteria:[{key:"williams",label:"Williams %R",min_sessions:14,description:"Momentum",hypothesis:"Oversold",evidence_basis:"audit",validation_status:"experimental"},{key:"ma100_proximity",label:"100MA proximity",min_sessions:100,description:"Distance",hypothesis:"Support",evidence_basis:"audit",validation_status:"experimental"},{key:"ma50_proximity",label:"50MA proximity",min_sessions:50,description:"Distance",hypothesis:"Support",evidence_basis:"audit",validation_status:"experimental"}],filters:[{key:"williams",label:"Williams %R",operators:["<=",">="],default_operator:"<=",default_value:-70}],default_formula:{criteria:{williams:60,ma100_proximity:40},filters:[]}});
 if(p.endsWith("/opportunities/formulas")&&m==="GET")return respond(r,{default:{id:"default",name:"Default",built_in:true,criteria:{williams:60,ma100_proximity:40},filters:[]},saved:[{id:9,name:"Saved Test",built_in:false,criteria:{williams:70,ma100_proximity:30},filters:[]}]});
 if(p.includes("/opportunities/formulas"))return respond(r,{id:9,name:"Saved Test",built_in:false,criteria:{williams:70},filters:[]});
 if(p.endsWith("/opportunities/index"))return respond(r,{rows:[{formula_rank:1,quality_adjusted_rank:1,symbol:"NBIS",sector:"Technology",score:80,quality_adjusted_score:78,quality_confidence:.9,raw_criteria:{williams:-82,ma100_proximity:2,ma50_proximity:4,liquidity:9},quality:{state:"verified"}}],counts:{formula_complete:1,filtered_out:0},quality_counts:{degraded:0,incomplete:0},formula:{label:"audit"}});
 if(p.endsWith("/news/world"))return respond(r,{provider:"Audit",synthesis_model:"deterministic",cache:"fresh",synthesis_policy:"audit",taxonomy_counts:{monetary_policy:1},stories:[],articles:[{url:"https://example.com/a",title:"Fed story",importance_score:90,relevance_score:90,primary_category:"monetary_policy",macro_categories:["monetary_policy"],domain:"example.com",published_at:"2026-09-10T16:00:00Z",why_it_matters:"audit",first_order_effects:["rates"],second_order_effects:["growth"],effect_policy:"hypothesis",exposure_map:{tickers:["NBIS"],themes:["AI"],sectors:["Tech"],mapping_basis:"keyword",causal_confidence:"association_only"}}]});
 if(p.endsWith("/events"))return respond(r,{events:[],providers:[]});if(p.endsWith("/events/tracked-companies"))return respond(r,{events:[],count:0,markets_symbols:[],portfolio_symbols:[],refreshed_symbols:[],deferred_symbols:[],methodology:"audit"});
 if(p.endsWith("/data/health"))return respond(r,{summary:{},items:[]});if(p.endsWith("/data/diagnostics"))return respond(r,{checks:[]});
 if(p.endsWith("/flow/recent"))return respond(r,{provider:"Audit",events:[{symbol:"NBIS",occurred_at:new Date().toISOString(),source_url:"https://example.com/flow",data:{premium:100000,strike:100,expiration:"2099-01-01",contracts:100,volume_oi_ratio:2,side:"call",aggression:"buy",market_cap:1e9}}]});if(p.endsWith("/flow/analytics"))return respond(r,{rows:[{symbol:"NBIS",flow_to_market_cap:.001,total_premium:100000,premium_1h:10000,premium_24h:50000,premium_72h:100000,unique_contracts:1,events:1}]});
 return respond(r,{});});}
const noOverflow=async(page:Page)=>expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);

test.describe("V4 root",()=>{test.beforeEach(async({page})=>{await mock(page);await page.goto("/v4");await expect(page.getByRole("heading",{name:"Decision Stack"})).toBeVisible()});
 test("research",async({page})=>{await page.getByRole("textbox",{name:"Ticker",exact:true}).fill("AAOI");await page.getByRole("button",{name:"Open",exact:true}).click();await expect(page.getByText("AAOI",{exact:true}).first()).toBeVisible();const g=page.getByRole("group",{name:/Research statistics/});for(const b of await g.getByRole("button").all()){await b.click();await expect(b).toHaveAttribute("aria-pressed","true");await b.click()}await page.getByRole("button",{name:"Layout",exact:true}).click();await page.getByRole("button",{name:"Reset layer",exact:true}).click();const q=page.getByRole("textbox",{name:"Global ticker search",exact:true});await q.fill("mu");await expect(q).toHaveValue("MU");await noOverflow(page)});
 test("macro",async({page})=>{await page.getByRole("button",{name:/Macro/}).click();await expect(page.getByText("2 groups",{exact:true})).toBeVisible();if((page.viewportSize()?.width||999)>560){const g=page.getByRole("group",{name:/sort macro rotation groups/});for(const n of ["Rotation pressure","Conviction","1-observation change","3-observation change","Ticker"])await g.getByRole("button",{name:new RegExp(`^${n}`)}).click()}const selects=page.locator(".table-controls select");await selects.nth(0).selectOption("early");await selects.nth(1).selectOption("symbol");await page.getByRole("button",{name:/Sort descending|Sort ascending/}).click();await page.getByTitle("Open XLK research").click();await expect(page.getByText("XLK",{exact:true}).first()).toBeVisible();await noOverflow(page)});
 test("opportunity",async({page})=>{await page.getByRole("button",{name:/Opportunity/}).click();await expect(page.getByText(/Partial cached-market scan/)).toBeVisible();await page.getByLabel("Add Opportunity criterion",{exact:true}).selectOption("ma50_proximity");await page.locator(".formula-actions").getByRole("button",{name:"Add",exact:true}).click();await page.getByRole("button",{name:"Remove 50MA proximity",exact:true}).click();await page.getByLabel("Add hard screen",{exact:true}).selectOption("williams");await page.locator(".filter-add").getByRole("button",{name:"Add",exact:true}).click();await page.getByRole("button",{name:"Remove Williams %R filter",exact:true}).click();await page.getByRole("button",{name:"Saved Test",exact:true}).click();await page.getByTitle("Open NBIS details").click();await expect(page.getByTitle("Open NBIS details")).toHaveAttribute("aria-expanded","true");await page.getByRole("button",{name:"Enrich shortlist",exact:true}).click();await expect(page.getByText(/1 enrichment job queued/)).toBeVisible();await noOverflow(page)});
 test("deployment",async({page})=>{await page.getByRole("button",{name:/Deployment/}).click();await page.getByLabel("Deployment basket",{exact:true}).selectOption("watchlist");await page.getByLabel("New capital",{exact:true}).fill("2500");await page.getByRole("button",{name:"Calculate",exact:true}).click();await expect(page.locator(".allocation-row-button")).toHaveCount(1);await page.getByText("Fundamental score details",{exact:true}).click();await page.locator(".allocation-row-button").click();await expect(page.getByText("NBIS",{exact:true}).first()).toBeVisible();await noOverflow(page)});
});

test.describe("V4 deep",()=>{test.beforeEach(async({page})=>mock(page));
 test("world news",async({page})=>{await page.goto("/v4/deep/world-news");await page.getByLabel("Topic",{exact:true}).selectOption("Rates & Central Banks");await page.getByLabel("Macro category",{exact:true}).selectOption("monetary_policy");await page.getByLabel("Time window",{exact:true}).selectOption("168");await page.getByLabel("Sort news",{exact:true}).selectOption("newest");await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByText("Fed story",{exact:true})).toBeVisible();await noOverflow(page)});
 test("flow",async({page})=>{await page.goto("/v4/deep/flow");await expect(page.getByRole("heading",{name:"Flow Intelligence",level:1})).toBeVisible();await page.getByLabel("Ticker",{exact:true}).fill("NBIS");for(const n of ["Active only","Expired","All contracts","24h","72h","7d","All history"])await page.getByRole("button",{name:n,exact:true}).click();for(const n of ["Relative Flow","Persistence","Methodology","Feed"])await page.getByRole("tab",{name:n,exact:true}).click();await noOverflow(page)});
 test("events",async({page})=>{await page.goto("/v4/deep/events");await expect(page.getByRole("heading",{name:"Catalyst Calendar",level:1})).toBeVisible();for(const n of ["Calendar","Tracked Companies","Markets","Portfolios","My Events","Sources"]){const t=page.getByRole("tab",{name:n,exact:true});await t.click();await expect(t).toHaveAttribute("aria-selected","true")}await noOverflow(page)});
 test("data health",async({page})=>{await page.goto("/v4/deep/data-health");await expect(page.getByRole("heading",{name:"Data Health",level:1})).toBeVisible();const q=page.getByRole("textbox",{name:"Global ticker search",exact:true});await q.fill("MU");await expect(q).toHaveValue("MU");await noOverflow(page)});
 test("deep research and legacy navigation bridge",async({page})=>{await page.goto("/v4/deep/research/NBIS");await expect(page.getByRole("heading",{name:"NBIS",level:1})).toBeVisible();await expect(page.getByText("Security context",{exact:true})).toBeVisible();await page.getByText("Score history",{exact:true}).click();await page.getByText("Attached theses",{exact:true}).click();await page.evaluate(()=>window.dispatchEvent(new CustomEvent("daily-report-nav-request",{detail:{tab:"Research",symbol:"AAOI"}})));await expect(page).toHaveURL(/\/v4\/deep\/research\/AAOI$/);await noOverflow(page)});
});
