import {expect,test,Page,Route} from "@playwright/test";

const json=(route:Route,body:any,status=200)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});
const account={id:"usr_test",email:"test@example.com",name:"UI Audit",role:"owner",status:"approved",enabled:true};

async function mockBase(page:Page){
  await page.route("**/backend/**",async route=>{
    const u=new URL(route.request().url()),p=u.pathname,method=route.request().method();
    if(p.endsWith("/api/v1/auth/session"))return json(route,{account});
    if(p.endsWith("/api/v1/stack/overview"))return json(route,{version:"4.5-test",pipeline:["research","macro","opportunity","deployment"],layers:{research:{tracked_symbols:5,stored_market_snapshots:10,stored_feature_snapshots:8},macro:{rotation_history_days:22},opportunity:{methodology:"test"},deployment:{}}});
    if(p.includes("/api/v1/stack/research/"))return json(route,{symbol:p.split("/").pop(),registry:{name:"Nebius",sector:"Technology"},market:{price:99.12,retrieved_at:"2026-09-10T17:00:00Z",provider:"test",verification_status:"verified",source_url:"https://example.com/market",ma100:90,ma200:80,change_pct:1.2},latest_features:{buy_score:77,williams_r:-82,model_version:"test-v1",ma100_proximity:2.1},score_history:{buy_score_change:3,history:[{score:74}],largest_positive_drivers:[{component:"williams",buy_score_contribution_delta:2}],largest_negative_drivers:[],raw_driver_changes:[{field:"williams_r",label:"Williams %R",delta:-4}]},rotation_context:{proxy:"SMH",basis:"sector proxy",state:{state:"leading_stable",rotation_pressure:1.2,conviction:80,observations:4,data_age_hours:1}},flow_72h:{events:2},data_state:{market:true,fundamentals:true,feature_history_points:4},fundamentals:{pe_ratio:20,price_to_sales_ratio:4,quarterly_revenue_growth_yoy:.3},theses:[{id:1,title:"Test thesis",statement:"Test statement"}]});
    if(p.endsWith("/api/v1/stack/rotation"))return json(route,{rows:[{symbol:"SMH",name:"Semiconductors",state:"leading_stable",rotation_pressure:2,rotation_score:2,conviction:90,delta_1_observation:.2,delta_3_observations:.5,forward_bias:"leaders"},{symbol:"XLK",name:"Technology",state:"lagging_improving",rotation_pressure:.5,rotation_score:.4,conviction:60,delta_1_observation:.1,delta_3_observations:.2,forward_bias:"early_rotation_candidate"},{symbol:"XLE",name:"Energy",state:"leading_weakening",rotation_pressure:-2,rotation_score:-1,conviction:55,delta_1_observation:-.2,delta_3_observations:-.5,forward_bias:"rotation_out_risk"}],early_rotation:[{symbol:"XLK",name:"Technology",conviction:60}],outflow_risk:[{symbol:"XLE",name:"Energy",rotation_pressure:-2}],methodology:"test macro methodology"});
    if(p.endsWith("/api/v1/stack/candidates"))return json(route,{candidates:[{symbol:"NBIS",score:80,williams_r:-82,ma100_proximity:2,ma100_slope:.1,approach_velocity:.2,liquidity_score:9}],rows:[],stages:[{name:"Universe coverage",input:100,output:80,rule:"cached"}],coverage:{market_wide_ready:false,cached_snapshot_coverage_percent:80,registry_scannable:100,cached_scannable:80,technical_complete:70,technical_coverage_percent:70,limitation:"partial"},verification:{verified:60,primary_only:10},last_cache_update:"2026-09-10T17:00:00Z",deep_enrichment_symbols:["NBIS"],methodology:"test opportunity"});
    if(p.endsWith("/api/v1/stack/candidates/enrich"))return json(route,{jobs_added:1});
    if(p.endsWith("/api/v1/stack/deployment"))return json(route,{basket:u.searchParams.get("basket")||"ai-buildout",capital:Number(u.searchParams.get("capital")||1000),model:"Williams Priority",eligible:[{priority_rank:1,symbol:"NBIS",williams_r:-82,signal_month:"2026-09",fundamental_score:{score:70,grade:"B",coverage:.8,components:[{factor:"growth",score:70}]},priority_weight:1,suggested_dollars:Number(u.searchParams.get("capital")||1000),fundamental_source:{provider:"test",retrieved_at:"2026-09-10T17:00:00Z"}}],unavailable:[],methodology:"test deployment",fundamental_score_policy:"informational"});
    if(p.endsWith("/api/v1/opportunities/criteria"))return json(route,{criteria:[{key:"williams",label:"Williams %R",min_sessions:14,description:"Momentum",hypothesis:"Oversold",evidence_basis:"test",validation_status:"experimental"},{key:"ma100_proximity",label:"100MA proximity",min_sessions:100,description:"Distance",hypothesis:"Support",evidence_basis:"test",validation_status:"experimental"},{key:"ma50_proximity",label:"50MA proximity",min_sessions:50,description:"Distance",hypothesis:"Support",evidence_basis:"test",validation_status:"experimental"}],filters:[{key:"williams",label:"Williams %R",operators:["<=",">="],default_operator:"<=",default_value:-70}],default_formula:{criteria:{williams:60,ma100_proximity:40},filters:[]}});
    if(p.endsWith("/api/v1/opportunities/formulas")&&method==="GET")return json(route,{default:{id:"default",name:"Default",built_in:true,criteria:{williams:60,ma100_proximity:40},filters:[]},saved:[{id:9,name:"Saved Test",built_in:false,criteria:{williams:70,ma100_proximity:30},filters:[]}]});
    if(p.endsWith("/api/v1/opportunities/formulas")&&method==="POST")return json(route,{id:10,name:"Audit Formula",built_in:false,criteria:{williams:60},filters:[]});
    if(/\/api\/v1\/opportunities\/formulas\/\d+$/.test(p)&&method==="PUT")return json(route,{id:9,name:"Saved Test",built_in:false});
    if(/\/api\/v1\/opportunities\/formulas\/\d+$/.test(p)&&method==="DELETE")return json(route,{status:"deleted"});
    if(p.endsWith("/api/v1/opportunities/index"))return json(route,{rows:[{formula_rank:1,quality_adjusted_rank:1,symbol:"NBIS",sector:"Technology",score:80,quality_adjusted_score:78,quality_confidence:.9,raw_criteria:{williams:-82,ma100_proximity:2,ma50_proximity:4,ma100_slope:.1,approach_velocity:.2,relative_volume:1.3,fundamental_quality:70,valuation_quality:60,liquidity:9},quality:{state:"verified"}}],counts:{formula_complete:1,filtered_out:0},quality_counts:{degraded:0,incomplete:0},formula:{label:"test"},last_cache_update:"2026-09-10T17:00:00Z"});
    if(p.endsWith("/api/v1/events"))return json(route,{events:[{event_date:"2026-09-10",time:"10:00",title:"CPI",impact:"high",category:"Macro",source:"Test",source_url:"https://example.com/cpi"},{event_date:"2026-09-11",title:"Custom",impact:"medium",category:"Custom",source:"User event",custom_event_id:7}],providers:[{provider:"Test",count:2,status:"ok"}]});
    if(p.endsWith("/api/v1/events/tracked-companies"))return json(route,{events:[{event_date:"2026-09-12",title:"NBIS earnings",impact:"high",category:"Earnings",source:"Test",symbol:"NBIS",tracked_via:["Markets","Portfolio"]}],count:1,markets_symbols:["NBIS"],portfolio_symbols:["NBIS"],refreshed_symbols:[],deferred_symbols:[],methodology:"test"});
    if(p.endsWith("/api/v1/events/custom")&&method==="POST")return json(route,{id:8});
    if(/\/api\/v1\/events\/custom\/\d+$/.test(p)&&method==="DELETE")return json(route,{status:"deleted"});
    if(p.endsWith("/api/v1/news/world"))return json(route,{provider:"Test",synthesis_model:"deterministic",cache:"fresh",synthesis_policy:"test",taxonomy_counts:{monetary_policy:1},stories:[{story_id:"s1",headline:"Rates story",category:"monetary_policy",article_count:1,source_count:1,importance_score:90,timeline:[{title:"Timeline item",url:"https://example.com/story",published_at:"2026-09-10T16:00:00Z",domain:"example.com"}]}],articles:[{url:"https://example.com/a",title:"Fed story",importance_score:90,relevance_score:90,primary_category:"monetary_policy",macro_categories:["monetary_policy"],domain:"example.com",published_at:"2026-09-10T16:00:00Z",why_it_matters:"test",first_order_effects:["rates"],second_order_effects:["growth"],effect_policy:"hypothesis",exposure_map:{tickers:["NBIS"],themes:["AI"],sectors:["Tech"],mapping_basis:"keyword",causal_confidence:"association_only"}}]});
    return json(route,{});
  });
}
async function expectNoHorizontalOverflow(page:Page){const px=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);expect(px).toBeLessThanOrEqual(1)}

test.describe("V4 decision stack exhaustive controls",()=>{
  test.beforeEach(async({page})=>{await mockBase(page);await page.goto("/v4");await expect(page.getByRole("heading",{name:"Decision Stack"})).toBeVisible()});
  test("research search, layout, deep links and global search",async({page})=>{const localTicker=page.getByLabel("Ticker");await localTicker.fill("AAOI");await page.getByRole("button",{name:"Open"}).click();await expect(page.getByText("AAOI",{exact:true}).first()).toBeVisible();const layout=page.getByRole("button",{name:"Layout"});await layout.click();await expect(layout).toHaveAttribute("aria-expanded","true");const panel=page.locator(".v4-layout-panel");const hide=panel.getByRole("button",{name:"Hide"}).first();if(await hide.count()){await hide.click();await panel.getByRole("button",{name:"Show"}).first().click()}const down=panel.getByRole("button",{name:/Move .* down/}).first();if(await down.count()&&await down.isEnabled())await down.click();await panel.getByRole("button",{name:"Reset layer"}).click();await page.getByText("Deep workspaces",{exact:true}).click();await expect(page.getByRole("navigation",{name:"research deep workspaces"})).toBeVisible();const global=page.getByLabel("Global ticker search");await global.fill("mu");await expect(global).toHaveValue("MU");await expect(page.getByRole("button",{name:"Research"})).toBeEnabled();await expectNoHorizontalOverflow(page)});
  test("macro sorting, filters and ticker drilldown",async({page})=>{await page.getByRole("button",{name:/Macro/}).click();await expect(page.getByText("3 groups")).toBeVisible();const sortGroup=page.getByRole("group",{name:"Click a metric to sort macro rotation groups"});for(const name of ["Rotation pressure","Conviction","1-observation change","3-observation change","Ticker"]){await sortGroup.getByRole("button",{name:new RegExp(name)}).click()}await page.getByLabel("View").selectOption("early");await expect(page.getByText("1 shown")).toBeVisible();await page.getByLabel("Rank metric").selectOption("symbol");await page.getByRole("button",{name:/Sort descending|Sort ascending/}).click();await page.getByTitle("Open XLK research").click();await expect(page.getByText("XLK",{exact:true}).first()).toBeVisible();await expectNoHorizontalOverflow(page)});
  test("opportunity formula, filters, presets, ranking and enrich",async({page})=>{await page.getByRole("button",{name:/Opportunity/}).click();await expect(page.getByText(/Partial cached-market scan/)).toBeVisible();const addCriterion=page.getByLabel("Add Opportunity criterion");await addCriterion.selectOption("ma50_proximity");await page.locator(".formula-actions").getByRole("button",{name:"Add"}).click();await expect(page.getByLabel("50MA proximity weight")).toBeVisible();await page.getByRole("button",{name:"Remove 50MA proximity"}).click();const addFilter=page.getByLabel("Add hard screen");await addFilter.selectOption("williams");await page.locator(".filter-add").getByRole("button",{name:"Add"}).click();await page.getByLabel("Williams %R operator").selectOption(">=");await page.getByLabel("Williams %R threshold").fill("-80");await page.getByRole("button",{name:"Remove Williams %R filter"}).click();await page.getByRole("button",{name:"Saved Test"}).click();const formulaName=page.getByLabel("Formula name");await formulaName.fill("Audit Formula");await page.getByRole("button",{name:"Save New"}).click();await page.getByRole("button",{name:"Duplicate"}).click();const sort=page.getByRole("group",{name:"Click a metric to sort opportunity index"});for(const name of ["Index","Williams %R","100MA distance","Ticker"]){await sort.getByRole("button",{name:name,exact:true}).click()}await page.getByTitle("Open NBIS details").click();await expect(page.getByTitle("Open NBIS details")).toHaveAttribute("aria-expanded","true");await page.getByRole("button",{name:"Enrich shortlist"}).click();await expect(page.getByText(/1 enrichment job queued/)).toBeVisible();await expectNoHorizontalOverflow(page)});
  test("deployment controls and drilldown",async({page})=>{await page.getByRole("button",{name:/Deployment/}).click();await page.getByLabel("Deployment basket").selectOption("watchlist");await page.getByLabel("New capital").fill("2500");await page.getByRole("button",{name:"Calculate"}).click();await expect(page.getByText("$2,500",{exact:true})).toBeVisible();await page.getByText("Fundamental score details").click();await page.locator(".allocation-row-button").first().click();await expect(page.getByText("NBIS",{exact:true}).first()).toBeVisible();await expectNoHorizontalOverflow(page)});
});

test.describe("V4 deep workspaces interaction coverage",()=>{
  test.beforeEach(async({page})=>{await mockBase(page)});
  test("world news controls and disclosures",async({page})=>{await page.goto("/v4/deep/world-news");await expect(page.getByRole("heading",{name:"World News"})).toBeVisible();await page.getByLabel("Topic").selectOption("Rates & Central Banks");await page.getByLabel("Macro category").selectOption("monetary_policy");await page.getByLabel("Time window").selectOption("168");await page.getByLabel("Sort news").selectOption("newest");await page.getByRole("button",{name:"Refresh"}).click();await expect(page.getByText("Fed story")).toBeVisible();await expect(page.getByRole("link",{name:/Open publisher/})).toHaveAttribute("href","https://example.com/a");await expectNoHorizontalOverflow(page)});
  test("events tabs, filters, calendar navigation and custom event",async({page})=>{await page.goto("/v4/deep/events");await expect(page.getByRole("heading",{name:"Events"})).toBeVisible();await page.getByRole("button",{name:"Refresh all"}).click();for(const tab of ["Tracked Companies","Markets","Portfolios","My Events","Sources","Calendar"]){await page.getByRole("tab",{name:tab}).click();await expect(page.getByRole("tab",{name:tab})).toHaveAttribute("aria-selected","true")}await page.getByText("Filters",{exact:true}).click();await page.getByLabel("Impact").selectOption("high");await page.getByLabel("Category").selectOption("Macro");await page.getByRole("button",{name:"← Previous"}).click();await page.getByRole("button",{name:"Next →"}).click();await page.getByRole("button",{name:"Agenda"}).click();await expect(page.getByRole("button",{name:"Agenda"})).toHaveAttribute("aria-pressed","true");await page.getByRole("tab",{name:"My Events"}).click();await page.getByLabel("Date").fill("2026-09-20");await page.getByLabel("Title").fill("Audit event");await page.getByLabel("Ticker (optional)").fill("nbis");await page.getByLabel("Notes").fill("audit");await page.getByRole("button",{name:"Add event"}).click();await expectNoHorizontalOverflow(page)});
  test("deep shell global search and back navigation",async({page})=>{await page.goto("/v4/deep/world-news");const search=page.getByLabel("Global ticker search");await search.fill("MU");await expect(page.getByRole("button",{name:"Research"})).toBeEnabled();await expect(page.getByRole("link",{name:/Decision Stack/})).toHaveAttribute("href","/v4")});
});
